const json=(value)=>JSON.stringify(value??null)
const parseJson=(value,fallback)=>{if(value===null||value===undefined||value==='')return fallback;if(typeof value==='object')return value;try{return JSON.parse(value)}catch{return fallback}}
const formatTime=(value)=>value instanceof Date?value.toLocaleString('zh-CN',{hour12:false}).replaceAll('/','-'):String(value||'')

const seedSources=[
  ['SRC-ERP','集团ERP采购视图','数据库视图','采购项目、订单、供应商','张海','增量','今天 11:52','启用'],
  ['SRC-OA','OA审批事件接口','API','审批实例、节点、意见','刘敏','事件','今天 12:06','启用'],
  ['SRC-TREASURY','司库付款消息','消息','付款申请、账户、流水','王宁','事件','今天 12:08','启用'],
  ['SRC-EXTERNAL','工商司法外部数据','API','主体、股东、司法风险','陈洁','增量','昨天 23:00','异常'],
]
const seedGraphs=[
  ['GRAPH-20260717.2','ONT-PROC','BASE v1.6 / PROC v2.2','MAP v3.4','2026-01-01 至 2026-07-17',128542,309861,48210,0,8,'已发布','2026-07-17 08:45:00'],
  ['GRAPH-20260717.3','ONT-PROC','BASE v1.6 / PROC v2.2','MAP v3.5','2026-01-01 至 2026-07-17',129104,311202,48637,0,3,'待发布',null],
  ['GRAPH-20260716.4','ONT-FIN','BASE v1.6 / FIN v1.0','MAP v2.8','2025-01-01 至 2026-07-16',98412,206871,39605,2,12,'失败',null],
]

function mapSource(row){return{id:row.id,name:row.name,mode:row.mode,range:row.data_range,owner:row.owner,syncMode:row.sync_mode,lastSuccess:row.last_success,status:row.status}}
function mapMetadata(row){return{id:String(row.id),sourceId:row.source_id,tableName:row.table_name,displayName:row.display_name,fieldCount:Number(row.field_count),summary:row.summary}}
function mapMapping(row){return{id:String(row.id),sourceId:row.source_id,type:row.mapping_type,sourceField:row.source_field,transform:row.transform_rule,targetCode:row.target_code,confidence:Number(row.confidence),status:row.status}}
function mapSync(row){return{id:row.id,sourceId:row.source_id,sourceName:row.source_name,mode:row.sync_mode,startedAt:formatTime(row.started_at),processed:Number(row.processed_count),errors:Number(row.error_count),duration:row.duration_text,result:row.result}}
function mapGraph(row){return{id:row.id,ontologyId:row.ontology_id,ontologyVersion:row.ontology_version,mappingVersion:row.mapping_version,range:row.data_range,entities:Number(row.entity_count),relations:Number(row.relation_count),events:Number(row.event_count),blockers:Number(row.blockers),warnings:Number(row.warnings),status:row.status,publishedAt:row.published_at?formatTime(row.published_at):'—'}}
function mapIssue(row){return{id:row.id,graphId:row.graph_id,title:row.title,level:row.level,description:row.description,sourceRef:row.source_ref,status:row.status}}
function mapGovernance(row){return{id:row.id,graphId:row.graph_id,objectType:row.object_type,candidates:parseJson(row.candidate_json,[]),evidence:row.evidence,suggestion:row.suggestion,level:row.level,status:row.status,result:row.result||'',reason:row.reason||''}}

async function seedMetadata(pool,sourceId){
  const rows=sourceId==='SRC-ERP'?
    [['purchase_project','采购项目视图',32,'项目、预算、采购方式、组织与时间字段'],['supplier_master','供应商主数据',28,'供应商主体、证照、联系方式字段'],['purchase_order','采购订单',41,'订单、金额、合同与明细字段'],['bid_event','招投标事件',18,'报名、评审、中标确认事件字段']]:
    [['source_object','来源对象',16,'自动解析的来源对象与字段'],['source_event','来源事件',12,'自动解析的业务事件字段']]
  for(const row of rows)await pool.query('INSERT IGNORE INTO data_source_metadata (source_id,table_name,display_name,field_count,summary) VALUES (?,?,?,?,?)',[sourceId,...row])
}
async function seedMappings(pool,sourceId){
  const rows=[
    ['属性','supplier_code','直接映射','PROC.Supplier.credit_code',98,'有效'],
    ['属性','supplier_name','去空格','PROC.Supplier.name',99,'有效'],
    ['属性','credit_code','大写转换','PROC.Supplier.credit_code',96,'有效'],
    ['关系','supplier_id + phone','哈希关联','PROC.supplier_contact',95,'有效'],
    ['关系','phone + reviewer_id','哈希关联','PROC.shared_contact',92,'有效'],
    ['事件','bid_confirm_id','组合键去重','PROC.BidConfirmed',99,'有效'],
  ]
  for(const row of rows)await pool.query('INSERT IGNORE INTO semantic_mappings (source_id,mapping_type,source_field,transform_rule,target_code,confidence,status) VALUES (?,?,?,?,?,?,?)',[sourceId,...row])
}

export async function initializeDataGraphDatabase(pool){
  await pool.query(`CREATE TABLE IF NOT EXISTS data_sources (id VARCHAR(64) PRIMARY KEY,name VARCHAR(160) NOT NULL,mode VARCHAR(40) NOT NULL,data_range VARCHAR(300) NOT NULL,owner VARCHAR(80) NOT NULL,sync_mode VARCHAR(40) NOT NULL,last_success VARCHAR(80) NOT NULL DEFAULT '未同步',status VARCHAR(24) NOT NULL DEFAULT '草稿',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
  await pool.query(`CREATE TABLE IF NOT EXISTS data_source_metadata (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,source_id VARCHAR(64) NOT NULL,table_name VARCHAR(120) NOT NULL,display_name VARCHAR(160) NOT NULL,field_count INT NOT NULL DEFAULT 0,summary VARCHAR(500) NOT NULL DEFAULT '',updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uk_source_table (source_id,table_name),CONSTRAINT fk_metadata_source FOREIGN KEY (source_id) REFERENCES data_sources(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
  await pool.query(`CREATE TABLE IF NOT EXISTS semantic_mappings (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,source_id VARCHAR(64) NOT NULL,mapping_type VARCHAR(24) NOT NULL,source_field VARCHAR(160) NOT NULL,transform_rule VARCHAR(160) NOT NULL,target_code VARCHAR(160) NOT NULL,confidence INT NOT NULL DEFAULT 0,status VARCHAR(24) NOT NULL DEFAULT '待校验',updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uk_mapping (source_id,mapping_type,source_field,target_code),CONSTRAINT fk_mapping_source FOREIGN KEY (source_id) REFERENCES data_sources(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
  await pool.query(`CREATE TABLE IF NOT EXISTS sync_records (id VARCHAR(80) PRIMARY KEY,source_id VARCHAR(64) NOT NULL,source_name VARCHAR(160) NOT NULL,sync_mode VARCHAR(40) NOT NULL,started_at DATETIME NOT NULL,processed_count INT NOT NULL DEFAULT 0,error_count INT NOT NULL DEFAULT 0,duration_text VARCHAR(40) NOT NULL,result VARCHAR(24) NOT NULL,KEY idx_sync_source (source_id,started_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
  await pool.query(`CREATE TABLE IF NOT EXISTS graph_versions (id VARCHAR(64) PRIMARY KEY,ontology_id VARCHAR(64) NOT NULL DEFAULT 'ONT-PROC',ontology_version VARCHAR(160) NOT NULL,mapping_version VARCHAR(80) NOT NULL,data_range VARCHAR(160) NOT NULL,entity_count INT NOT NULL DEFAULT 0,relation_count INT NOT NULL DEFAULT 0,event_count INT NOT NULL DEFAULT 0,blockers INT NOT NULL DEFAULT 0,warnings INT NOT NULL DEFAULT 0,status VARCHAR(24) NOT NULL DEFAULT '待发布',published_at DATETIME NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_graph_status (status,updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
  await pool.query(`CREATE TABLE IF NOT EXISTS graph_quality_issues (id VARCHAR(80) PRIMARY KEY,graph_id VARCHAR(64) NOT NULL,title VARCHAR(120) NOT NULL,level VARCHAR(24) NOT NULL,description VARCHAR(500) NOT NULL,source_ref VARCHAR(200) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT '待处理',KEY idx_issue_graph (graph_id,status),CONSTRAINT fk_issue_graph FOREIGN KEY (graph_id) REFERENCES graph_versions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
  await pool.query(`CREATE TABLE IF NOT EXISTS graph_governance_tasks (id VARCHAR(80) PRIMARY KEY,graph_id VARCHAR(64) NOT NULL,object_type VARCHAR(40) NOT NULL,candidate_json JSON NOT NULL,evidence VARCHAR(300) NOT NULL,suggestion VARCHAR(60) NOT NULL,level VARCHAR(16) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT '待处理',result VARCHAR(40) NOT NULL DEFAULT '',reason VARCHAR(500) NOT NULL DEFAULT '',KEY idx_governance_graph (graph_id,status),CONSTRAINT fk_governance_graph FOREIGN KEY (graph_id) REFERENCES graph_versions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
  for(const item of seedSources)await pool.query('INSERT IGNORE INTO data_sources (id,name,mode,data_range,owner,sync_mode,last_success,status) VALUES (?,?,?,?,?,?,?,?)',item)
  for(const item of seedGraphs)await pool.query('INSERT IGNORE INTO graph_versions (id,ontology_id,ontology_version,mapping_version,data_range,entity_count,relation_count,event_count,blockers,warnings,status,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',item)
  for(const item of seedSources){await seedMetadata(pool,item[0]);await seedMappings(pool,item[0])}
  await pool.query('INSERT IGNORE INTO sync_records (id,source_id,source_name,sync_mode,started_at,processed_count,error_count,duration_text,result) VALUES (?,?,?,?,?,?,?,?,?)',['SYNC-0717-006','SRC-TREASURY','司库付款消息','事件','2026-07-17 12:08:00',326,0,'3秒','成功'])
  await pool.query('INSERT IGNORE INTO sync_records (id,source_id,source_name,sync_mode,started_at,processed_count,error_count,duration_text,result) VALUES (?,?,?,?,?,?,?,?,?)',['SYNC-0717-005','SRC-OA','OA审批事件接口','事件','2026-07-17 12:06:00',1824,3,'18秒','部分成功'])
  await pool.query('INSERT IGNORE INTO graph_quality_issues (id,graph_id,title,level,description,source_ref,status) VALUES (?,?,?,?,?,?,?)',['GQI-001','GRAPH-20260717.3','主标识缺失','阻断','供应商记录缺少统一社会信用代码','集团ERP采购视图 · 2条','待处理'])
  await pool.query('INSERT IGNORE INTO graph_quality_issues (id,graph_id,title,level,description,source_ref,status) VALUES (?,?,?,?,?,?,?)',['GQI-002','GRAPH-20260717.3','来源结构变化','警告','OA审批接口新增 approver_org 字段','OA审批事件接口 · 1项','待处理'])
  await pool.query('INSERT IGNORE INTO graph_governance_tasks (id,graph_id,object_type,candidate_json,evidence,suggestion,level,status) VALUES (?,?,?,?,?,?,?,?)',['GOV-0018','GRAPH-20260717.2','供应商',json(['华北数字科技有限公司','华北数字科技（北京）有限公司']),'统一社会信用代码一致','确认合并','高','待处理'])
}

async function listSources(pool){const [rows]=await pool.query('SELECT * FROM data_sources ORDER BY updated_at DESC,id ASC');return rows.map(mapSource)}
async function createSource(pool,payload){if(!String(payload.name||'').trim()||!String(payload.range||'').trim())throw Object.assign(new Error('请填写数据源名称和数据范围'),{status:400});const [rows]=await pool.query('SELECT COUNT(*) AS total FROM data_sources');const id='SRC-'+String(Number(rows[0].total)+1).padStart(3,'0');await pool.query('INSERT INTO data_sources (id,name,mode,data_range,owner,sync_mode,last_success,status) VALUES (?,?,?,?,?,?,?,?)',[id,String(payload.name).trim(),payload.mode||'数据库视图',payload.range,payload.owner||'张海',payload.syncMode||'增量','未同步','草稿']);await seedMetadata(pool,id);await seedMappings(pool,id);return mapSource((await pool.query('SELECT * FROM data_sources WHERE id=?',[id]))[0][0])}
async function getSource(pool,id){const [rows]=await pool.query('SELECT * FROM data_sources WHERE id=?',[id]);return rows[0]||null}
async function testSource(pool,id){const source=await getSource(pool,id);if(!source)throw Object.assign(new Error('数据源不存在'),{status:404});await pool.query("UPDATE data_sources SET status=IF(status='异常','草稿',status) WHERE id=?",[id]);return{ok:true,message:'连接测试成功，耗时86ms',source:mapSource({...source,status:source.status==='异常'?'草稿':source.status})}}
async function toggleSource(pool,id,enabled){const source=await getSource(pool,id);if(!source)throw Object.assign(new Error('数据源不存在'),{status:404});if(enabled){const [mappings]=await pool.query("SELECT COUNT(*) AS total FROM semantic_mappings WHERE source_id=? AND status='有效'",[id]);if(!Number(mappings[0].total))throw Object.assign(new Error('请先完成语义映射校验'),{status:409})}await pool.query('UPDATE data_sources SET status=? WHERE id=?',[enabled?'启用':'停用',id]);return mapSource((await pool.query('SELECT * FROM data_sources WHERE id=?',[id]))[0][0])}
async function metadata(pool,id){await seedMetadata(pool,id);const [rows]=await pool.query('SELECT * FROM data_source_metadata WHERE source_id=? ORDER BY table_name',[id]);return rows.map(mapMetadata)}
async function mappings(pool,id,type=''){await seedMappings(pool,id);const params=[id];let where='WHERE source_id=?';if(type){where+=' AND mapping_type=?';params.push(type)}const [rows]=await pool.query(`SELECT * FROM semantic_mappings ${where} ORDER BY mapping_type,id`,params);return rows.map(mapMapping)}
async function validateMappings(pool,id){const [rows]=await pool.query('SELECT COUNT(*) AS total FROM semantic_mappings WHERE source_id=?',[id]);if(!Number(rows[0].total))throw Object.assign(new Error('暂无可校验映射'),{status:409});await pool.query("UPDATE semantic_mappings SET status='有效' WHERE source_id=?",[id]);return{ok:true,message:'语义映射校验通过'}}
async function syncSource(pool,id){const source=await getSource(pool,id);if(!source)throw Object.assign(new Error('数据源不存在'),{status:404});const recordId='SYNC-'+Date.now().toString(36).toUpperCase();await pool.query('INSERT INTO sync_records (id,source_id,source_name,sync_mode,started_at,processed_count,error_count,duration_text,result) VALUES (?,?,?,?,NOW(),?,?,?,?)',[recordId,id,source.name,source.sync_mode,Math.floor(300+Math.random()*6000),0,'12秒','成功']);await pool.query("UPDATE data_sources SET last_success='刚刚',status='启用' WHERE id=?",[id]);return{recordId,message:'同步完成，已写入同步记录'}}
async function listSync(pool){const [rows]=await pool.query('SELECT * FROM sync_records ORDER BY started_at DESC LIMIT 30');return rows.map(mapSync)}
async function listGraphs(pool,url){const status=String(url.searchParams.get('status')||'');const params=[];let where='';if(status){where='WHERE status=?';params.push(status)}const [rows]=await pool.query(`SELECT * FROM graph_versions ${where} ORDER BY updated_at DESC,id DESC`,params);return rows.map(mapGraph)}
async function createGraph(pool,payload){const id=String(payload.id||`GRAPH-${new Date().toISOString().slice(0,10).replaceAll('-','')}.${Math.floor(Math.random()*9)+1}`).trim().toUpperCase();await pool.query('INSERT INTO graph_versions (id,ontology_id,ontology_version,mapping_version,data_range,entity_count,relation_count,event_count,blockers,warnings,status) VALUES (?,?,?,?,?,?,?,?,?,? ,?)',[id,payload.ontologyId||'ONT-PROC',payload.ontologyVersion||'BASE v1.6 / PROC v2.2',payload.mappingVersion||'MAP v3.6',payload.range||'2026-01-01 至今',Number(payload.entities||129000),Number(payload.relations||311000),Number(payload.events||48600),Number(payload.blockers||0),Number(payload.warnings||0),'待发布']);return mapGraph((await pool.query('SELECT * FROM graph_versions WHERE id=?',[id]))[0][0])}
async function publishGraph(pool,id){const connection=await pool.getConnection();try{await connection.beginTransaction();const [rows]=await connection.query('SELECT * FROM graph_versions WHERE id=? FOR UPDATE',[id]);if(!rows.length)throw Object.assign(new Error('图谱版本不存在'),{status:404});const graph=rows[0];if(Number(graph.blockers)>0)throw Object.assign(new Error(`存在${graph.blockers}个阻断问题，不能发布`),{status:409});if(graph.status!=='待发布')throw Object.assign(new Error('只有待发布图谱可以发布'),{status:409});await connection.query("UPDATE graph_versions SET status='已归档' WHERE status='已发布'");await connection.query("UPDATE graph_versions SET status='已发布',published_at=NOW() WHERE id=?",[id]);await connection.commit();return mapGraph((await pool.query('SELECT * FROM graph_versions WHERE id=?',[id]))[0][0])}catch(error){await connection.rollback();throw error}finally{connection.release()}}
async function resolveIssue(pool,graphId,issueId){await pool.query("UPDATE graph_quality_issues SET status='已处理' WHERE graph_id=? AND id=?",[graphId,issueId]);return{ok:true,message:'质量问题已处理'}}
async function govern(pool,graphId,taskId,payload){if(!String(payload.reason||'').trim())throw Object.assign(new Error('治理原因不能为空'),{status:400});await pool.query("UPDATE graph_governance_tasks SET status='已处理',result=?,reason=? WHERE graph_id=? AND id=?",[payload.result||'合并',payload.reason,graphId,taskId]);return{ok:true,message:`实体${payload.result||'合并'}完成，影响记录已生成`}}

export async function handleDataGraphApi(req,res,url,{pool,sendJson,readBody}){
  if(url.pathname==='/api/data-sources'&&req.method==='GET'){sendJson(res,200,await listSources(pool));return true}
  if(url.pathname==='/api/data-sources'&&req.method==='POST'){sendJson(res,201,await createSource(pool,await readBody(req)));return true}
  const sourceAction=url.pathname.match(/^\/api\/data-sources\/([^/]+)\/(test|toggle|metadata\/parse|metadata|mappings\/validate|mappings|sync)$/)
  if(sourceAction){const id=decodeURIComponent(sourceAction[1]);const action=sourceAction[2];if(action==='test'&&req.method==='POST'){sendJson(res,200,await testSource(pool,id));return true}if(action==='toggle'&&req.method==='POST'){sendJson(res,200,await toggleSource(pool,id,Boolean((await readBody(req)).enabled)));return true}if(action==='metadata/parse'&&req.method==='POST'){sendJson(res,200,await metadata(pool,id));return true}if(action==='metadata'&&req.method==='GET'){sendJson(res,200,await metadata(pool,id));return true}if(action==='mappings'&&req.method==='GET'){sendJson(res,200,await mappings(pool,id,String(url.searchParams.get('type')||'')));return true}if(action==='mappings/validate'&&req.method==='POST'){sendJson(res,200,await validateMappings(pool,id));return true}if(action==='sync'&&req.method==='POST'){sendJson(res,201,await syncSource(pool,id));return true}}
  if(url.pathname==='/api/sync-records'&&req.method==='GET'){sendJson(res,200,await listSync(pool));return true}
  if(url.pathname==='/api/graphs'&&req.method==='GET'){sendJson(res,200,await listGraphs(pool,url));return true}
  if(url.pathname==='/api/graphs'&&req.method==='POST'){sendJson(res,201,await createGraph(pool,await readBody(req)));return true}
  const graphIssue=url.pathname.match(/^\/api\/graphs\/([^/]+)\/issues(?:\/([^/]+)\/resolve)?$/)
  if(graphIssue){const graphId=decodeURIComponent(graphIssue[1]);if(req.method==='GET'){const [rows]=await pool.query('SELECT * FROM graph_quality_issues WHERE graph_id=? ORDER BY status,id',[graphId]);sendJson(res,200,rows.map(mapIssue));return true}if(req.method==='POST'&&graphIssue[2]){sendJson(res,200,await resolveIssue(pool,graphId,decodeURIComponent(graphIssue[2])));return true}}
  const graphGovern=url.pathname.match(/^\/api\/graphs\/([^/]+)\/governance(?:\/([^/]+))?$/)
  if(graphGovern){const graphId=decodeURIComponent(graphGovern[1]);if(req.method==='GET'){const [rows]=await pool.query('SELECT * FROM graph_governance_tasks WHERE graph_id=? ORDER BY status,id',[graphId]);sendJson(res,200,rows.map(mapGovernance));return true}if(req.method==='POST'&&graphGovern[2]){sendJson(res,200,await govern(pool,graphId,decodeURIComponent(graphGovern[2]),await readBody(req)));return true}}
  const publish=url.pathname.match(/^\/api\/graphs\/([^/]+)\/publish$/)
  if(publish&&req.method==='POST'){sendJson(res,200,await publishGraph(pool,decodeURIComponent(publish[1])));return true}
  return false
}
