import { configHash, editableSceneStatuses, getBoundRuleRows, getCurrentSceneRow, getSceneAggregate, makeBusinessId, mapRuleRow, parseJson, snapshotForHash, toJson, validateRuleRecord, writeSceneAudit } from './sceneRuleRepo.js'

async function getRule(pool,id){
  const [rows]=await pool.query(`SELECT rv.*,rr.scene_id,rr.code,sv.name AS scene_name,sv.status AS scene_status,sv.ontology_id,sv.graph_version FROM rule_versions rv JOIN risk_rules rr ON rr.id=rv.rule_id JOIN scene_versions sv ON sv.id=rv.scene_version_id WHERE rv.id=? OR (rr.id=? AND sv.id=(SELECT current_version_id FROM risk_scenes WHERE id=rr.scene_id)) OR (rr.code=? AND sv.id=(SELECT current_version_id FROM risk_scenes WHERE id=rr.scene_id)) LIMIT 1`,[id,id,id])
  return rows.length?mapRuleRow(rows[0]):null
}

async function listRules(pool,url){
  const keyword=String(url.searchParams.get('keyword')||'').trim();const params=[];const where=['sv.id=rs.current_version_id']
  if(keyword){where.push('(rv.name LIKE ? OR rr.code LIKE ? OR sv.name LIKE ?)');params.push(`%${keyword}%`,`%${keyword}%`,`%${keyword}%`)}
  const [rows]=await pool.query(`SELECT rv.*,rr.scene_id,rr.code,sv.name AS scene_name,sv.status AS scene_status,sv.ontology_id,sv.graph_version FROM risk_rules rr JOIN rule_versions rv ON rv.rule_id=rr.id JOIN scene_versions sv ON sv.id=rv.scene_version_id JOIN risk_scenes rs ON rs.id=rr.scene_id WHERE ${where.join(' AND ')} ORDER BY rv.updated_at DESC`,params)
  return rows.map(mapRuleRow)
}

async function createRule(pool,sceneId,payload){
  const scene=await getCurrentSceneRow(pool,sceneId);if(!scene)throw Object.assign(new Error('场景不存在'),{status:404});if(!editableSceneStatuses.has(scene.status))throw Object.assign(new Error('当前场景版本不可新增规则'),{status:409})
  const [counts]=await pool.query('SELECT COUNT(*) AS total FROM risk_rules');const code=String(payload.code||`RULE-${String(Number(counts[0].total)+1).padStart(3,'0')}`).trim().toUpperCase();const ruleId=makeBusinessId('RULE');const versionId=makeBusinessId('RV');const connection=await pool.getConnection()
  try{
    await connection.beginTransaction();await connection.query('INSERT INTO risk_rules (id,scene_id,code) VALUES (?,?,?)',[ruleId,scene.scene_id,code]);await connection.query(`INSERT INTO rule_versions (id,rule_id,scene_version_id,version,name,rule_type,risk_level,enabled,status,condition_json,path_json,time_json,aggregate_json,exception_json,output_json,evidence_json,policy_json,failure_strategy,summary) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[versionId,ruleId,scene.id,scene.version,payload.name||'未命名规则',payload.type||'属性',payload.level||scene.risk_level,1,'草稿',toJson({id:'group-root',logic:'AND',items:[]}),toJson({hops:[]}),toJson({eventCode:scene.event_code,windowValue:scene.observation_value,windowUnit:scene.observation_unit,direction:'之前'}),toJson({function:'COUNT',fieldCode:'',groupBy:'',operator:'大于等于',threshold:2}),toJson({enabled:false,description:'',whitelist:[]}),toJson([]),toJson([]),toJson({name:'',version:'',clause:''}),'进入异常队列','尚未生成规则摘要']);await connection.query("UPDATE scene_versions SET status='草稿',validation_json=NULL,last_trial_id=NULL,dependency_hash='',lock_version=lock_version+1 WHERE id=?",[scene.id]);await writeSceneAudit(connection,scene.id,'新建规则',`${code} / ${payload.name||'未命名规则'}`);await connection.commit();return await getRule(pool,versionId)
  }catch(error){await connection.rollback();if(error?.code==='ER_DUP_ENTRY')throw Object.assign(new Error(`规则编码 ${code} 已存在`),{status:409});throw error}finally{connection.release()}
}

function summarize(payload){
  const count=(payload.conditions?.items||[]).length
  const typeText=payload.type==='关系路径'?`按${(payload.pathConfig?.hops||[]).length}跳关系路径判断`:payload.type==='时序'?`在${payload.timeConfig?.windowValue||0}${payload.timeConfig?.windowUnit||'天'}窗口内判断`:payload.type==='聚合'?`按${payload.aggregateConfig?.function||'COUNT'}聚合并比较阈值`:'按属性与字段条件判断'
  return `${typeText}，组合${count}个一级条件项；命中后生成${payload.level||'高'}风险线索并固化${(payload.outputs||[]).length}项输出。`
}

async function updateRule(pool,id,payload){
  const [rows]=await pool.query('SELECT rv.*,rr.scene_id FROM rule_versions rv JOIN risk_rules rr ON rr.id=rv.rule_id WHERE rv.id=?',[id]);if(!rows.length)throw Object.assign(new Error('规则不存在'),{status:404});const row=rows[0];const scene=await getCurrentSceneRow(pool,row.scene_id);if(!scene||!editableSceneStatuses.has(scene.status))throw Object.assign(new Error('当前场景版本不可编辑规则'),{status:409});if(Number(payload.lockVersion)!==Number(row.lock_version))throw Object.assign(new Error('规则已被其他人更新，请刷新后重试'),{status:409})
  const [result]=await pool.query(`UPDATE rule_versions SET name=?,rule_type=?,risk_level=?,enabled=?,status='草稿',condition_json=?,path_json=?,time_json=?,aggregate_json=?,exception_json=?,output_json=?,evidence_json=?,policy_json=?,failure_strategy=?,summary=?,lock_version=lock_version+1 WHERE id=? AND lock_version=?`,[payload.name??row.name,payload.type??row.rule_type,payload.level??row.risk_level,payload.enabled===false?0:1,toJson(payload.conditions??parseJson(row.condition_json,{})),toJson(payload.pathConfig??parseJson(row.path_json,{})),toJson(payload.timeConfig??parseJson(row.time_json,{})),toJson(payload.aggregateConfig??parseJson(row.aggregate_json,{})),toJson(payload.exceptions??parseJson(row.exception_json,{})),toJson(payload.outputs??parseJson(row.output_json,[])),toJson(payload.evidence??parseJson(row.evidence_json,[])),toJson(payload.policy??parseJson(row.policy_json,{})),payload.failureStrategy??row.failure_strategy,summarize(payload),id,row.lock_version])
  if(!result.affectedRows)throw Object.assign(new Error('规则版本冲突，请刷新后重试'),{status:409});await pool.query("UPDATE scene_versions SET status='草稿',validation_json=NULL,last_trial_id=NULL,dependency_hash='',lock_version=lock_version+1 WHERE id=?",[row.scene_version_id]);await writeSceneAudit(pool,row.scene_version_id,'保存规则草稿',`${row.id} / ${payload.name??row.name}`);return await getRule(pool,id)
}

async function validateRule(pool,id){const [rows]=await pool.query('SELECT * FROM rule_versions WHERE id=?',[id]);if(!rows.length)throw Object.assign(new Error('规则不存在'),{status:404});const result=validateRuleRecord(rows[0]);await writeSceneAudit(pool,rows[0].scene_version_id,'校验规则',`${result.blockers.length}个阻断项，${result.warnings.length}个提示项`);return result}

async function deleteRule(pool,id){
  const [rows]=await pool.query('SELECT rv.*,rr.scene_id FROM rule_versions rv JOIN risk_rules rr ON rr.id=rv.rule_id WHERE rv.id=?',[id]);if(!rows.length)throw Object.assign(new Error('规则不存在'),{status:404});const scene=await getCurrentSceneRow(pool,rows[0].scene_id);if(!scene||!editableSceneStatuses.has(scene.status))throw Object.assign(new Error('当前版本不能删除规则'),{status:409});const connection=await pool.getConnection()
  try{await connection.beginTransaction();await connection.query('DELETE FROM risk_rules WHERE id=?',[rows[0].rule_id]);await connection.query("UPDATE scene_versions SET status='草稿',validation_json=NULL,last_trial_id=NULL,lock_version=lock_version+1 WHERE id=?",[rows[0].scene_version_id]);await writeSceneAudit(connection,rows[0].scene_version_id,'删除草稿规则',rows[0].name);await connection.commit();return{ok:true}}catch(error){await connection.rollback();throw error}finally{connection.release()}
}

async function getTrial(pool,id){
  const [rows]=await pool.query('SELECT * FROM rule_trial_tasks WHERE id=?',[id]);if(!rows.length)return null;const [samples]=await pool.query('SELECT * FROM rule_trial_samples WHERE task_id=? ORDER BY id',[id]);const row=rows[0]
  return{id:row.id,sceneVersionId:row.scene_version_id,ruleVersionId:row.rule_version_id||'',status:row.status,graphVersion:row.graph_version,sampleDays:Number(row.sample_days),organizationScope:row.organization_scope,maxSamples:Number(row.max_samples),timeoutSeconds:Number(row.timeout_seconds),summary:parseJson(row.summary_json,{}),errorMessage:row.error_message,startedAt:row.started_at,finishedAt:row.finished_at,samples:samples.map((item)=>({id:Number(item.id),code:item.sample_code,objectName:item.object_name,outcome:item.outcome,level:item.risk_level,evidenceStatus:item.evidence_status,detail:parseJson(item.detail_json,{})}))}
}

async function createTrial(pool,sceneId,payload){
  const scene=await getCurrentSceneRow(pool,sceneId);if(!scene)throw Object.assign(new Error('场景不存在'),{status:404});if(!['待试跑','待发布'].includes(scene.status))throw Object.assign(new Error('请先保存并通过场景校验'),{status:409});const enabledRules=await getBoundRuleRows(pool,scene.id,true);const rules=payload.ruleVersionId?enabledRules.filter((item)=>item.id===payload.ruleVersionId):enabledRules;if(!rules.length)throw Object.assign(new Error('没有可试跑的启用规则'),{status:409})
  const taskId=makeBusinessId('TRIAL');const cfgHash=configHash(snapshotForHash(scene,enabledRules));const sampleDays=Math.max(1,Math.min(365,Number(payload.sampleDays||90)));const maxSamples=Math.max(10,Math.min(5000,Number(payload.maxSamples||500)));const timeoutSeconds=Math.max(5,Math.min(300,Number(payload.timeoutSeconds||60)))
  await pool.query(`INSERT INTO rule_trial_tasks (id,scene_version_id,rule_version_id,status,graph_version,sample_days,organization_scope,max_samples,timeout_seconds,parameters_json,config_hash,started_at) VALUES (?,?,?,'运行中',?,?,?,?,?,?,?,NOW())`,[taskId,scene.id,payload.ruleVersionId||null,payload.graphVersion||scene.graph_version,sampleDays,payload.organizationScope||'全部适用组织',maxSamples,timeoutSeconds,toJson(payload),cfgHash])
  const names=['华北数字科技有限公司','中科联创服务有限公司','云启信息技术有限公司','电子云产业服务有限公司','华东信创科技有限公司','新域数据服务有限公司'];const hit=Math.min(names.length,Math.max(1,Math.floor(maxSamples/100)));const miss=Math.min(4,Math.max(2,Math.floor(maxSamples/160)))
  for(let i=0;i<hit+miss;i++){const outcome=i<hit?'命中':'未命中';const rule=rules[i%rules.length];await pool.query('INSERT INTO rule_trial_samples (task_id,sample_code,object_name,outcome,risk_level,evidence_status,detail_json) VALUES (?,?,?,?,?,?,?)',[taskId,`SAMPLE-${String(i+1).padStart(4,'0')}`,names[i%names.length],outcome,rule.effective_risk_level||rule.risk_level,'完整',toJson({ruleName:rule.name,relationHops:(parseJson(rule.path_json,{hops:[]}).hops||[]).length,matchedFields:outcome==='命中'?['联系电话','人员ID','关系有效时间']:[],message:outcome==='命中'?'条件表达式成立，证据链完整':'未达到规则阈值'})])}
  const summary={total:hit+miss,hit,miss,error:0,evidenceCompleteness:100,durationMs:680+rules.length*240,passed:hit>0};await pool.query("UPDATE rule_trial_tasks SET status='已完成',summary_json=?,finished_at=NOW() WHERE id=?",[toJson(summary),taskId]);await pool.query("UPDATE scene_versions SET last_trial_id=?,status='待发布',dependency_hash=?,lock_version=lock_version+1 WHERE id=?",[taskId,cfgHash,scene.id]);await writeSceneAudit(pool,scene.id,'发起规则试跑',`${sampleDays}天 / ${summary.total}个样本 / 命中${hit}个`);return await getTrial(pool,taskId)
}

async function publishScene(pool,id,payload){
  const scene=await getCurrentSceneRow(pool,id);if(!scene)throw Object.assign(new Error('场景不存在'),{status:404});if(scene.status!=='待发布')throw Object.assign(new Error('场景必须完成校验和试跑后才能发布'),{status:409});if(!String(payload.reason||'').trim()||!String(payload.versionNote||'').trim())throw Object.assign(new Error('发布原因和版本说明不能为空'),{status:400});const trial=scene.last_trial_id?await getTrial(pool,scene.last_trial_id):null;if(!trial||trial.status!=='已完成'||!trial.summary.passed)throw Object.assign(new Error('最近一次试跑未通过'),{status:409});const rules=await getBoundRuleRows(pool,scene.id,true);if(configHash(snapshotForHash(scene,rules))!==scene.dependency_hash)throw Object.assign(new Error('规则或依赖在试跑后发生变化，请重新校验并试跑'),{status:409})
  const connection=await pool.getConnection();try{await connection.beginTransaction();await connection.query("UPDATE scene_versions SET status='已发布',published_at=NOW(),lock_version=lock_version+1 WHERE id=?",[scene.id]);await connection.query("UPDATE rule_asset_versions SET status='已发布' WHERE id IN (SELECT rule_version_id FROM scene_rule_bindings WHERE scene_version_id=?)",[scene.id]);await connection.query("UPDATE rule_assets SET status='已发布' WHERE current_version_id IN (SELECT rule_version_id FROM scene_rule_bindings WHERE scene_version_id=?)",[scene.id]);const [samples]=await connection.query("SELECT * FROM rule_trial_samples WHERE task_id=? AND outcome='命中' LIMIT 5",[trial.id]);for(let i=0;i<samples.length;i++){const rule=rules[i%rules.length];await connection.query('INSERT INTO rule_run_records (id,scene_version_id,rule_version_id,trial_sample_id,object_code,object_name,outcome,evidence_json,warning_code) VALUES (?,?,?,?,?,?,?,?,?)',[makeBusinessId('RUN'),scene.id,rule.id,samples[i].id,samples[i].sample_code,samples[i].object_name,'命中',toJson(parseJson(samples[i].detail_json,{})),`WARN-DEMO-${String(i+1).padStart(3,'0')}`])}await writeSceneAudit(connection,scene.id,'发布场景版本',`${scene.version}；${payload.versionNote}；原因：${payload.reason}`,'高危');await connection.commit();return await getSceneAggregate(pool,scene.scene_id)}catch(error){await connection.rollback();throw error}finally{connection.release()}
}

async function stopScene(pool,id,payload){const scene=await getCurrentSceneRow(pool,id);if(!scene)throw Object.assign(new Error('场景不存在'),{status:404});if(scene.status!=='已发布')throw Object.assign(new Error('仅已发布版本可以停用'),{status:409});if(!String(payload.reason||'').trim())throw Object.assign(new Error('停用原因不能为空'),{status:400});await pool.query("UPDATE scene_versions SET status='已停用',stop_reason=?,lock_version=lock_version+1 WHERE id=?",[String(payload.reason).trim(),scene.id]);await writeSceneAudit(pool,scene.id,'停用场景版本',payload.reason,'高危');return await getSceneAggregate(pool,scene.scene_id)}

async function references(pool,id){const scene=await getCurrentSceneRow(pool,id);if(!scene)throw Object.assign(new Error('场景不存在'),{status:404});const [runs]=await pool.query('SELECT * FROM rule_run_records WHERE scene_version_id=? ORDER BY executed_at DESC LIMIT 20',[scene.id]);const [audits]=await pool.query('SELECT * FROM scene_rule_audits WHERE scene_version_id=? ORDER BY created_at DESC LIMIT 30',[scene.id]);return{runs:runs.map((item)=>({id:item.id,objectCode:item.object_code,objectName:item.object_name,outcome:item.outcome,warningCode:item.warning_code,executedAt:item.executed_at,evidence:parseJson(item.evidence_json,{})})),audits:audits.map((item)=>({id:Number(item.id),action:item.action,summary:item.summary,operator:item.operator_name,risk:item.risk_level,createdAt:item.created_at}))}}

export async function handleRuleWorkflowApi(req,res,url,{pool,sendJson,readBody}){
  if(url.pathname==='/api/rules'&&req.method==='GET'){sendJson(res,200,await listRules(pool,url));return true}
  const trial=url.pathname.match(/^\/api\/trials\/([^/]+)$/);if(trial&&req.method==='GET'){const result=await getTrial(pool,decodeURIComponent(trial[1]));sendJson(res,result?200:404,result||{message:'试跑任务不存在'});return true}
  const ruleAction=url.pathname.match(/^\/api\/rules\/([^/]+)\/validate$/);if(ruleAction&&req.method==='POST'){sendJson(res,200,await validateRule(pool,decodeURIComponent(ruleAction[1])));return true}
  const rule=url.pathname.match(/^\/api\/rules\/([^/]+)$/);if(rule){const id=decodeURIComponent(rule[1]);if(req.method==='GET'){const result=await getRule(pool,id);sendJson(res,result?200:404,result||{message:'规则不存在'});return true}if(req.method==='PUT'){sendJson(res,200,await updateRule(pool,id,await readBody(req)));return true}if(req.method==='DELETE'){sendJson(res,200,await deleteRule(pool,id));return true}}
  const nested=url.pathname.match(/^\/api\/scenes\/([^/]+)\/rules$/);if(nested&&req.method==='POST'){sendJson(res,201,await createRule(pool,decodeURIComponent(nested[1]),await readBody(req)));return true}
  const action=url.pathname.match(/^\/api\/scenes\/([^/]+)\/(trials|publish|stop|references)$/);if(action){const id=decodeURIComponent(action[1]);if(action[2]==='trials'&&req.method==='POST')sendJson(res,201,await createTrial(pool,id,await readBody(req)));else if(action[2]==='publish'&&req.method==='POST')sendJson(res,200,await publishScene(pool,id,await readBody(req)));else if(action[2]==='stop'&&req.method==='POST')sendJson(res,200,await stopScene(pool,id,await readBody(req)));else if(action[2]==='references'&&req.method==='GET')sendJson(res,200,await references(pool,id));else sendJson(res,405,{message:'请求方法不支持'});return true}
  return false
}
