import { randomUUID } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const seedPath=fileURLToPath(new URL('./data/ruleCatalogSeed.json',import.meta.url))
const json=(value)=>JSON.stringify(value??null)
const marks=(items)=>items.map(()=>'?').join(',')
const importId=()=>('IMP-RULECAT-'+Date.now().toString(36).toUpperCase()+'-'+randomUUID().slice(0,6).toUpperCase())

export async function loadRuleCatalogSeed(path=seedPath){return JSON.parse(await readFile(path,'utf8'))}

export async function initializeRuleCatalogDatabase(pool){
  await pool.query("CREATE TABLE IF NOT EXISTS rule_catalog_import_batches (id VARCHAR(80) PRIMARY KEY,catalog_code VARCHAR(80) NOT NULL,catalog_version VARCHAR(24) NOT NULL,source_file VARCHAR(240) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT '运行中',dry_run TINYINT(1) NOT NULL DEFAULT 0,counts_json JSON NOT NULL,validation_json JSON NOT NULL,error_message TEXT NOT NULL,operator_name VARCHAR(80) NOT NULL DEFAULT '尹晨阳',started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,finished_at DATETIME NULL,KEY idx_rule_catalog_batch (catalog_code,status,started_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
  await pool.query("CREATE TABLE IF NOT EXISTS risk_patterns (id VARCHAR(64) PRIMARY KEY,code VARCHAR(32) NOT NULL UNIQUE,category VARCHAR(120) NOT NULL,name VARCHAR(200) NOT NULL,description TEXT NOT NULL,source_type VARCHAR(32) NOT NULL,is_user_code TINYINT(1) NOT NULL DEFAULT 1,mode_kind VARCHAR(32) NOT NULL DEFAULT '风险模式',stage VARCHAR(32) NOT NULL,risk_level VARCHAR(16) NOT NULL,coverage_status VARCHAR(40) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT '草稿',source_catalog VARCHAR(80) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_pattern_category (category,status),KEY idx_pattern_coverage (coverage_status,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
  await pool.query("CREATE TABLE IF NOT EXISTS scene_pattern_bindings (scene_version_id VARCHAR(80) NOT NULL,pattern_id VARCHAR(64) NOT NULL,priority INT NOT NULL DEFAULT 100,source_catalog VARCHAR(80) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (scene_version_id,pattern_id),KEY idx_scene_pattern_pattern (pattern_id,scene_version_id),CONSTRAINT fk_scene_pattern_scene FOREIGN KEY (scene_version_id) REFERENCES scene_versions(id) ON DELETE CASCADE,CONSTRAINT fk_scene_pattern_pattern FOREIGN KEY (pattern_id) REFERENCES risk_patterns(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
  await pool.query("CREATE TABLE IF NOT EXISTS pattern_rule_bindings (pattern_id VARCHAR(64) NOT NULL,rule_version_id VARCHAR(80) NOT NULL,binding_type VARCHAR(24) NOT NULL DEFAULT '主绑定',source_catalog VARCHAR(80) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (pattern_id,rule_version_id),KEY idx_pattern_rule_rule (rule_version_id,pattern_id),CONSTRAINT fk_pattern_rule_pattern FOREIGN KEY (pattern_id) REFERENCES risk_patterns(id) ON DELETE CASCADE,CONSTRAINT fk_pattern_rule_version FOREIGN KEY (rule_version_id) REFERENCES rule_asset_versions(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
  await pool.query("CREATE TABLE IF NOT EXISTS ai_capabilities (id VARCHAR(64) PRIMARY KEY,code VARCHAR(64) NOT NULL UNIQUE,name VARCHAR(200) NOT NULL,domain VARCHAR(64) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT '草稿',enabled TINYINT(1) NOT NULL DEFAULT 0,config_json JSON NOT NULL,source_catalog VARCHAR(80) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
  await pool.query("CREATE TABLE IF NOT EXISTS pattern_capability_bindings (pattern_id VARCHAR(64) NOT NULL,capability_id VARCHAR(64) NOT NULL,binding_type VARCHAR(24) NOT NULL DEFAULT '主绑定',source_catalog VARCHAR(80) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (pattern_id,capability_id),CONSTRAINT fk_pattern_capability_pattern FOREIGN KEY (pattern_id) REFERENCES risk_patterns(id) ON DELETE CASCADE,CONSTRAINT fk_pattern_capability_asset FOREIGN KEY (capability_id) REFERENCES ai_capabilities(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
  await pool.query("CREATE TABLE IF NOT EXISTS rule_catalog_import_items (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,batch_id VARCHAR(80) NOT NULL,item_type VARCHAR(32) NOT NULL,source_code VARCHAR(80) NOT NULL,target_id VARCHAR(80) NOT NULL,action VARCHAR(24) NOT NULL,status VARCHAR(24) NOT NULL,message VARCHAR(500) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_rule_catalog_item (batch_id,item_type,status),CONSTRAINT fk_rule_catalog_item_batch FOREIGN KEY (batch_id) REFERENCES rule_catalog_import_batches(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
}

function duplicates(values){const seen=new Set();const result=new Set();for(const value of values){if(seen.has(value))result.add(value);else seen.add(value)}return [...result]}

export function validateRuleCatalogSeed(seed){
  const blockers=[];const warnings=[]
  const scenes=Array.isArray(seed?.scenes)?seed.scenes:[]
  const modes=Array.isArray(seed?.modes)?seed.modes:[]
  const rules=Array.isArray(seed?.rules)?seed.rules:[]
  const bindings=Array.isArray(seed?.bindings)?seed.bindings:[]
  const sceneCodes=new Set(scenes.map(item=>item.code));const modeCodes=new Set(modes.map(item=>item.code));const ruleCodes=new Set(rules.map(item=>item.code))
  for(const [label,items] of [['场景',duplicates(scenes.map(item=>item.code))],['模式',duplicates(modes.map(item=>item.code))],['规则',duplicates(rules.map(item=>item.code))]])if(items.length)blockers.push(label+'编号重复：'+items.join('、'))
  for(const mode of modes)if(!sceneCodes.has(mode.primarySceneCode))blockers.push('模式 '+mode.code+' 引用的场景 '+mode.primarySceneCode+' 不存在')
  for(const rule of rules)if(!modeCodes.has(rule.primaryModeCode))blockers.push('规则 '+rule.code+' 的主模式 '+rule.primaryModeCode+' 不存在')
  for(const binding of bindings){if(!modeCodes.has(binding.modeCode))blockers.push('绑定引用的模式 '+binding.modeCode+' 不存在');if(!ruleCodes.has(binding.ruleCode))blockers.push('绑定引用的规则 '+binding.ruleCode+' 不存在')}
  const boundModes=new Set(bindings.map(item=>item.modeCode));for(const mode of modes)if(!boundModes.has(mode.code))blockers.push('模式 '+mode.code+' 未绑定原子规则或智能能力')
  const expected=seed?.metadata?.counts||{};for(const [key,actual] of [['scenes',scenes.length],['modes',modes.length],['rules',rules.length],['bindings',bindings.length]])if(expected[key]!==undefined&&Number(expected[key])!==actual)blockers.push('元数据 '+key+'='+expected[key]+'，实际为'+actual)
  for(const rule of rules){if(!rule.objectCode||!rule.eventCode||!rule.ontologyId||!rule.graphVersion)blockers.push('规则 '+rule.code+' 缺少语义配置');if(rule.enabled!==false)warnings.push('规则 '+rule.code+' 导入时将强制禁用')}
  return {blockers:[...new Set(blockers)],warnings:[...new Set(warnings)],counts:{scenes:scenes.length,modes:modes.length,rules:rules.length,bindings:bindings.length,capabilities:rules.filter(item=>item.ruleType==='智能服务').length,executableRules:rules.filter(item=>item.ruleType!=='智能服务').length}}
}

async function rowsByCode(pool,table,codes){if(!codes.length)return new Map();const [rows]=await pool.query('SELECT * FROM '+table+' WHERE code IN ('+marks(codes)+')',codes);return new Map(rows.map(row=>[row.code,row]))}

export async function previewRuleCatalogImport(pool,seed=null){
  seed=seed||await loadRuleCatalogSeed()
  await initializeRuleCatalogDatabase(pool)
  const structural=validateRuleCatalogSeed(seed);const blockers=[...structural.blockers];const warnings=[...structural.warnings]
  const normal=seed.rules.filter(item=>item.ruleType!=='智能服务');const capabilities=seed.rules.filter(item=>item.ruleType==='智能服务')
  const [scenes,patterns,rules,capabilityRows]=await Promise.all([rowsByCode(pool,'risk_scenes',seed.scenes.map(item=>item.code)),rowsByCode(pool,'risk_patterns',seed.modes.map(item=>item.code)),rowsByCode(pool,'rule_assets',normal.map(item=>item.code)),rowsByCode(pool,'ai_capabilities',capabilities.map(item=>item.code))])
  if(scenes.size){const codes=[...scenes.keys()];const [items]=await pool.query('SELECT rs.code,sv.status FROM risk_scenes rs JOIN scene_versions sv ON sv.id=rs.current_version_id WHERE rs.code IN ('+marks(codes)+')',codes);for(const item of items)if(['已发布','已停用'].includes(item.status))blockers.push('场景 '+item.code+' 当前为'+item.status+'，禁止覆盖')}
  if(rules.size){const codes=[...rules.keys()];const [items]=await pool.query('SELECT ra.code,rav.status FROM rule_assets ra JOIN rule_asset_versions rav ON rav.id=ra.current_version_id WHERE ra.code IN ('+marks(codes)+')',codes);for(const item of items)if(['已发布','已停用'].includes(item.status))blockers.push('规则 '+item.code+' 当前为'+item.status+'，禁止覆盖')}
  const ontologyIds=[...new Set(seed.rules.map(item=>item.ontologyId))];const graphIds=[...new Set(seed.rules.map(item=>item.graphVersion))]
  const [ontologyRows]=await pool.query('SELECT id,status FROM ontologies WHERE id IN ('+marks(ontologyIds)+')',ontologyIds);const [graphRows]=await pool.query('SELECT id,status,ontology_id FROM graph_versions WHERE id IN ('+marks(graphIds)+')',graphIds)
  const ontologyMap=new Map(ontologyRows.map(row=>[row.id,row]));const graphMap=new Map(graphRows.map(row=>[row.id,row]))
  for(const id of ontologyIds){const item=ontologyMap.get(id);if(!item)blockers.push('本体 '+id+' 不存在');else if(item.status!=='已发布')blockers.push('本体 '+id+' 尚未发布')}
  for(const id of graphIds){const item=graphMap.get(id);if(!item)blockers.push('图谱 '+id+' 不存在');else if(item.status!=='已发布')blockers.push('图谱 '+id+' 尚未发布')}
  const pairs=[...new Map(seed.rules.map(rule=>[rule.ontologyId+'|'+rule.objectCode+'|'+rule.eventCode,rule])).values()]
  for(const rule of pairs){const [objects]=await pool.query("SELECT element_id FROM ontology_elements WHERE ontology_id=? AND element_type='class' AND code=? LIMIT 1",[rule.ontologyId,rule.objectCode]);const [events]=await pool.query("SELECT element_id FROM ontology_elements WHERE ontology_id=? AND element_type='event' AND code=? LIMIT 1",[rule.ontologyId,rule.eventCode]);if(!objects.length)blockers.push('规则对象 '+rule.objectCode+' 不存在');if(!events.length)blockers.push('规则事件 '+rule.eventCode+' 不存在')}
  const statusCounts={};for(const rule of seed.rules)statusCounts[rule.buildStatus]=(statusCounts[rule.buildStatus]||0)+1
  return {ok:blockers.length===0,catalog:seed.metadata,counts:structural.counts,statusCounts,existing:{scenes:scenes.size,patterns:patterns.size,rules:rules.size,capabilities:capabilityRows.size},newItems:{scenes:seed.scenes.length-scenes.size,patterns:seed.modes.length-patterns.size,rules:normal.length-rules.size,capabilities:capabilities.length-capabilityRows.size},blockers:[...new Set(blockers)],warnings:[...new Set(warnings)]}
}

const sceneVersionId=(code)=>'SV-'+code+'-V01'
const ruleVersionId=(code)=>'RAV-'+code+'-V01'
async function auditItem(connection,batchId,type,code,target,action,message){await connection.query('INSERT INTO rule_catalog_import_items (batch_id,item_type,source_code,target_id,action,status,message) VALUES (?,?,?,?,?,\'成功\',?)',[batchId,type,code,target,action,message])}

export async function importRuleCatalog(pool,{seed=null,operator='尹晨阳'}={}){
  seed=seed||await loadRuleCatalogSeed()
  const preview=await previewRuleCatalogImport(pool,seed);if(!preview.ok)throw Object.assign(new Error('规则目录存在阻断问题，未执行入库'),{status:409,preview})
  const batchId=importId();const catalog=seed.metadata.catalogCode;const connection=await pool.getConnection()
  try{
    await connection.beginTransaction()
    await connection.query("INSERT INTO rule_catalog_import_batches (id,catalog_code,catalog_version,source_file,status,dry_run,counts_json,validation_json,error_message,operator_name) VALUES (?,?,?,?, '运行中',0,?,?, '',?)",[batchId,catalog,seed.metadata.version,seed.metadata.sourceWorkbook,json(preview.counts),json(preview),operator])
    const sceneMap=new Map()
    for(const scene of seed.scenes){
      const [existing]=await connection.query('SELECT rs.current_version_id FROM risk_scenes rs WHERE rs.code=? LIMIT 1',[scene.code]);const versionId=existing[0]?.current_version_id||sceneVersionId(scene.code)
      if(!existing.length){await connection.query('INSERT INTO risk_scenes (id,code,current_version_id,created_by) VALUES (?,?,?,?)',[scene.code,scene.code,versionId,operator]);await connection.query("INSERT INTO scene_versions (id,scene_id,version,status,name,domain,description,object_code,object_name,event_code,event_name,risk_level,observation_value,observation_unit,ontology_id,graph_version,organization_json,object_scope_json,exception_json,evidence_json,policy_json,check_template_json,updated_by) VALUES (?,?,?,'草稿',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[versionId,scene.code,'v0.1',scene.name,scene.domain,scene.description,scene.objectCode,scene.objectName,scene.eventCode,scene.eventName,scene.level,scene.observationValue,scene.observationUnit,scene.ontologyId,scene.graphVersion,json(['中国电子云集团','集团采购中心','各事业部采购组织']),json({logic:'AND',items:[],stage:scene.stage}),json({validUntil:'2027-12-31',description:'经批准的紧急采购、涉密采购或其他制度例外转人工复核'}),json(['业务来源记录','主体信息','审批记录','规则运行明细']),json([{name:'采购管理制度（演示）',version:'v1.0',clause:'正式发布前确认对应条款'}]),json({materials:['业务单据','审批记录','图谱路径','规则命中明细'],requirements:'核验业务单据、审批顺序、主体关系和资金物流证据，形成可追溯结论。',deadlineHours:scene.level==='重大'?24:48}),operator]);await auditItem(connection,batchId,'场景',scene.code,versionId,'新增','以草稿版本导入')}
      else{await connection.query("UPDATE scene_versions SET name=?,domain=?,description=?,object_code=?,object_name=?,event_code=?,event_name=?,risk_level=?,observation_value=?,observation_unit=?,ontology_id=?,graph_version=?,object_scope_json=?,status='草稿',validation_json=NULL,last_trial_id=NULL,dependency_hash='',updated_by=? WHERE id=?",[scene.name,scene.domain,scene.description,scene.objectCode,scene.objectName,scene.eventCode,scene.eventName,scene.level,scene.observationValue,scene.observationUnit,scene.ontologyId,scene.graphVersion,json({logic:'AND',items:[],stage:scene.stage}),operator,versionId]);await auditItem(connection,batchId,'场景',scene.code,versionId,'更新','更新现有未发布版本')}
      sceneMap.set(scene.code,versionId)
    }
    for(const mode of seed.modes){await connection.query("INSERT INTO risk_patterns (id,code,category,name,description,source_type,is_user_code,mode_kind,stage,risk_level,coverage_status,status,source_catalog) VALUES (?,?,?,?,?,?,?,?,?,?,?,'草稿',?) ON DUPLICATE KEY UPDATE category=VALUES(category),name=VALUES(name),description=VALUES(description),source_type=VALUES(source_type),is_user_code=VALUES(is_user_code),mode_kind=VALUES(mode_kind),stage=VALUES(stage),risk_level=VALUES(risk_level),coverage_status=VALUES(coverage_status),status='草稿',source_catalog=VALUES(source_catalog)",[mode.code,mode.code,mode.category,mode.name,mode.description,mode.source,mode.isUserCode?1:0,mode.modeKind,mode.stage,mode.level==='能力'?'高':mode.level,mode.coverageStatus,catalog]);await connection.query('INSERT INTO scene_pattern_bindings (scene_version_id,pattern_id,priority,source_catalog) VALUES (?,?,100,?) ON DUPLICATE KEY UPDATE priority=VALUES(priority),source_catalog=VALUES(source_catalog)',[sceneMap.get(mode.primarySceneCode),mode.code,catalog]);await auditItem(connection,batchId,'模式',mode.code,mode.code,'写入',mode.primarySceneCode+' / '+mode.coverageStatus)}
    const ruleMap=new Map();const capabilityMap=new Map()
    for(const rule of seed.rules){
      if(rule.ruleType==='智能服务'){await connection.query("INSERT INTO ai_capabilities (id,code,name,domain,status,enabled,config_json,source_catalog) VALUES (?,?,?,?,'草稿',0,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),domain=VALUES(domain),status='草稿',enabled=0,config_json=VALUES(config_json),source_catalog=VALUES(source_catalog)",[rule.code,rule.code,rule.name,rule.domain,json(rule),catalog]);capabilityMap.set(rule.code,rule.code);await auditItem(connection,batchId,'智能能力',rule.code,rule.code,'写入','以禁用草稿导入');continue}
      const [existing]=await connection.query('SELECT ra.id,ra.current_version_id FROM rule_assets ra WHERE ra.code=? LIMIT 1',[rule.code]);const assetId=existing[0]?.id||rule.code;const versionId=existing[0]?.current_version_id||ruleVersionId(rule.code)
      if(!existing.length)await connection.query("INSERT INTO rule_assets (id,code,current_version_id,status,created_by) VALUES (?,?,?,'草稿',?)",[assetId,rule.code,versionId,operator])
      const values=[rule.name,rule.domain,rule.objectCode,rule.objectName,rule.eventCode,rule.eventName,rule.ontologyId,rule.graphVersion,rule.ruleType,rule.level,'草稿',json(rule.conditionJson),json(rule.pathJson),json(rule.timeJson),json(rule.aggregateJson),json(rule.exceptionJson),json(rule.outputJson),json(rule.evidenceJson),json(rule.policyJson),rule.failureStrategy,rule.summary]
      if(!existing.length){await connection.query('INSERT INTO rule_asset_versions (id,rule_id,version,name,domain,object_code,object_name,event_code,event_name,ontology_id,graph_version,rule_type,risk_level,status,condition_json,path_json,time_json,aggregate_json,exception_json,output_json,evidence_json,policy_json,failure_strategy,summary) VALUES (?,?,?,'+values.map(()=>'?').join(',')+')',[versionId,assetId,'v0.1',...values]);await auditItem(connection,batchId,'原子规则',rule.code,versionId,'新增','禁用草稿；现有映射 '+(rule.currentMapping||'无'))}
      else{await connection.query('UPDATE rule_asset_versions SET name=?,domain=?,object_code=?,object_name=?,event_code=?,event_name=?,ontology_id=?,graph_version=?,rule_type=?,risk_level=?,status=?,condition_json=?,path_json=?,time_json=?,aggregate_json=?,exception_json=?,output_json=?,evidence_json=?,policy_json=?,failure_strategy=?,summary=?,lock_version=lock_version+1 WHERE id=?',[...values,versionId]);await connection.query("UPDATE rule_assets SET status='草稿' WHERE id=?",[assetId]);await auditItem(connection,batchId,'原子规则',rule.code,versionId,'更新','更新现有未发布版本')}
      ruleMap.set(rule.code,versionId)
    }
    const modeCodesByRule=new Map()
    for(const binding of seed.bindings){if(!modeCodesByRule.has(binding.ruleCode))modeCodesByRule.set(binding.ruleCode,[]);modeCodesByRule.get(binding.ruleCode).push(binding.modeCode);if(capabilityMap.has(binding.ruleCode))await connection.query('INSERT INTO pattern_capability_bindings (pattern_id,capability_id,binding_type,source_catalog) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE binding_type=VALUES(binding_type),source_catalog=VALUES(source_catalog)',[binding.modeCode,capabilityMap.get(binding.ruleCode),binding.bindingType,catalog]);else await connection.query('INSERT INTO pattern_rule_bindings (pattern_id,rule_version_id,binding_type,source_catalog) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE binding_type=VALUES(binding_type),source_catalog=VALUES(source_catalog)',[binding.modeCode,ruleMap.get(binding.ruleCode),binding.bindingType,catalog])}
    const modes=new Map(seed.modes.map(item=>[item.code,item]));const rules=new Map(seed.rules.map(item=>[item.code,item]))
    for(const [ruleCode,modeCodes] of modeCodesByRule){if(!ruleMap.has(ruleCode))continue;const sceneCodes=[...new Set(modeCodes.map(code=>modes.get(code)?.primarySceneCode).filter(Boolean))];for(const sceneCode of sceneCodes)await connection.query('INSERT INTO scene_rule_bindings (scene_version_id,rule_version_id,enabled,risk_level_override,parameters_json,priority) VALUES (?,?,0,NULL,?,100) ON DUPLICATE KEY UPDATE enabled=0,parameters_json=VALUES(parameters_json)',[sceneMap.get(sceneCode),ruleMap.get(ruleCode),json({importBatchId:batchId,catalogCode:catalog,patternCodes:modeCodes,buildStatus:rules.get(ruleCode)?.buildStatus||'',sourceRuleCode:rules.get(ruleCode)?.currentMapping||''})])}
    const counts={...preview.counts,scenePatternBindings:seed.modes.length,patternAssetBindings:seed.bindings.length,disabledSceneRuleBindings:ruleMap.size}
    await connection.query("UPDATE rule_catalog_import_batches SET status='已完成',counts_json=?,validation_json=?,finished_at=NOW() WHERE id=?",[json(counts),json(preview),batchId]);await connection.commit();return {ok:true,batchId,catalog:seed.metadata,counts,preview}
  }catch(error){await connection.rollback();try{await pool.query("INSERT INTO rule_catalog_import_batches (id,catalog_code,catalog_version,source_file,status,dry_run,counts_json,validation_json,error_message,operator_name,finished_at) VALUES (?,?,?,?,'失败',0,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE status='失败',error_message=VALUES(error_message),finished_at=NOW()",[batchId,seed.metadata.catalogCode,seed.metadata.version,seed.metadata.sourceWorkbook,json(preview.counts),json(preview),String(error?.message||error),operator])}catch{}throw error}finally{connection.release()}
}

export async function getRuleCatalogSummary(pool){
  await initializeRuleCatalogDatabase(pool)
  const [[patterns],[scenePatterns],[patternRules],[capabilities],[capabilityBindings],[batches]]=await Promise.all([pool.query("SELECT COUNT(*) AS total,SUM(is_user_code=1) AS user_total,SUM(mode_kind='智能能力') AS capability_modes FROM risk_patterns"),pool.query('SELECT COUNT(*) AS total FROM scene_pattern_bindings'),pool.query('SELECT COUNT(*) AS total FROM pattern_rule_bindings'),pool.query('SELECT COUNT(*) AS total,SUM(enabled=1) AS enabled_total FROM ai_capabilities'),pool.query('SELECT COUNT(*) AS total FROM pattern_capability_bindings'),pool.query('SELECT id,status,catalog_code,catalog_version,counts_json,validation_json,error_message,started_at,finished_at FROM rule_catalog_import_batches ORDER BY started_at DESC LIMIT 5')])
  return {patterns:patterns[0]||{},scenePatternBindings:Number(scenePatterns[0]?.total||0),patternRuleBindings:Number(patternRules[0]?.total||0),capabilities:capabilities[0]||{},patternCapabilityBindings:Number(capabilityBindings[0]?.total||0),batches}
}

export async function listRiskPatterns(pool,url){
  await initializeRuleCatalogDatabase(pool);const keyword=String(url?.searchParams?.get('keyword')||'').trim();const status=String(url?.searchParams?.get('status')||'').trim();const params=[];const where=[]
  if(keyword){where.push('(p.code LIKE ? OR p.name LIKE ? OR p.category LIKE ?)');params.push('%'+keyword+'%','%'+keyword+'%','%'+keyword+'%')}if(status){where.push('p.coverage_status=?');params.push(status)}
  const [rows]=await pool.query("SELECT p.*,(SELECT COUNT(*) FROM pattern_rule_bindings prb WHERE prb.pattern_id=p.id) AS rule_count,(SELECT COUNT(*) FROM pattern_capability_bindings pcb WHERE pcb.pattern_id=p.id) AS capability_count,(SELECT GROUP_CONCAT(DISTINCT sv.name ORDER BY sv.name SEPARATOR '、') FROM scene_pattern_bindings spb JOIN scene_versions sv ON sv.id=spb.scene_version_id WHERE spb.pattern_id=p.id) AS scene_names FROM risk_patterns p "+(where.length?'WHERE '+where.join(' AND '):'')+' ORDER BY p.category,p.code',params)
  return rows.map(row=>({...row,isUserCode:Boolean(row.is_user_code),ruleCount:Number(row.rule_count),capabilityCount:Number(row.capability_count),sceneNames:String(row.scene_names||'').split('、').filter(Boolean)}))
}

export async function getRiskPattern(pool,code){
  const [patterns]=await pool.query('SELECT * FROM risk_patterns WHERE code=? LIMIT 1',[code]);if(!patterns.length)return null
  const [rules]=await pool.query('SELECT ra.code,rav.id AS version_id,rav.name,rav.rule_type,rav.risk_level,rav.status,prb.binding_type FROM pattern_rule_bindings prb JOIN rule_asset_versions rav ON rav.id=prb.rule_version_id JOIN rule_assets ra ON ra.id=rav.rule_id WHERE prb.pattern_id=? ORDER BY ra.code',[patterns[0].id])
  const [capabilities]=await pool.query('SELECT ac.code,ac.name,ac.status,ac.enabled,pcb.binding_type FROM pattern_capability_bindings pcb JOIN ai_capabilities ac ON ac.id=pcb.capability_id WHERE pcb.pattern_id=? ORDER BY ac.code',[patterns[0].id])
  const [scenes]=await pool.query('SELECT rs.code,sv.id AS version_id,sv.name,sv.status FROM scene_pattern_bindings spb JOIN scene_versions sv ON sv.id=spb.scene_version_id JOIN risk_scenes rs ON rs.id=sv.scene_id WHERE spb.pattern_id=? ORDER BY rs.code',[patterns[0].id])
  return {...patterns[0],isUserCode:Boolean(patterns[0].is_user_code),rules,capabilities:capabilities.map(item=>({...item,enabled:Boolean(item.enabled)})),scenes}
}