import { useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { audits, dataSources, graphVersions, ontologies, roles, scenes, users } from '../data'
import { useAppStore } from '../store'
import type { AuditItem, DataSourceItem, GraphVersion, OntologyItem, RoleItem, SceneItem, UserItem } from '../types'
import { Button, Drawer, Field, FilterGrid, Icon, KeyValue, Modal, PageHeader, Panel, RiskTag, StatusTag, Tabs } from '../ui'

export function SceneListPage() {
  const navigate = useNavigate()
  const setToast = useAppStore((state) => state.setToast)
  const [status, setStatus] = useState('全部')
  const [keyword, setKeyword] = useState('')
  const [modal, setModal] = useState<'new' | 'publish' | 'stop' | null>(null)
  const [target, setTarget] = useState<SceneItem | null>(null)
  const rows = scenes.filter((item) => (!keyword || `${item.name}${item.id}`.includes(keyword)) && (status === '全部' || item.status === status))
  return <>
    <PageHeader eyebrow="能力中心 / 规则管理 / 风险场景" title="风险场景" description="管理目标类、适用范围、等级、制度依据、证据要求和核查模板，发布后形成不可变版本。" actions={<><Button icon="refresh" onClick={() => setToast('场景列表已刷新')}>刷新</Button><Button variant="primary" icon="plus" onClick={() => setModal('new')}>新建场景</Button></>}/>
    <FilterGrid onReset={() => { setKeyword(''); setStatus('全部') }} onSearch={() => setToast(`已查询到 ${rows.length} 个场景`)}>
      <Field label="关键词"><input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="场景名称或编码"/></Field><Field label="监管领域"><select><option>全部授权领域</option><option>采购</option><option>合同</option><option>财务</option><option>投资</option></select></Field><Field label="主对象"><select><option>全部类</option><option>供应商</option><option>合同</option><option>付款单</option></select></Field><Field label="目标类"><select><option>全部目标类</option><option>中标确认</option><option>合同签订</option><option>付款执行</option></select></Field><Field label="默认等级"><select><option>全部等级</option><option>重大</option><option>高</option><option>中</option></select></Field><Field label="状态"><select value={status} onChange={(event) => setStatus(event.target.value)}><option>全部</option><option>草稿</option><option>待试跑</option><option>待发布</option><option>已发布</option><option>已停用</option></select></Field>
    </FilterGrid>
    <Panel title="场景列表" subtitle={`共 ${rows.length} 个场景，已发布版本不可直接编辑`}>
      <div className="table-container"><table><thead><tr><th>场景名称 / 编码</th><th>监管领域</th><th>主对象 / 目标类</th><th>默认等级</th><th>规则数量</th><th>当前版本</th><th>状态</th><th>引用情况</th><th>更新人 / 时间</th><th>操作</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><button className="table-link title-cell" onClick={() => navigate(`/scenes/${item.id}`)}><strong>{item.name}</strong><span>{item.id}</span></button></td><td>{item.domain}</td><td>{item.object}<small className="cell-sub">{item.event}</small></td><td><RiskTag level={item.level}/></td><td><strong>{item.rules}</strong> 条</td><td><button className="version-link" onClick={() => setToast(`${item.name} 版本记录已打开`)}>{item.version}</button></td><td><StatusTag>{item.status}</StatusTag></td><td><span>运行预警 {item.id === 'SCENE-001' ? 42 : 18}</span><small className="cell-sub">图谱依赖 GRAPH-0717.2</small></td><td>{item.updatedBy}<small className="cell-sub">{item.updatedAt}</small></td><td><div className="row-actions vertical"><button onClick={() => navigate(`/scenes/${item.id}`)}>{item.status === '已发布' ? '查看' : '编辑'}</button><button onClick={() => { setTarget(item); setModal(item.status === '已发布' ? 'stop' : 'publish') }}>{item.status === '已发布' ? '停用' : '发布'}</button></div></td></tr>)}</tbody></table></div>
    </Panel>
    <Modal open={modal === 'new'} title="新建风险场景" description="创建后进入场景草稿编辑页。" onClose={() => setModal(null)} onConfirm={() => { setToast('场景草稿已创建'); setModal(null); navigate('/scenes/SCENE-NEW') }}><div className="form-stack"><Field label="场景名称"><input placeholder="请输入业务化场景名称"/></Field><Field label="场景编码"><input placeholder="例如 SCENE-PROC-006"/></Field><Field label="监管领域"><select><option>采购</option><option>合同</option><option>财务</option></select></Field><Field label="场景说明"><textarea placeholder="描述风险、适用边界和不适用情形"/></Field></div></Modal>
    <Modal open={modal === 'publish' || modal === 'stop'} title={modal === 'stop' ? '停用场景版本' : '发布场景版本'} description={target ? `${target.name} ${target.version}` : ''} danger={modal === 'stop'} confirmText={modal === 'stop' ? '确认停用' : '确认发布'} onClose={() => setModal(null)} onConfirm={() => { setToast(modal === 'stop' ? '场景已停用，历史引用保留' : '场景版本已发布'); setModal(null) }}><div className="alert-box"><Icon name="warning"/><span>{modal === 'stop' ? '停用只影响后续运行，历史预警继续引用原版本。' : '系统将重新校验图谱结构、图谱、事件、证据要求和权限依赖。'}</span></div></Modal>
  </>
}

export function SceneEditorPage() {
  const { id = 'SCENE-001' } = useParams()
  const navigate = useNavigate()
  const setToast = useAppStore((state) => state.setToast)
  const scene = scenes.find((item) => item.id === id) || { ...scenes[4], id: 'SCENE-NEW', name: '新建风险场景', version: 'v0.1', status: '草稿' as const }
  const readonly = scene.status === '已发布'
  const [tab, setTab] = useState('basic')
  const [publish, setPublish] = useState(false)
  return <>
    <div className="editor-header"><div><button className="back-button" onClick={() => navigate('/scenes')}>‹ 返回场景列表</button><p className="eyebrow">风险场景 / {scene.id}</p><h1>{scene.name}</h1><div className="editor-meta"><StatusTag>{scene.status}</StatusTag><span>版本 {scene.version}</span><span>{scene.domain}领域</span><span>最近保存：今天 11:26</span></div></div><div className="page-actions">{readonly ? <Button variant="primary" onClick={() => setToast('已复制为新草稿版本')}>复制新版本</Button> : <><Button onClick={() => setToast('草稿已保存')}>保存草稿</Button><Button onClick={() => setToast('校验通过：0个阻断项，2个提示项')}>校验</Button><Button variant="primary" onClick={() => setPublish(true)}>发布</Button></>}</div></div>
    <Panel className="editor-panel"><Tabs value={tab} onChange={setTab} items={[{ key: 'basic', label: '基本信息' }, { key: 'rules', label: '规则配置', count: scene.rules }, { key: 'policies', label: '制度依据', count: 2 }, { key: 'evidence', label: '证据要求', count: 5 }, { key: 'scope', label: '适用范围' }, { key: 'versions', label: '版本记录', count: 4 }]}/>
      {tab === 'basic' && <div className="form-section two-column"><Field label="场景名称"><input defaultValue={scene.name} disabled={readonly}/></Field><Field label="场景编码"><input defaultValue={scene.id} disabled/></Field><Field label="监管领域"><select defaultValue={scene.domain} disabled={readonly}><option>采购</option><option>合同</option><option>财务</option><option>投资</option></select></Field><Field label="默认风险等级"><select defaultValue={scene.level} disabled={readonly}><option>重大</option><option>高</option><option>中</option><option>低</option></select></Field><Field label="主对象"><select defaultValue={scene.object} disabled={readonly}><option>供应商</option><option>合同</option><option>付款单</option><option>投资项目</option></select></Field><Field label="目标类"><select defaultValue={scene.event} disabled={readonly}><option>入围/中标确认</option><option>合同签订</option><option>付款执行</option><option>决策审批</option></select></Field><Field label="观察窗口"><div className="input-group"><input defaultValue="48" disabled={readonly}/><select disabled={readonly}><option>小时</option><option>天</option></select></div></Field><Field label="场景说明" wide><textarea defaultValue="识别供应商、评审人员及关联主体之间可能影响采购公平性的异常关系，适用于入围和中标确认前的事前监管。" disabled={readonly}/></Field></div>}
      {tab === 'rules' && <RuleList scene={scene} readonly={readonly} onEdit={(rule) => navigate(`/rules/${rule}`)}/>} 
      {tab === 'policies' && <div className="policy-editor-list"><Panel title="制度依据" subtitle="第一阶段由人工维护，可配置多条制度、版本和条款"><div className="policy-card"><Icon name="file"/><div><strong>采购评审管理办法 v3.2</strong><span>第十二条 · 评审人员回避要求</span><p>评审人员与投标主体存在利益关联或其他可能影响公正评审的关系时，应主动回避。</p></div></div><div className="policy-card"><Icon name="file"/><div><strong>采购项目评审专家管理细则 v1.6</strong><span>第八条 · 利益冲突申报</span><p>专家与投标主体存在近亲属、任职、投资或其他利益关系时，应进行申报和回避。</p></div></div><Button onClick={() => setToast('制度依据人工配置已打开')} disabled={readonly}>新增制度依据</Button></Panel></div>}
      {tab === 'evidence' && <div className="detail-grid"><Panel title="证据要求" subtitle="第一阶段由人工配置，运行后生成实际证据"><div className="evidence-requirement-list">{['供应商报名记录','工商主体信息','评审专家抽取记录','联系方式来源记录','规则运行明细'].map((item) => <article key={item} className="selected"><label><input type="checkbox" defaultChecked disabled={readonly}/><span><strong>{item}</strong><small>需保存来源系统、来源记录编号和取数批次</small></span></label><div><StatusTag>{item.includes('记录') ? '可预览' : '可追溯'}</StatusTag><button onClick={() => setToast(`${item}证据要求预览已打开`)}>预览</button></div></article>)}</div></Panel><Panel title="证据要求摘要" subtitle="对应统一预警中的实际证据"><p className="drawer-note">证据要求只定义必须固化哪些类型；实际附件和快照在统一预警生成后查看。</p></Panel></div>}
      {tab === 'scope' && <div className="detail-grid"><Panel title="适用组织"><div className="org-tree simple"><label><input type="checkbox" defaultChecked disabled={readonly}/><span>中国电子云</span></label><label className="child"><input type="checkbox" defaultChecked disabled={readonly}/><span>集团采购中心</span></label><label className="child"><input type="checkbox" defaultChecked disabled={readonly}/><span>各事业部采购组织</span></label></div></Panel><Panel title="例外范围"><div className="exception-row"><span>已批准单一来源采购</span><StatusTag>有效</StatusTag><button>查看依据</button></div><div className="exception-row"><span>集团内部关联交易</span><StatusTag>需复核</StatusTag><button>编辑</button></div></Panel></div>}
      {tab === 'versions' && <VersionTimeline labels={['v2.3 当前发布版本','v2.2 规则阈值调整','v2.1 新增工商证据','v1.0 首次发布']}/>} 
    </Panel>
    <Modal open={publish} title="发布风险场景版本" description={`${scene.name} ${scene.version}`} confirmText="确认发布" onClose={() => setPublish(false)} onConfirm={() => { setPublish(false); setToast('场景版本发布成功') }}><PublishChecklist/></Modal>
  </>
}

function RuleList({ scene, readonly, onEdit }: { scene: SceneItem; readonly: boolean; onEdit: (id: string) => void }) {
  const rows = [
    ['RULE-001','供应商与评审人员共同手机号','关系路径','重大','启用'],['RULE-002','供应商与评审人员共同地址','关系路径','高','启用'],['RULE-003','实际控制人存在任职关联','关系路径','重大','启用'],['RULE-004','历史合作频次异常','聚合','中','启用'],['RULE-005','白名单和授权例外','属性','低','启用'],
  ]
  return <div><div className="section-toolbar"><div><strong>{scene.rules} 条关联规则</strong><span>规则只引用图谱结构编码和标准化事实</span></div><Button variant="primary" icon="plus" onClick={() => onEdit('new')} disabled={readonly}>新建规则</Button></div><div className="table-container"><table><thead><tr><th>规则名称 / 编码</th><th>规则类型</th><th>默认等级</th><th>条件摘要</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}><td><strong>{row[1]}</strong><small className="cell-sub">{row[0]}</small></td><td>{row[2]}</td><td><RiskTag level={row[3] as '重大' | '高' | '中' | '低'}/></td><td>关系路径 ≤ 2跳，命中数量 ≥ 1</td><td><StatusTag>{row[4]}</StatusTag></td><td><div className="row-actions"><button onClick={() => onEdit(row[0])}>{readonly ? '查看' : '编辑'}</button><button disabled={readonly}>试跑</button></div></td></tr>)}</tbody></table></div></div>
}

export function RuleEditorPage() {
  const { id = 'RULE-001' } = useParams()
  const navigate = useNavigate()
  const setToast = useAppStore((state) => state.setToast)
  const [logic, setLogic] = useState('AND')
  const [trial, setTrial] = useState(false)
  return <>
    <div className="editor-header"><div><button className="back-button" onClick={() => navigate('/scenes/SCENE-001')}>‹ 返回所属场景</button><p className="eyebrow">规则编辑器 / {id}</p><h1>{id === 'new' ? '新建风险规则' : '供应商与评审人员共同信息'}</h1><div className="editor-meta"><StatusTag>草稿</StatusTag><span>所属场景：供应商异常关联</span><span>图谱结构版本：PROC v2.2</span></div></div><div className="page-actions"><Button onClick={() => setToast('规则草稿已保存')}>保存</Button><Button onClick={() => setToast('规则校验通过')}>校验</Button><Button variant="primary" onClick={() => setTrial(true)}>试跑</Button></div></div>
    <section className="rule-editor-layout">
      <Panel title="结构元素" subtitle="点击元素加入条件" className="ontology-palette"><input className="palette-search" placeholder="搜索对象类、属性、关系或事件类"/><Tabs value="object" onChange={() => undefined} items={[{ key: 'object', label: '对象' }, { key: 'relation', label: '关系' }, { key: 'event', label: '事件类' }]}/><div className="element-tree"><b>采购监管扩展图谱结构</b><details open><summary>供应商</summary><button>主体名称</button><button>统一社会信用代码</button><button>联系电话</button><button>注册地址</button></details><details open><summary>评审人员</summary><button>人员编码</button><button>联系电话</button><button>任职组织</button></details><details><summary>采购项目</summary><button>项目编号</button><button>采购金额</button></details></div></Panel>
      <Panel title="条件组编辑" subtitle="支持AND、OR和嵌套条件组" className="condition-canvas"><div className="logic-toolbar"><div className="segmented"><button className={logic === 'AND' ? 'active' : ''} onClick={() => setLogic('AND')}>AND</button><button className={logic === 'OR' ? 'active' : ''} onClick={() => setLogic('OR')}>OR</button></div><Button icon="plus" onClick={() => setToast('已新增条件组')}>新增条件组</Button></div><div className="condition-group"><header><strong>条件组 1</strong><StatusTag>{logic}</StatusTag></header><ConditionRow object="供应商.联系电话" operator="等于" value="评审人员.联系电话"/><ConditionRow object="共同信息.有效时间" operator="覆盖" value="目标类前180天"/><div className="nested-condition"><div className="condition-connector">OR</div><ConditionRow object="供应商.注册地址" operator="等于" value="评审人员.联系地址"/><ConditionRow object="实际控制人.人员ID" operator="等于" value="评审人员.人员ID"/></div></div><button className="drop-zone" onClick={() => setToast('请选择左侧结构元素')}>＋ 从左侧选择结构元素或新增条件</button></Panel>
      <Panel title="命中输出与证据快照" subtitle="决定预警快照保存内容" className="output-panel"><Field label="规则类型"><select defaultValue="关系路径"><option>属性</option><option>字段比对</option><option>关系路径</option><option>时序</option><option>聚合</option></select></Field><Field label="关系路径"><div className="path-builder"><span>供应商</span><i>登记信息</i><span>联系方式</span><i>共同使用</i><span>评审人员</span></div></Field><Field label="实际命中输出"><div className="check-grid vertical">{['供应商名称与编码','共同手机号脱敏值','评审人员编码','关系有效时间','来源记录与版本'].map((item) => <label key={item}><input type="checkbox" defaultChecked/><span>{item}</span></label>)}</div></Field><Field label="失败策略"><select><option>进入异常队列</option><option>不生成预警</option><option>生成待核查线索</option></select></Field><Panel title="规则摘要" className="mini-summary"><p>当供应商与评审人员在目标类前180天内存在共同联系方式或地址时，生成重大风险预警并固化两跳证据路径。</p></Panel></Panel>
    </section>
    <Drawer open={trial} title="规则试跑结果" eyebrow="样本验证" onClose={() => setTrial(false)} footer={<><Button onClick={() => setTrial(false)}>关闭</Button><Button variant="primary" onClick={() => { setTrial(false); setToast('试跑结果已采纳') }}>采纳结果</Button></>}><section className="trial-summary"><div><span>样本范围</span><strong>近90天 / 2,486个供应商</strong></div><div><span>命中样本</span><strong>12</strong></div><div><span>执行耗时</span><strong>2.3秒</strong></div><div><span>证据完整率</span><strong>91.7%</strong></div></section><div className="alert-box"><Icon name="warning"/><span>1个样本缺少工商来源记录，已按失败策略进入异常队列。</span></div><div className="record-list trial-list">{['华北数字科技有限公司','中科联创服务有限公司','云启信息技术有限公司'].map((item, index) => <article key={item}><header><div><strong>{item}</strong><span>样本 #{index + 1} · 命中路径2跳</span></div><RiskTag level={index === 2 ? '高' : '重大'}/></header><p>共同手机号：138****820{index + 1}；证据状态：{index === 2 ? '部分缺失' : '完整'}</p></article>)}</div></Drawer>
  </>
}

function ConditionRow({ object, operator, value }: { object: string; operator: string; value: string }) {
  return <div className="condition-row"><span>{object}</span><select defaultValue={operator}><option>等于</option><option>不等于</option><option>大于</option><option>覆盖</option></select><input defaultValue={value}/><button><Icon name="close" size={14}/></button></div>
}

export function OntologyListPage() {
  const navigate = useNavigate()
  const setToast = useAppStore((state) => state.setToast)
  const [target, setTarget] = useState<OntologyItem | null>(null)
  return <>
    <PageHeader eyebrow="能力中心 / 知识图谱 / 图谱结构" title="图谱结构" description="维护基础图谱结构和领域图谱结构，统一类、属性和关系定义。" actions={<><Button icon="refresh" onClick={() => setToast('图谱结构列表已刷新')}>刷新</Button><Button variant="primary" icon="plus" onClick={() => navigate('/ontology/ONT-NEW')}>新建图谱结构</Button></>}/>
    <FilterGrid onSearch={() => setToast('图谱结构查询完成')}><Field label="关键词"><input placeholder="图谱结构名称或编码"/></Field><Field label="适用范围"><select><option>全部</option><option>基础图谱结构</option><option>领域图谱结构</option></select></Field><Field label="监管领域"><select><option>全部授权领域</option><option>采购</option><option>合同</option><option>财务</option></select></Field><Field label="状态"><select><option>草稿、待校验、已发布</option><option>已废止</option></select></Field><Field label="当前版本"><input placeholder="版本号"/></Field></FilterGrid>
    <Panel title="图谱结构列表" subtitle="已发布版本只读，变更必须复制新版本"><div className="table-container"><table><thead><tr><th>图谱结构名称 / 编码</th><th>范围 / 领域</th><th>当前版本</th><th>类 / 属性 / 关系</th><th>状态</th><th>引用情况</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{ontologies.map((item) => <tr key={item.id}><td><button className="table-link title-cell" onClick={() => navigate(`/ontology/${item.id}`)}><strong>{item.name}</strong><span>{item.id}</span></button></td><td>{item.scope}<small className="cell-sub">{item.domain}</small></td><td><button className="version-link" onClick={() => setToast('版本记录已打开')}>{item.version}</button></td><td><span className="metrics-inline"><b>{item.classes}</b>类（{Math.max(0, item.classes - item.events)}对象 / {item.events}事件） · <b>{item.properties}</b>属性 · <b>{item.relations}</b>关系</span></td><td><StatusTag>{item.status}</StatusTag></td><td>映射 4 · 场景 6<small className="cell-sub">历史预警 126</small></td><td>{item.updatedAt}</td><td><div className="row-actions vertical"><button onClick={() => navigate(`/ontology/${item.id}`)}>{item.status === '已发布' ? '查看' : '编辑'}</button><button onClick={() => setTarget(item)}>{item.status === '已发布' ? '复制版本' : '发布'}</button></div></td></tr>)}</tbody></table></div></Panel>
    <Modal open={!!target} title={target?.status === '已发布' ? '复制图谱结构新版本' : '发布图谱结构版本'} description={target ? `${target.name} ${target.version}` : ''} onClose={() => setTarget(null)} onConfirm={() => { setToast(target?.status === '已发布' ? '新草稿版本已创建' : '图谱结构版本已发布'); setTarget(null) }}><PublishChecklist/></Modal>
  </>
}

export function OntologyEditorPage() {
  const { id = 'ONT-BASE' } = useParams()
  const navigate = useNavigate()
  const setToast = useAppStore((state) => state.setToast)
  const item = ontologies.find((row) => row.id === id) || { ...ontologies[0], id: 'ONT-NEW', name: '新建领域图谱结构', version: 'v0.1', status: '草稿' as const }
  const readonly = item.status === '已发布'
  const [tab, setTab] = useState('class')
  const [selected, setSelected] = useState('供应商')
  const [drawer, setDrawer] = useState(false)
  return <>
    <div className="editor-header"><div><button className="back-button" onClick={() => navigate('/ontology')}>‹ 返回图谱结构列表</button><p className="eyebrow">图谱结构版本编辑 / {item.id}</p><h1>{item.name}</h1><div className="editor-meta"><StatusTag>{item.status}</StatusTag><span>版本 {item.version}</span><span>{item.scope}</span><span>最近保存：今天 10:18</span></div></div><div className="page-actions">{readonly ? <Button variant="primary" onClick={() => setToast('已复制为新草稿版本')}>复制新版本</Button> : <><Button onClick={() => setToast('图谱结构草稿已保存')}>保存草稿</Button><Button onClick={() => setToast('校验完成：0个阻断项')}>校验</Button><Button variant="primary" onClick={() => setToast('图谱结构版本发布成功')}>发布</Button></>}</div></div>
    <section className="ontology-editor-layout">
      <Panel title="类" subtitle={`${item.classes} 个类`} className="class-tree"><input placeholder="搜索名称或编码"/><div className="tree-list">{['组织','人员','主体','供应商','采购项目','合同','审批记录','资金记录','账户','文档/附件','预警','风险事件'].map((name) => <button key={name} className={selected === name ? 'active' : ''} onClick={() => setSelected(name)}><Icon name={name === '人员' ? 'user' : name === '预警' ? 'warning' : 'graph'} size={15}/><span>{name}</span><small>{name === '供应商' ? 'PROC.Supplier' : `BASE.${name}`}</small></button>)}</div><Button icon="plus" onClick={() => setDrawer(true)} disabled={readonly}>新增类</Button></Panel>
      <Panel className="ontology-element-panel"><div className="selected-class-header"><div><p className="eyebrow">当前类</p><h2>{selected}</h2><span>主识别属性：统一社会信用代码 / 主体编码</span></div><Button icon="edit" onClick={() => setDrawer(true)} disabled={readonly}>编辑类定义</Button></div><Tabs value={tab} onChange={setTab} items={[{ key: 'class', label: '类定义' }, { key: 'property', label: '属性', count: 12 }, { key: 'relation', label: '关系', count: 8 }, { key: 'diff', label: '版本差异' }]}/>{tab === 'class' && <div className="form-section two-column read-view"><KeyValue items={[{ label: '类编码', value: 'PROC.Supplier' }, { label: '中文名称', value: selected }, { label: '别名', value: '供应商、服务商、投标主体' }, { label: '默认显示属性', value: '主体名称' }, { label: '默认敏感等级', value: <StatusTag>内部</StatusTag> }, { label: '主识别属性', value: '统一社会信用代码、供应商编码' }]}/><Panel title="业务说明" className="mini-summary"><p>参与采购、合同或服务活动的法人、非法人组织及其他业务主体。名称相似不得作为自动合并的唯一依据。</p></Panel></div>}{tab === 'property' && <OntologyElementTable type="属性" rows={['supplier_code|供应商编码|文本|主标识','credit_code|统一社会信用代码|文本|主标识','supplier_name|供应商名称|文本|必填','registered_capital|注册资本|金额|普通','contact_phone|联系电话|文本|强敏感']}/>} {tab === 'relation' && <OntologyElementTable type="关系" rows={['participate|参与|供应商 → 采购项目|多对多','sign|签订|供应商 → 合同|一对多','use_account|使用账户|供应商 → 账户|一对多','controlled_by|受控制于|供应商 → 主体|多对多']}/>} {tab === 'diff' && <VersionTimeline labels={['新增：共同联系方式关系','修改：供应商主标识质量要求','修改：联系电话敏感等级','删除：旧版注册状态枚举']}/>}</Panel>
    </section>
    <Drawer open={drawer} title={`${readonly ? '查看' : '编辑'}类：${selected}`} eyebrow="结构元素" onClose={() => setDrawer(false)} footer={<><Button onClick={() => setDrawer(false)}>取消</Button><Button variant="primary" onClick={() => { setDrawer(false); setToast('类定义已保存') }} disabled={readonly}>保存</Button></>}><div className="form-stack"><Field label="类编码"><input defaultValue="PROC.Supplier" disabled/></Field><Field label="中文名称"><input defaultValue={selected} disabled={readonly}/></Field><Field label="别名"><input defaultValue="供应商、服务商、投标主体" disabled={readonly}/></Field><Field label="默认敏感等级"><select defaultValue="内部" disabled={readonly}><option>普通</option><option>内部</option><option>敏感</option><option>强敏感</option></select></Field><Field label="类说明"><textarea defaultValue="参与采购、合同或服务活动的法人、非法人组织及其他业务主体。" disabled={readonly}/></Field></div></Drawer>
  </>
}

function OntologyElementTable({ type, rows }: { type: string; rows: string[] }) {
  return <div><div className="section-toolbar"><div><strong>{rows.length} 个{type}</strong><span>当前图谱结构版本内定义</span></div><Button icon="plus">新增{type}</Button></div><div className="table-container"><table><thead><tr><th>编码</th><th>名称</th><th>类型 / 两端</th><th>约束</th><th>敏感等级</th><th>操作</th></tr></thead><tbody>{rows.map((text) => { const row = text.split('|'); return <tr key={row[0]}><td><code>{row[0]}</code></td><td><strong>{row[1]}</strong></td><td>{row[2]}</td><td>{row[3]}</td><td><StatusTag>{row[0].includes('phone') ? '强敏感' : '内部'}</StatusTag></td><td><div className="row-actions"><button>编辑</button><button>引用</button></div></td></tr> })}</tbody></table></div></div>
}

export function DataAccessPage() {
  const setToast = useAppStore((state) => state.setToast)
  const [tab, setTab] = useState('sources')
  const [selected, setSelected] = useState<DataSourceItem>(dataSources[0])
  const [drawer, setDrawer] = useState(false)
  return <>
    <PageHeader eyebrow="知识图谱 / 数据接入" title="数据接入与字段映射" description="登记来源系统，将来源记录统一映射为节点实例和关系。" actions={<><Button icon="refresh" onClick={() => setToast('同步状态已刷新')}>刷新</Button><Button variant="primary" icon="plus" onClick={() => setDrawer(true)}>新建数据源</Button></>}/>
    <section className="stats-grid four"><article className="mini-stat"><span>启用数据源</span><strong>3</strong><small>1个异常</small></article><article className="mini-stat"><span>今日接收事件</span><strong>12,604</strong><small>重复率0.18%</small></article><article className="mini-stat"><span>有效映射</span><strong>86</strong><small>待校验4项</small></article><article className="mini-stat"><span>最近同步</span><strong>12:08</strong><small>司库付款消息</small></article></section>
    <Panel className="data-access-panel"><Tabs value={tab} onChange={setTab} items={[{ key: 'sources', label: '数据源列表', count: 4 }, { key: 'metadata', label: '元数据' }, { key: 'mapping', label: '节点实例映射' }, { key: 'relation', label: '关系映射' }, { key: 'records', label: '同步记录' }]}/>{tab === 'sources' && <DataSourceList selected={selected.id} onSelect={(item) => { setSelected(item); setTab('metadata') }} onTest={(item) => setToast(`${item.name} 连接测试成功，耗时86ms`)}/>} {tab === 'metadata' && <MetadataView source={selected} onMapping={() => setTab('mapping')}/>} {tab === 'mapping' && <MappingView type="节点实例" source={selected}/>} {tab === 'relation' && <MappingView type="关系" source={selected}/>} {tab === 'records' && <SyncRecords/>}</Panel>
    <Drawer open={drawer} title="新建数据源" eyebrow="数据源向导" onClose={() => setDrawer(false)} footer={<><Button onClick={() => setDrawer(false)}>取消</Button><Button variant="primary" onClick={() => { setDrawer(false); setToast('数据源草稿已创建') }}>保存并继续</Button></>}><div className="step-indicator"><span className="active">1 基本配置</span><span>2 连接测试</span><span>3 元数据解析</span></div><div className="form-stack"><Field label="来源系统名称"><input placeholder="请输入名称"/></Field><Field label="来源系统编码"><input placeholder="客户环境内唯一"/></Field><Field label="来源方式"><select><option>数据库视图</option><option>API</option><option>消息</option><option>批量文件</option></select></Field><Field label="责任人"><select><option>张海（数据管理员）</option><option>陈洁（数据治理专家）</option></select></Field><Field label="数据范围"><textarea placeholder="说明对象、时间和组织范围"/></Field><Field label="敏感等级"><select><option>内部</option><option>敏感</option><option>强敏感</option></select></Field></div></Drawer>
  </>
}

function DataSourceList({ selected, onSelect, onTest }: { selected: string; onSelect: (item: DataSourceItem) => void; onTest: (item: DataSourceItem) => void }) {
  return <><FilterGrid><Field label="关键词"><input placeholder="来源名称或编码"/></Field><Field label="来源方式"><select><option>全部</option><option>数据库视图</option><option>API</option><option>消息</option></select></Field><Field label="状态"><select><option>启用、异常</option><option>草稿</option><option>停用</option></select></Field></FilterGrid><div className="table-container"><table><thead><tr><th>来源名称 / 编码</th><th>来源方式</th><th>数据范围</th><th>责任人</th><th>最近成功时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{dataSources.map((item) => <tr key={item.id} className={selected === item.id ? 'selected-row' : ''}><td><button className="table-link title-cell" onClick={() => onSelect(item)}><strong>{item.name}</strong><span>{item.id}</span></button></td><td>{item.mode}</td><td>{item.range}</td><td>{item.owner}</td><td>{item.lastSuccess}</td><td><StatusTag>{item.status}</StatusTag></td><td><div className="row-actions"><button onClick={() => onSelect(item)}>详情</button><button onClick={() => onTest(item)}>测试</button></div></td></tr>)}</tbody></table></div></>
}

function MetadataView({ source, onMapping }: { source: DataSourceItem; onMapping: () => void }) {
  return <div className="detail-grid"><Panel title="来源基本信息"><KeyValue items={[{ label: '来源名称', value: source.name }, { label: '来源编码', value: source.id }, { label: '来源方式', value: source.mode }, { label: '责任人', value: source.owner }, { label: '最近成功时间', value: source.lastSuccess }, { label: '状态', value: <StatusTag>{source.status}</StatusTag> }]}/><div className="panel-actions bottom"><Button>测试连接</Button><Button variant="primary">重新解析元数据</Button></div></Panel><Panel title="已解析元数据"><div className="metadata-list">{['purchase_project · 采购项目视图 · 32字段','supplier_master · 供应商主数据 · 28字段','purchase_order · 采购订单 · 41字段','bid_event · 招投标事件 · 18字段'].map((item) => <button key={item}>{item}<Icon name="chevron" size={14}/></button>)}</div><Button variant="primary" onClick={onMapping}>进入字段映射</Button></Panel></div>
}

function MappingView({ type, source }: { type: '节点实例' | '关系'; source: DataSourceItem }) {
  const rows = type === '节点实例' ? [['supplier_code','供应商编码','PROC.Supplier.supplier_code','直接映射','已校验'],['supplier_name','供应商名称','PROC.Supplier.supplier_name','去空格','已校验'],['credit_code','统一社会信用代码','PROC.Supplier.credit_code','大写转换','已校验'],['contact_phone','联系电话','PROC.Supplier.contact_phone','号码标准化','待校验'],['record_id + occurred_at','中标确认记录','PROC.BidConfirmed','节点识别','已校验']] : [['supplier_id + project_id','参与投标','Supplier → PurchaseProject','关联键映射','已校验'],['supplier_id + account_no','使用账户','Supplier → Account','哈希关联','待校验']]
  return <><div className="mapping-header"><div><span>当前来源</span><strong>{source.name}</strong><small>{source.id}</small></div><div className="mapping-progress"><span>{type}映射完整度</span><strong>{type === '节点实例' ? '92%' : '78%'}</strong><i><em style={{ width: type === '节点实例' ? '92%' : '78%' }}/></i></div><Button variant="primary">提交校验</Button></div><div className="mapping-canvas"><aside><h3>来源字段 / 关联键</h3>{rows.map((row) => <button key={row[0]}>{row[0]}<small>varchar(64)</small></button>)}</aside><main><h3>转换与识别规则</h3>{rows.map((row) => <div key={row[0]}><span>{row[3]}</span><Icon name="chevron"/></div>)}</main><aside><h3>{type === '节点实例' ? '目标类 / 属性' : '目标图谱关系'}</h3>{rows.map((row) => <button key={row[0]}>{row[2]}<small>核验状态：{row[4]}</small></button>)}</aside></div></>
}

function SyncRecords() {
  return <div className="table-container"><table><thead><tr><th>批次号</th><th>数据源</th><th>方式</th><th>开始时间</th><th>处理数量</th><th>异常数量</th><th>耗时</th><th>结果</th></tr></thead><tbody>{[['SYNC-0717-006','司库付款消息','事件','今天 12:08','326','0','3秒','成功'],['SYNC-0717-005','OA审批事件接口','事件','今天 12:06','1,824','3','18秒','部分成功'],['SYNC-0717-004','集团ERP采购视图','增量','今天 11:52','6,428','0','2分16秒','成功']].map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={cell}>{index === 7 ? <StatusTag>{cell}</StatusTag> : cell}</td>)}</tr>)}</tbody></table></div>
}

export function GraphManagementPage() {
  const setToast = useAppStore((state) => state.setToast)
  const [tab, setTab] = useState('versions')
  const [target, setTarget] = useState<GraphVersion | null>(null)
  const [govern, setGovern] = useState(false)
  return <>
    <PageHeader eyebrow="知识图谱" title="知识图谱" description="维护图谱结构和数据源，生成并发布知识图谱。" actions={<Button variant="primary" icon="plus" onClick={() => setTarget(graphVersions[1])}>生成知识图谱</Button>}/>
    <section className="graph-overview"><div><span>当前知识图谱</span><strong>GRAPH-20260717.2</strong><small>发布于今天 08:45</small></div><div><span>节点 / 关系</span><strong>176,752 / 309,861</strong><small>覆盖4个数据源</small></div><div><span>生成状态</span><strong className="success-text">已发布</strong><small>后台快照留痕</small></div><div><span>数据源</span><strong>4</strong><small>启用中</small></div></section>
    <Panel><Tabs value={tab} onChange={setTab} items={[{ key: 'versions', label: '生成结果', count: 3 }, { key: 'governance', label: '实例处理', count: 18 }, { key: 'quality', label: '生成检查', count: 34 }, { key: 'publish', label: '发布快照', count: 12 }]}/>{tab === 'versions' && <GraphVersionTable onPublish={setTarget}/>} {tab === 'governance' && <GovernanceView onOpen={() => setGovern(true)}/>} {tab === 'quality' && <QualityView/>} {tab === 'publish' && <VersionTimeline labels={['GRAPH-20260717.2 · 陈洁 · 发布成功','GRAPH-20260716.3 · 陈洁 · 数据源补偿后重建','GRAPH-20260715.5 · 张海 · 发布成功','GRAPH-20260714.1 · 王宁 · 校验失败']}/>}</Panel>
    <Modal open={!!target} title="发布知识图谱" description={target ? `${target.id} · ${target.ontologyVersion}` : ''} onClose={() => setTarget(null)} onConfirm={() => { setTarget(null); setToast('知识图谱发布任务已提交') }}><PublishChecklist/></Modal>
    <Drawer open={govern} title="候选实例对比" eyebrow="实例处理 / GOV-0018" onClose={() => setGovern(false)} footer={<><Button onClick={() => setGovern(false)}>保持独立</Button><Button variant="danger" onClick={() => { setGovern(false); setToast('实例合并已确认并记录审计') }}>确认合并</Button></>}><div className="entity-compare"><article><StatusTag>来源A</StatusTag><h3>华北数字科技有限公司</h3><KeyValue items={[{ label: '统一社会信用代码', value: '91110108MA01****' }, { label: '供应商编码', value: 'SUP-002186' }, { label: '联系电话', value: '138****8201' }, { label: '来源', value: '集团ERP采购视图' }]}/></article><div className="compare-score"><strong>96%</strong><span>建议合并</span><small>强标识一致</small></div><article><StatusTag>来源B</StatusTag><h3>华北数字科技（北京）有限公司</h3><KeyValue items={[{ label: '统一社会信用代码', value: '91110108MA01****' }, { label: '主体编码', value: 'EXT-77120' }, { label: '联系电话', value: '138****8201' }, { label: '来源', value: '工商司法外部数据' }]}/></article></div><div className="alert-box danger"><Icon name="warning"/><span>实例合并属于高危操作，将影响后续知识图谱。历史快照和预警快照不受影响。</span></div></Drawer>
  </>
}

function GraphVersionTable({ onPublish }: { onPublish: (item: GraphVersion) => void }) {
  return <div className="table-container"><table><thead><tr><th>知识图谱</th><th>图谱结构 / 映射快照</th><th>数据范围</th><th>节点 / 关系</th><th>生成检查</th><th>状态</th><th>发布时间</th><th>操作</th></tr></thead><tbody>{graphVersions.map((item) => <tr key={item.id}><td><button className="table-link"><strong>{item.id}</strong></button></td><td>{item.ontologyVersion}<small className="cell-sub">{item.mappingVersion}</small></td><td>{item.range}</td><td>{(item.entities + item.events).toLocaleString()}<small className="cell-sub">{item.relations.toLocaleString()} 关系</small></td><td><span className={item.blockers ? 'danger-text' : 'success-text'}>{item.blockers} 阻断</span><small className="cell-sub">{item.warnings} 警告</small></td><td><StatusTag>{item.status}</StatusTag></td><td>{item.publishedAt}</td><td><div className="row-actions"><button>查看</button>{item.status === '待发布' && <button onClick={() => onPublish(item)}>发布</button>}<button>检查</button></div></td></tr>)}</tbody></table></div>
}

function GovernanceView({ onOpen }: { onOpen: () => void }) {
  const rows = [['GOV-0018','供应商','华北数字科技有限公司 / 华北数字科技（北京）有限公司','统一社会信用代码一致','确认合并','高'],['GOV-0017','人员','王宁 / 王 宁','员工编码一致，姓名格式不同','自动合并','中'],['GOV-0016','账户','账户尾号6208 / 账户尾号6208','开户名不一致','待确认','重大']]
  return <div className="table-container"><table><thead><tr><th>治理任务</th><th>对象类型</th><th>候选实体</th><th>识别依据</th><th>建议结果</th><th>风险等级</th><th>操作</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><StatusTag>{row[4]}</StatusTag></td><td><RiskTag level={row[5] as '重大' | '高' | '中'}/></td><td><div className="row-actions"><button onClick={onOpen}>对比</button><button>保持独立</button></div></td></tr>)}</tbody></table></div>
}

function QualityView() {
  return <div className="quality-grid">{[['主标识缺失','阻断','供应商记录缺少统一社会信用代码','集团ERP采购视图 · 2条'],['来源结构变化','警告','OA审批接口新增 approver_org 字段','OA审批事件接口 · 1项'],['事件时间延迟','警告','付款执行事件平均延迟65秒','司库付款消息 · 12项'],['关系有效期缺失','提示','历史任职关系缺少valid_to','人力主数据 · 19项']].map((item) => <article key={item[0]}><StatusTag>{item[1]}</StatusTag><h3>{item[0]}</h3><p>{item[2]}</p><span>{item[3]}</span><Button>定位问题</Button></article>)}</div>
}

export function UsersPage() {
  const setToast = useAppStore((state) => state.setToast)
  const [org, setOrg] = useState('中国电子云')
  const [selected, setSelected] = useState<UserItem | null>(null)
  const rows = users.filter((item) => org === '中国电子云' || item.organization === org)
  return <>
    <PageHeader eyebrow="系统管理 / 用户与组织" title="用户与组织" description="同步或维护组织、用户、岗位和账号状态，停用前完成未办任务转派。" actions={<><Button onClick={() => setToast('组织用户同步任务已创建')}>同步组织用户</Button><Button variant="primary" icon="plus" onClick={() => setToast('新建用户抽屉已打开')}>新建用户</Button></>}/>
    <section className="users-layout"><Panel title="组织树" className="organization-panel"><input placeholder="搜索组织"/><div className="org-tree">{['中国电子云','集团监管部','采购管理部','财务共享中心','数据管理部','审计纪检部'].map((name, index) => <button key={name} className={`${org === name ? 'active' : ''} ${index ? 'child' : ''}`} onClick={() => setOrg(name)}><Icon name={index ? 'graph' : 'home'} size={15}/><span>{name}</span><small>{index ? users.filter((u) => u.organization === name).length : users.length}</small></button>)}</div></Panel><Panel title={org} subtitle={`${rows.length} 名用户`} className="user-list-panel"><FilterGrid><Field label="关键词"><input placeholder="姓名、账号或人员编码"/></Field><Field label="岗位"><select><option>全部岗位</option></select></Field><Field label="角色"><select><option>全部角色</option></select></Field><Field label="账号状态"><select><option>启用</option><option>锁定</option><option>停用</option></select></Field></FilterGrid><div className="table-container"><table><thead><tr><th>姓名 / 账号</th><th>所属组织 / 岗位</th><th>当前角色</th><th>状态</th><th>未完成待办</th><th>最后登录</th><th>操作</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><button className="table-link title-cell" onClick={() => setSelected(item)}><strong>{item.name}</strong><span>{item.account} · {item.id}</span></button></td><td>{item.organization}<small className="cell-sub">{item.position}</small></td><td>{item.roles.map((role) => <StatusTag key={role}>{role}</StatusTag>)}</td><td><StatusTag>{item.status}</StatusTag></td><td><button className={item.todos ? 'count-link' : ''}>{item.todos}</button></td><td>{item.lastLogin}</td><td><div className="row-actions"><button onClick={() => setSelected(item)}>查看</button><button onClick={() => setToast(`${item.name} 待办转派向导已打开`)}>转派</button></div></td></tr>)}</tbody></table></div></Panel></section>
    <Drawer open={!!selected} title={selected?.name || ''} eyebrow="用户详情" onClose={() => setSelected(null)} footer={<><Button onClick={() => setSelected(null)}>关闭</Button><Button variant="primary" onClick={() => setToast('用户信息已保存')}>保存</Button></>}><KeyValue items={[{ label: '账号', value: selected?.account }, { label: '人员编码', value: selected?.id }, { label: '所属组织', value: selected?.organization }, { label: '岗位', value: selected?.position }, { label: '账号状态', value: <StatusTag>{selected?.status}</StatusTag> }, { label: '未完成待办', value: `${selected?.todos} 项` }, { label: '最后登录', value: selected?.lastLogin }]}/><Panel title="角色分配" className="drawer-section"><div className="check-grid vertical">{['监管负责人','领域监管专员','业务责任人','图谱结构员','数据管理员'].map((role) => <label key={role}><input type="checkbox" defaultChecked={selected?.roles.includes(role)}/><span>{role}</span></label>)}</div></Panel>{selected && selected.todos > 0 && <div className="alert-box danger"><Icon name="warning"/><span>该用户存在{selected.todos}项未完成待办，停用账号前必须完成转派。</span></div>}</Drawer>
  </>
}

export function RolesPage() {
  const setToast = useAppStore((state) => state.setToast)
  const [selected, setSelected] = useState<RoleItem>(roles[0])
  const [tab, setTab] = useState('menu')
  const [confirm, setConfirm] = useState(false)
  return <>
    <PageHeader eyebrow="系统管理 / 角色与权限" title="角色与权限" description="配置菜单、按钮、组织、字段、关系、证据和高危操作权限，权限变更即时生效。" actions={<Button variant="primary" icon="plus" onClick={() => setToast('角色草稿已创建')}>新建角色</Button>}/>
    <section className="role-layout"><Panel title="角色列表" className="role-list"><input placeholder="搜索角色名称或编码"/>{roles.map((item) => <button key={item.id} className={selected.id === item.id ? 'active' : ''} onClick={() => setSelected(item)}><div><strong>{item.name}</strong><span>{item.id} · {item.type}</span></div><small>{item.users}人</small><StatusTag>{item.status}</StatusTag></button>)}</Panel><Panel className="permission-panel"><div className="selected-role-header"><div><p className="eyebrow">当前角色</p><h2>{selected.name}</h2><span>{selected.id} · {selected.type}角色 · {selected.users}名用户</span></div><div><Button onClick={() => setToast('权限变更差异已打开')}>查看变更</Button><Button variant="primary" onClick={() => setConfirm(true)}>保存权限</Button></div></div><Tabs value={tab} onChange={setTab} items={[{ key: 'menu', label: '菜单与按钮' }, { key: 'org', label: '组织数据' }, { key: 'field', label: '字段属性' }, { key: 'relation', label: '关系权限' }, { key: 'evidence', label: '证据权限' }, { key: 'danger', label: '高危操作' }]}/><PermissionContent tab={tab} role={selected}/></Panel></section>
    <Modal open={confirm} title="保存角色权限" description={`${selected.name} · 权限调整将立即影响 ${selected.users} 名用户`} confirmText="确认保存" danger onClose={() => setConfirm(false)} onConfirm={() => { setConfirm(false); setToast('角色权限已保存并即时生效') }}><div className="alert-box danger"><Icon name="warning"/><span>服务端将重新计算菜单、按钮、字段、关系和证据权限，当前在线用户可能需要刷新页面。</span></div></Modal>
  </>
}

function PermissionContent({ tab, role }: { tab: string; role: RoleItem }) {
  if (tab === 'menu') return <div className="permission-tree">{['监管工作台','监管态势','风险监管 / 统一预警','风险监管 / 风险事件','能力中心 / 模型管理','能力中心 / 规则管理','能力中心 / 知识图谱','系统管理'].map((item, index) => <div key={item}><label><input type="checkbox" defaultChecked={index < 4}/><span>{item}</span></label><div className="permission-buttons"><label><input type="checkbox" defaultChecked={index < 4}/>查看</label><label><input type="checkbox" defaultChecked={index === 2}/>派发</label><label><input type="checkbox" defaultChecked={index === 2}/>复核</label></div></div>)}</div>
  if (tab === 'org') return <div className="detail-grid"><Panel title="数据范围"><div className="radio-list"><label><input type="radio" name="scope" defaultChecked/>当前组织</label><label><input type="radio" name="scope"/>当前组织及授权下级</label><label><input type="radio" name="scope"/>自定义组织节点</label></div></Panel><Panel title="授权摘要"><KeyValue items={[{ label: '当前范围', value: role.scope }, { label: '组织节点', value: '12个' }, { label: '监管领域', value: '采购、合同、财务' }]}/></Panel></div>
  if (tab === 'field') return <div className="table-container"><table><thead><tr><th>类 / 字段</th><th>敏感等级</th><th>明文</th><th>脱敏</th><th>隐藏</th></tr></thead><tbody>{[['人员','证件号码','强敏感'],['账户','银行账号','强敏感'],['合同','合同金额','敏感'],['供应商','联系电话','敏感'],['资金记录','付款金额','敏感']].map((row, index) => <tr key={row[1]}><td><strong>{row[0]}</strong><small className="cell-sub">{row[1]}</small></td><td><StatusTag>{row[2]}</StatusTag></td><td><input type="radio" name={`f${index}`} defaultChecked={index > 2}/></td><td><input type="radio" name={`f${index}`} defaultChecked={index <= 2}/></td><td><input type="radio" name={`f${index}`}/></td></tr>)}</tbody></table></div>
  if (tab === 'relation') return <div className="check-grid permission-cards">{['组织隶属','人员任职','主体控制','参与采购','签订合同','支付收款','账户归属','证据来源'].map((item, index) => <label key={item}><input type="checkbox" defaultChecked={index < 6}/><Icon name="graph"/><span>{item}</span></label>)}</div>
  if (tab === 'evidence') return <div className="permission-matrix"><div><span>证据类型</span><b>摘要</b><b>详情</b><b>预览</b><b>下载</b></div>{['业务来源记录','审批记录','合同单据','资金记录','附件','外部数据','制度条款'].map((item) => <div key={item}><strong>{item}</strong><input type="checkbox" defaultChecked/><input type="checkbox" defaultChecked/><input type="checkbox" defaultChecked={item !== '资金记录'}/><input type="checkbox" defaultChecked={item === '附件'}/></div>)}</div>
  return <div className="danger-permissions">{['发布图谱结构','发布规则与场景','发布知识图谱','实例合并与拆分','解除重大高风险预警','升级风险事件','复核关闭风险事件','调整角色权限'].map((item, index) => <label key={item}><div><Icon name="lock"/><span>{item}</span></div><input type="checkbox" defaultChecked={index >= 4 && index <= 6}/></label>)}</div>
}

export function AuditPage() {
  const setToast = useAppStore((state) => state.setToast)
  const [selected, setSelected] = useState<AuditItem | null>(null)
  const [risk, setRisk] = useState('全部')
  const rows = audits.filter((item) => risk === '全部' || item.risk === risk)
  return <>
    <PageHeader eyebrow="系统管理 / 审计日志" title="审计日志" description="查询高危操作、敏感数据访问和业务处置链路；记录只读、不可删除和物理覆盖。" actions={<><span className="updated-time">最近索引 12:08:36</span><Button icon="refresh" onClick={() => setToast('审计索引已刷新')}>刷新</Button></>}/>
    <FilterGrid onReset={() => setRisk('全部')} onSearch={() => setToast(`已查询到 ${rows.length} 条审计记录`)}><Field label="操作时间"><input type="date" defaultValue="2026-07-10"/></Field><Field label="操作人"><input placeholder="姓名或账号"/></Field><Field label="操作类型"><select><option>全部操作</option><option>发布</option><option>处置</option><option>权限调整</option><option>敏感查看</option></select></Field><Field label="对象类型"><select><option>全部对象</option><option>预警</option><option>风险事件</option><option>知识图谱</option><option>角色</option><option>证据</option></select></Field><Field label="操作结果"><select><option>全部结果</option><option>成功</option><option>失败</option><option>部分成功</option></select></Field><Field label="风险级别"><select value={risk} onChange={(event) => setRisk(event.target.value)}><option>全部</option><option>普通</option><option>高危</option><option>敏感访问</option></select></Field><Field label="trace_id"><input placeholder="精确匹配"/></Field></FilterGrid>
    <Panel title="审计记录" subtitle={`当前条件共 ${rows.length} 条，默认按操作时间倒序`}><div className="table-container"><table><thead><tr><th>操作时间</th><th>操作人 / 组织</th><th>操作类型</th><th>对象类型 / 编号</th><th>操作摘要</th><th>结果</th><th>风险级别</th><th>trace_id</th><th>操作</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td>{item.time}</td><td>{item.operator}<small className="cell-sub">{item.organization}</small></td><td>{item.action}</td><td>{item.objectType}<small className="cell-sub">{item.objectId}</small></td><td>{item.summary}</td><td><StatusTag>{item.result}</StatusTag></td><td><StatusTag>{item.risk}</StatusTag></td><td><button className="trace-link" onClick={() => setSelected(item)}>{item.traceId}</button></td><td><button className="table-action" onClick={() => setSelected(item)}>详情</button></td></tr>)}</tbody></table></div></Panel>
    <Drawer open={!!selected} title={selected?.traceId || ''} eyebrow="审计日志详情" onClose={() => setSelected(null)} footer={<Button onClick={() => { navigator.clipboard?.writeText(selected?.traceId || ''); setToast('trace_id 已复制') }}>复制 trace_id</Button>}><KeyValue items={[{ label: '操作时间', value: selected?.time }, { label: '操作人', value: `${selected?.operator} / ${selected?.organization}` }, { label: '操作类型', value: selected?.action }, { label: '对象', value: `${selected?.objectType} / ${selected?.objectId}` }, { label: '操作结果', value: <StatusTag>{selected?.result}</StatusTag> }, { label: '风险级别', value: <StatusTag>{selected?.risk}</StatusTag> }, { label: 'IP地址', value: '10.20.18.***' }]}/><Panel title="操作原因" className="drawer-section"><p className="drawer-note">{selected?.summary}</p></Panel><Panel title="前后值" className="drawer-section"><div className="diff-view"><div><span>操作前</span><code>status: "待复核"</code></div><div><span>操作后</span><code>status: "已关闭"</code></div></div></Panel><Panel title="链路信息" className="drawer-section"><div className="trace-chain"><span>网关接入</span><i/><span>权限校验</span><i/><span>业务服务</span><i/><span>审计落库</span></div></Panel></Drawer>
  </>
}

function VersionTimeline({ labels }: { labels: string[] }) {
  return <div className="version-timeline">{labels.map((label, index) => <article key={label}><i/><div><strong>{label}</strong><span>{index === 0 ? '今天 10:20 · 当前版本' : `2026-07-${16 - index} · 版本变更记录`}</span></div><button>查看差异</button></article>)}</div>
}

function PublishChecklist() {
  return <div className="publish-checklist">{['基本信息与编码校验','图谱结构和图谱依赖有效','事件与证据要求配置完整','权限范围校验通过','试跑或质量校验通过'].map((item) => <div key={item}><span><Icon name="check"/></span><strong>{item}</strong><StatusTag>通过</StatusTag></div>)}<div className="alert-box"><Icon name="lock"/><span>发布后版本不可修改，历史业务对象继续引用发布时版本。</span></div></div>
}

