import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { sceneRuleApi } from '../sceneRuleApi'
import { ruleClosureApi } from '../ruleClosureApi'

import type { ConditionGroup, OntologyElement, RuleCondition, RuleItem, SceneItem, SceneReferences, TrialTask, ValidationIssue } from '../sceneRuleTypes'
import { isConditionGroup } from '../sceneRuleTypes'
import { dataGraphApi } from '../dataGraphApi'
import type { RiskLevel } from '../types'
import { useAppStore } from '../store'
import { Button, Drawer, EmptyState, Field, FilterGrid, Icon, Modal, PageHeader, Panel, RiskTag, StatusTag, Tabs } from '../ui'

const domains=['采购','合同','财务','投资']
const levels:RiskLevel[]=['重大','高','中','低']
const statuses=['全部','草稿','待试跑','待发布','已发布','已停用']
const organizations=['中国电子云集团','集团采购中心','财务共享中心','各事业部采购组织','试点事业部']
const evidenceOptions=['业务来源记录','主体信息','审批记录','联系方式来源','附件材料','规则运行明细']
const evidenceRequirementMeta:Record<string,{source:string;attachment:string;check:string;actual:string}>={
  '业务来源记录':{source:'ERP/采购系统业务单据',attachment:'可选附件',check:'必须能追溯到业务单据编号、来源系统和抽取批次',actual:'运行后形成供应商报名记录、采购项目记录等实际证据'},
  '主体信息':{source:'图谱主数据、工商司法外部数据',attachment:'可选附件',check:'必须包含主体编码、统一社会信用代码或外部主体标识',actual:'运行后形成主体登记快照、股权信息或关联主体清单'},
  '审批记录':{source:'OA/ERP审批流',attachment:'需支持附件',check:'必须包含审批节点、审批人、审批时间和审批结论',actual:'运行后形成审批流快照，可预览原始审批附件'},
  '联系方式来源':{source:'供应商登记、人员主数据、外部补充数据',attachment:'可选附件',check:'必须包含手机号/地址等字段来源、采集时间和脱敏策略',actual:'运行后形成联系方式命中明细和字段来源记录'},
  '附件材料':{source:'业务系统附件、外部文件归档',attachment:'必须有附件',check:'必须保存文件名、哈希、版本和权限级别',actual:'运行后可预览或下载有权限的附件快照'},
  '规则运行明细':{source:'规则运行服务',attachment:'无需附件',check:'必须记录规则版本、命中条件、命中值和执行时间',actual:'运行后形成规则命中明细，支撑复核和审计'}
}
const outputOptions=['主体名称与编码','命中字段和值','关系路径','事件时间','聚合结果','来源记录与版本']
const ruleTypes:RuleItem['type'][]=['属性','字段比对','关系路径','时序','聚合']
const fallbackElements:OntologyElement[]=[
  {id:'p1',type:'property',code:'PROC.Supplier.phone',name:'供应商联系电话',dataType:'文本',constraint:'',description:'供应商登记联系方式'},
  {id:'p2',type:'property',code:'PROC.Reviewer.phone',name:'评审人员联系电话',dataType:'文本',constraint:'',description:'评审人员登记联系方式'},
  {id:'p3',type:'property',code:'PROC.Contract.change_rate',name:'合同金额变更比例',dataType:'数字',constraint:'',description:'合同金额变化比例'},
  {id:'p4',type:'property',code:'PROC.Contact.valid_time',name:'关系有效时间',dataType:'日期时间',constraint:'',description:'关系有效时间'},
  {id:'r1',type:'relation',code:'PROC.shared_contact',name:'共同使用',dataType:'联系方式 → 评审人员',constraint:'',description:'共同使用联系方式'},
  {id:'e1',type:'class',code:'PROC.BidConfirmed',name:'中标确认',dataType:'类',constraint:'发生时间必填',description:'用于表达中标确认业务记录的普通类'},
]
type OntologyOption={id:string;name:string;status?:string;elements:OntologyElement[]}
type GraphOption={id:string;status:string;ontologyId:string}
type SceneCreateDraft={code:string;name:string;version:string;domain:string;level:RiskLevel;description:string}

const dateText=(value:unknown)=>value?new Date(String(value)).toLocaleString('zh-CN',{hour12:false}):'—'
const messageOf=(error:unknown)=>error instanceof Error?error.message:'操作失败，请稍后重试'

export function SceneListPage(){
  const navigate=useNavigate();const setToast=useAppStore((state)=>state.setToast)
  const [rows,setRows]=useState<SceneItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  const [filters,setFilters]=useState({keyword:'',status:'全部',domain:'全部'});const [draftFilters,setDraftFilters]=useState(filters)

  const [stopTarget,setStopTarget]=useState<SceneItem|null>(null);const [deleteTarget,setDeleteTarget]=useState<SceneItem|null>(null);const [stopReason,setStopReason]=useState('');const [referenceTarget,setReferenceTarget]=useState<SceneItem|null>(null);const [references,setReferences]=useState<SceneReferences|null>(null)

  const load=async(next=filters)=>{setLoading(true);setError('');try{setRows(await sceneRuleApi.listScenes(next))}catch(err){setError(messageOf(err))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])

  const copy=async(scene:SceneItem)=>{if(!window.confirm(`确认从 ${scene.version} 复制新草稿版本？`))return;try{const next=await sceneRuleApi.copyScene(scene.id);setToast(`已创建${next.version}草稿`);navigate(`/scenes/${next.id}`)}catch(err){setToast(messageOf(err))}}
  const stop=async()=>{if(!stopTarget)return;try{await sceneRuleApi.stopScene(stopTarget.id,stopReason);setStopTarget(null);setStopReason('');setToast('场景版本已停用');await load()}catch(err){setToast(messageOf(err))}}
  const remove=async()=>{if(!deleteTarget)return;try{const result=await sceneRuleApi.deleteScene(deleteTarget.id);setDeleteTarget(null);setToast(result.message);await load()}catch(err){setToast(messageOf(err))}}
  const openReferences=async(scene:SceneItem)=>{setReferenceTarget(scene);setReferences(null);try{setReferences(await sceneRuleApi.references(scene.id))}catch(err){setToast(messageOf(err))}}

  return <>
    <PageHeader eyebrow="能力中心 / 规则管理 / 风险场景" title="风险场景" description="场景用于定义风险主题，并统一组织标准规则。" actions={<><Button icon="refresh" onClick={()=>void load()}>刷新</Button><Button variant="primary" icon="plus" onClick={()=>navigate('/scenes/new')}>新建场景</Button></>}/>
    <FilterGrid onReset={()=>{const next={keyword:'',status:'全部',domain:'全部'};setDraftFilters(next);setFilters(next);void load(next)}} onSearch={()=>{setFilters(draftFilters);void load(draftFilters)}}>
      <Field label="关键词"><input value={draftFilters.keyword} onChange={(event)=>setDraftFilters({...draftFilters,keyword:event.target.value})} placeholder="场景名称或编码"/></Field>
      <Field label="监管领域"><select value={draftFilters.domain} onChange={(event)=>setDraftFilters({...draftFilters,domain:event.target.value})}><option>全部</option>{domains.map((item)=><option key={item}>{item}</option>)}</select></Field>
      <Field label="状态"><select value={draftFilters.status} onChange={(event)=>setDraftFilters({...draftFilters,status:event.target.value})}>{statuses.map((item)=><option key={item}>{item}</option>)}</select></Field>
    </FilterGrid>
    <Panel title="场景版本列表" subtitle="已发布版本不可直接编辑，变更必须复制新版本">
      {loading?<div className="loading-state"><i/><span>正在加载场景数据…</span></div>:error?<div className="error-state"><Icon name="warning"/><div><strong>场景加载失败</strong><span>{error}</span></div><Button onClick={()=>void load()}>重试</Button></div>:rows.length===0?<EmptyState title="没有符合条件的场景" description="调整查询条件，或新建一个风险场景。"/>:<div className="table-container"><table><thead><tr><th>场景名称 / 编码</th><th>监管领域</th><th>默认等级</th><th>检测能力</th><th>版本</th><th>状态</th><th>命中记录</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{rows.map((item)=><tr key={item.id}><td><button className="table-link title-cell" onClick={()=>navigate(`/scenes/${item.id}`)}><strong>{item.name}</strong><span>{item.code}</span></button></td><td>{item.domain}</td><td><RiskTag level={item.level}/></td><td><strong>{item.enabledRuleCount}</strong> 条启用规则<small className="cell-sub">共 {item.ruleCount} 条规则</small></td><td><button className="version-link" onClick={()=>navigate(`/scenes/${item.id}?tab=versions`)}>{item.version}</button></td><td><StatusTag>{item.status}</StatusTag></td><td><button className="reference-link" onClick={()=>void openReferences(item)}>命中记录 {item.runCount}<small>{item.ruleCount} 条规则</small></button></td><td>{item.updatedBy}<small className="cell-sub">{dateText(item.updatedAt)}</small></td><td><div className="row-actions vertical"><button onClick={()=>navigate(`/scenes/${item.id}`)}>{['已发布','已停用'].includes(item.status)?'查看':'编辑'}</button>{['已发布','已停用'].includes(item.status)&&<button onClick={()=>void copy(item)}>复制版本</button>}{item.status==='已发布'&&<button onClick={()=>setStopTarget(item)}>停用</button>}{item.status==='待发布'&&<button onClick={()=>navigate(`/scenes/${item.id}`)}>发布</button>}{item.canDelete&&<button className="danger-link" onClick={()=>setDeleteTarget(item)}>删除</button>}</div></td></tr>)}</tbody></table></div>}
    </Panel>

    <Modal open={!!stopTarget} title="停用场景版本" description={stopTarget?`${stopTarget.name} ${stopTarget.version}`:''} confirmText="确认停用" danger onClose={()=>setStopTarget(null)} onConfirm={()=>void stop()}><div className="form-stack"><div className="alert-box danger"><Icon name="warning"/><span>停用只影响后续运行，历史预警和命中记录继续引用原版本。</span></div><Field label="停用原因 *"><textarea value={stopReason} onChange={(event)=>setStopReason(event.target.value)}/></Field></div></Modal>
    <Modal open={!!deleteTarget} title="删除场景草稿" description={deleteTarget?`${deleteTarget.name} · ${deleteTarget.code}`:''} confirmText="确认删除" danger onClose={()=>setDeleteTarget(null)} onConfirm={()=>void remove()}><div className="alert-box danger"><Icon name="warning"/><span>仅可删除未发布且没有命中记录的当前版本；如已有历史版本，删除后将回退到上一版本。</span></div></Modal>
    <Drawer open={!!referenceTarget} title={referenceTarget?`${referenceTarget.name} · 命中记录与审计`:'命中记录与审计'} eyebrow="预警闭环" onClose={()=>setReferenceTarget(null)}>{!references?<div className="loading-state"><i/><span>正在加载命中记录…</span></div>:<div className="drawer-sections"><Panel title={`命中记录 ${references.runs.length}`}>{references.runs.length?references.runs.map((item)=><article className="audit-card" key={item.id}><div><strong>{item.objectName}</strong><span>{item.objectCode} · {item.warningCode||'未生成预警'}</span></div><small>{dateText(item.executedAt)}</small></article>):<EmptyState title="暂无命中记录" description="发布场景并形成命中后将在这里展示固化记录。"/>}</Panel><Panel title="操作审计">{references.audits.map((item)=><article className="audit-card" key={item.id}><div><strong>{item.action}</strong><span>{item.summary}</span></div><StatusTag>{item.risk}</StatusTag><small>{item.operator} · {dateText(item.createdAt)}</small></article>)}</Panel></div>}</Drawer>
  </>
}


export function SceneCreatePage(){
  const navigate=useNavigate();const setToast=useAppStore((state)=>state.setToast)
  const [draft,setDraft]=useState<SceneCreateDraft>({code:'',name:'',version:'V1',domain:'采购',level:'高',description:''})
  const [dirty,setDirty]=useState(false);const [saving,setSaving]=useState(false)
  const patch=(next:Partial<SceneCreateDraft>)=>{setDraft((value)=>({...value,...next}));setDirty(true)}
  useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty&&!saving){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty,saving])
  const basicDone=Boolean(draft.name.trim()&&draft.version.trim()&&draft.domain&&draft.level&&draft.description.trim())
  const createDraft=async(nextStep=false)=>{
    if(saving)return
    if(!draft.name.trim()){setToast('场景名称不能为空');return}
    if(!draft.version.trim()){setToast('场景版本号不能为空');return}
    if(!draft.description.trim()){setToast('请填写场景说明');return}
    setSaving(true)
    try{
      const scene=await sceneRuleApi.createScene({name:draft.name.trim(),code:draft.code.trim(),version:draft.version.trim(),domain:draft.domain,level:draft.level,description:draft.description.trim()})
      setDirty(false);setToast('场景草稿已创建')
      navigate(`/scenes/${encodeURIComponent(scene.id)}${nextStep?'?tab=rules':''}`,{replace:true})
    }catch(err){setToast(messageOf(err));setSaving(false)}
  }
  const cancel=()=>{if(dirty&&!window.confirm('当前新建内容尚未保存，确认放弃并返回？'))return;navigate('/scenes')}
  const stepCards=[
    {key:'basic',label:'基本信息',description:'名称、版本、领域与说明',done:basicDone},
    {key:'rules',label:'风险规则',description:'创建草稿后继续配置',done:false},
    {key:'scope',label:'适用范围',description:'创建草稿后继续配置',done:false},
  ]
  return <>
    <div className="simple-rule-header"><div><button className="back-button" onClick={cancel}>‹ 返回风险场景</button><p className="eyebrow">风险场景 / 新建场景</p><h1>{draft.name.trim()||'新增风险场景'}</h1><div className="editor-meta"><StatusTag>未创建</StatusTag><span>版本 {draft.version.trim()||'V1'}</span><span>{dirty?'存在未保存修改':'填写基本信息后创建草稿'}</span></div></div></div>
    <nav className="rule-editor-tabs" aria-label="场景创建步骤">{stepCards.map((step,index)=><button type="button" className={[step.key==='basic'?'active':'',step.done?'done':''].filter(Boolean).join(' ')} onClick={()=>step.key==='basic'?undefined:setToast('请先完成基本信息并点击下一步创建场景草稿')} key={step.key}><i>{step.done?'✓':index+1}</i><span><strong>{step.label}</strong><small>{step.description}</small></span></button>)}</nav>
    <main className="rule-step-content">
      <Panel title="1. 基本信息" subtitle="先定义风险主题；版本号可手工调整，发布后锁定">
        <div className="form-section two-column">
          <Field label="场景名称 *"><input value={draft.name} onChange={(event)=>patch({name:event.target.value})} placeholder="例如：供应商与评审人员利益关联"/></Field>
          <Field label="场景编码"><input value={draft.code} onChange={(event)=>patch({code:event.target.value.toUpperCase()})} placeholder="留空自动生成"/></Field>
          <Field label="场景版本号 *"><input value={draft.version} onChange={(event)=>patch({version:event.target.value.toUpperCase()})} placeholder="例如：V1"/></Field>
          <Field label="监管领域 *"><select value={draft.domain} onChange={(event)=>patch({domain:event.target.value})}>{domains.map((item)=><option key={item}>{item}</option>)}</select></Field>
          <Field label="默认风险等级 *"><select value={draft.level} onChange={(event)=>patch({level:event.target.value as RiskLevel})}>{levels.map((item)=><option key={item}>{item}</option>)}</select></Field>
          <Field label="场景说明 *" wide><textarea value={draft.description} onChange={(event)=>patch({description:event.target.value})} placeholder="说明这是什么风险、适用边界和不适用情形"/></Field>
        </div>
        <div className="next-action-card"><Icon name={basicDone?'check':'clock'}/><div><strong>{basicDone?'基本信息已完整':'请先补齐基本信息'}</strong><span>{basicDone?'点击下一步后创建场景草稿，并进入风险规则配置。':'至少填写场景名称、版本号、监管领域、默认风险等级和场景说明。'}</span></div></div>
      </Panel>
    </main>
    <footer className="editor-action-bar"><div><span className={dirty?'dirty-dot':''}/><strong>{dirty?'新建内容尚未保存':'尚未创建场景草稿'}</strong><small>版本号发布前可调整，发布后锁定</small></div><div><Button onClick={cancel}>取消</Button><Button disabled={saving} onClick={()=>void createDraft(false)}>{saving?'正在创建…':'保存草稿'}</Button><Button variant="primary" disabled={saving} onClick={()=>void createDraft(true)}>{saving?'正在创建…':'下一步'}</Button></div></footer>
  </>
}

export function RuleListPage(){
  const navigate=useNavigate();const [keyword,setKeyword]=useState('');const [rows,setRows]=useState<RuleItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  const load=async()=>{setLoading(true);setError('');try{setRows(await sceneRuleApi.listRules(keyword))}catch(err){setError(messageOf(err))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  return <><PageHeader eyebrow="能力中心 / 规则管理" title="规则管理" description="查看当前场景版本关联的确定性规则，编辑入口始终回到所属场景版本。" actions={<Button icon="refresh" onClick={()=>void load()}>刷新</Button>}/><FilterGrid onReset={()=>{setKeyword('');void sceneRuleApi.listRules().then(setRows)}} onSearch={()=>void load()}><Field label="关键词"><input value={keyword} onChange={(event)=>setKeyword(event.target.value)} placeholder="规则名称、编码或所属场景"/></Field></FilterGrid><Panel title="规则列表" subtitle="规则版本跟随场景版本发布并保持不可变">{loading?<div className="loading-state"><i/><span>正在加载规则…</span></div>:error?<div className="error-state"><Icon name="warning"/><span>{error}</span></div>:<div className="table-container"><table><thead><tr><th>规则名称 / 编码</th><th>所属场景</th><th>等级</th><th>条件摘要</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{rows.map((item)=><tr key={item.versionId}><td><strong>{item.name}</strong><small className="cell-sub">{item.code}</small></td><td><button className="table-link" onClick={()=>navigate(`/scenes/${item.sceneId}`)}>{item.sceneName}</button></td><td><RiskTag level={item.level}/></td><td className="summary-cell">{item.summary}</td><td><StatusTag>{item.status}</StatusTag></td><td>{dateText(item.updatedAt)}</td><td><button className="table-action" onClick={()=>navigate(`/rules/${item.versionId}`)}>{['已发布','已停用'].includes(item.sceneStatus||'')?'查看':'编辑'}</button></td></tr>)}</tbody></table></div>}</Panel></>
}

export function SceneEditorPage(){
  const {id=''}=useParams();const navigate=useNavigate();const setToast=useAppStore((state)=>state.setToast)
  const [scene,setScene]=useState<SceneItem|null>(null);const [draft,setDraft]=useState<SceneItem|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [dirty,setDirty]=useState(false);const initialTab=new URLSearchParams(window.location.hash.split('?')[1]||'').get('tab')||'basic';const [tab,setTab]=useState(['skills','template'].includes(initialTab)?'rules':initialTab)
  const [issuesOpen,setIssuesOpen]=useState(false);const [trialOpen,setTrialOpen]=useState(false);const [trial,setTrial]=useState<TrialTask|null>(null);const [trialParams,setTrialParams]=useState({sampleDays:90,maxSamples:500,timeoutSeconds:60,organizationScope:'全部适用组织'})
  const [publishOpen,setPublishOpen]=useState(false);const [publishInfo,setPublishInfo]=useState({versionNote:'',reason:''})
  const [ruleLibraryOpen,setRuleLibraryOpen]=useState(false);const [ruleLibrary,setRuleLibrary]=useState<RuleItem[]>([]);const [selectedRules,setSelectedRules]=useState<string[]>([]);const [ruleLibraryLoading,setRuleLibraryLoading]=useState(false)

  const readonly=!!scene&&['已发布','已停用'].includes(scene.status)
  const load=async()=>{setLoading(true);setError('');try{const data=await sceneRuleApi.getScene(id);setScene(data);setDraft(structuredClone(data));setDirty(false);if(data.lastTrialId&&data.status==='待发布')setTrial(await sceneRuleApi.getTrial(data.lastTrialId))}catch(err){setError(messageOf(err))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[id]);useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty])
  const patchDraft=(patch:Partial<SceneItem>)=>{if(!draft)return;setDraft({...draft,...patch});setDirty(true)}
  const save=async(silent=false)=>{if(!draft||!scene)return null;if(!dirty)return scene;try{const saved=await sceneRuleApi.updateScene(scene.id,{version:draft.version,name:draft.name,domain:draft.domain,description:draft.description,level:draft.level,organizations:draft.organizations,objectScope:draft.objectScope,exceptions:draft.exceptions,lockVersion:scene.lockVersion});setScene(saved);setDraft(structuredClone(saved));setDirty(false);if(!silent)setToast('场景草稿已保存');return saved}catch(err){setToast(messageOf(err));return null}}
  const validate=async()=>{const saved=await save(true);if(!saved)return;try{const result=await sceneRuleApi.validateScene(saved.id);setScene(result.scene);setDraft(structuredClone(result.scene));setDirty(false);setIssuesOpen(true);setToast(result.validation.blockers.length?'校验发现阻断问题':'校验通过，场景已进入待试跑')}catch(err){setToast(messageOf(err))}}
  const runTrial=async()=>{if(!scene)return;try{const result=await sceneRuleApi.createTrial(scene.id,trialParams);setTrial(result);setTrialOpen(false);const refreshed=await sceneRuleApi.getScene(scene.id);setScene(refreshed);setDraft(structuredClone(refreshed));setToast('试跑完成，场景已进入待发布')}catch(err){setToast(messageOf(err))}}
  const publish=async()=>{if(!scene)return;try{const result=await sceneRuleApi.publishScene(scene.id,publishInfo);setScene(result);setDraft(structuredClone(result));setPublishOpen(false);setToast('场景版本已发布并生成运行快照')}catch(err){setToast(messageOf(err))}}
  const copy=async()=>{if(!scene)return;try{const next=await sceneRuleApi.copyScene(scene.id);setToast(`已复制为${next.version}草稿`);navigate(`/scenes/${next.id}`)}catch(err){setToast(messageOf(err))}}
  const openRuleLibrary=async()=>{if(!scene)return;setRuleLibraryOpen(true);setSelectedRules([]);setRuleLibraryLoading(true);try{setRuleLibrary(await ruleClosureApi.listLibrary(scene.id))}catch(err){setToast(messageOf(err));setRuleLibrary([])}finally{setRuleLibraryLoading(false)}}
  const confirmRules=async()=>{if(!scene||!selectedRules.length){setToast('请至少选择一条规则');return}try{await ruleClosureApi.selectRules(scene.id,selectedRules);setRuleLibraryOpen(false);setToast(`已引用${selectedRules.length}条标准规则`);await load()}catch(err){setToast(messageOf(err))}}
  const createRule=()=>{if(scene)navigate(`/rules/new?sceneId=${encodeURIComponent(scene.id)}`)}

  const removeRule=async(rule:RuleItem)=>{if(!scene||!window.confirm(`确认将“${rule.name}”从当前场景移除？规则库中的规则不会被删除。`))return;try{await sceneRuleApi.unbindRule(scene.id,rule.versionId);setToast('已从当前场景移除规则，规则资产仍保留在规则管理中');await load()}catch(err){setToast(messageOf(err))}}


  const back=()=>{if(dirty&&!window.confirm('当前存在未保存修改，确认离开？'))return;navigate('/scenes')}
  const locateIssue=(issue:ValidationIssue)=>{setTab(issue.ruleId||['conditions','output','basic','rules'].includes(issue.tab)?'rules':issue.tab);setIssuesOpen(false)}

  if(loading)return <div className="loading-state page-loading"><i/><span>正在加载场景版本…</span></div>
  if(error||!draft||!scene)return <div className="error-state page-error"><Icon name="warning"/><div><strong>场景加载失败</strong><span>{error||'场景不存在'}</span></div><Button onClick={()=>navigate('/scenes')}>返回列表</Button></div>
  const toggleList=(value:string)=>{const list=draft.organizations;patchDraft({organizations:list.includes(value)?list.filter((item)=>item!==value):[...list,value]})}
  return <>
    <div className="scene-editor-head"><div><button className="back-button" onClick={back}>‹ 返回场景列表</button><p className="eyebrow">风险场景 / {scene.code}</p><h1>{draft.name}</h1><div className="editor-meta"><StatusTag>{scene.status}</StatusTag><span>版本 {draft.version}</span><span>{draft.domain}领域</span><span>{dirty?'存在未保存修改':`最近保存：${dateText(scene.updatedAt)}`}</span></div></div><div className="page-actions">{readonly?<Button variant="primary" onClick={()=>void copy()}>复制新版本</Button>:<><Button onClick={()=>void save()}>保存草稿</Button><Button onClick={()=>void validate()}>校验</Button>{scene.status==='待试跑'&&<Button variant="primary" onClick={()=>setTrialOpen(true)}>发起试跑</Button>}{scene.status==='待发布'&&<Button variant="primary" onClick={()=>setPublishOpen(true)}>发布版本</Button>}</>}</div></div>
    <div className="workflow-steps">{['草稿','待试跑','待发布','已发布'].map((item,index)=>{const currentIndex=['草稿','待试跑','待发布','已发布'].indexOf(scene.status==='已停用'?'已发布':scene.status);return <div key={item} className={`${index<currentIndex?'done':''} ${index===currentIndex?'active':''}`}><i>{index<currentIndex?'✓':index+1}</i><span>{item}</span></div>})}</div>
    <Panel className="scene-editor-panel"><Tabs value={tab} onChange={setTab} items={[{key:'basic',label:'基本信息'},{key:'rules',label:'风险规则',count:scene.ruleCount},{key:'scope',label:'适用范围'},{key:'versions',label:'版本记录',count:scene.versions.length}]}/>
      <div className="scene-tab-content">
        {tab==='basic'&&<div className="form-section two-column"><Field label="场景名称 *"><input value={draft.name} disabled={readonly} onChange={(event)=>patchDraft({name:event.target.value})}/></Field><Field label="场景编码"><input value={scene.code} disabled/></Field><Field label="场景版本号 *"><input value={draft.version} disabled={readonly} onChange={(event)=>patchDraft({version:event.target.value.toUpperCase()})} placeholder="例如：V1"/></Field><Field label="监管领域 *"><select value={draft.domain} disabled={readonly} onChange={(event)=>patchDraft({domain:event.target.value})}>{domains.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="默认风险等级 *"><select value={draft.level} disabled={readonly} onChange={(event)=>patchDraft({level:event.target.value as RiskLevel})}>{levels.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="场景说明 *" wide><textarea value={draft.description} disabled={readonly} onChange={(event)=>patchDraft({description:event.target.value})} placeholder="说明这是什么风险、适用边界和不适用情形"/></Field></div>}
        {tab==='rules'&&<div><div className="section-toolbar"><div><strong>{scene.enabledRuleCount} 条启用规则 / 共 {scene.ruleCount} 条</strong><span>当前页只维护场景下的规则引用关系；不直接删除规则资产。</span></div><div className="page-actions"><Button icon="link" disabled={readonly} onClick={()=>void openRuleLibrary()}>选择已有规则</Button><Button variant="primary" icon="plus" disabled={readonly} onClick={createRule}>新建规则</Button></div></div>{scene.rules.length?<div className="table-container"><table><thead><tr><th>规则名称 / 编码</th><th>适用图谱</th><th>命中等级</th><th>依据与证据</th><th>状态</th><th>操作</th></tr></thead><tbody>{scene.rules.map((rule)=><tr key={rule.versionId}><td><strong>{rule.name}</strong><small className="cell-sub">{rule.code} · {rule.version}</small></td><td>{rule.graphVersion||'未配置适用图谱'}<small className="cell-sub">图谱结构：{rule.ontologyId||'由适用图谱带出'}{rule.eventName?` · ${rule.eventName}`:''}</small></td><td>{rule.levelMode==='inherit'?<span>继承场景<small className="cell-sub">当前为 {scene.level}</small></span>:<RiskTag level={rule.level}/>}</td><td><strong>{rule.policies?.length||0} 条制度依据</strong><small className="cell-sub">{rule.evidenceRequirements?.length||rule.evidence.length} 项证据要求</small></td><td><StatusTag>{rule.enabled?'启用':'停用'}</StatusTag></td><td><div className="row-actions"><button onClick={()=>navigate(`/rules/${rule.versionId}?sceneId=${encodeURIComponent(scene.id)}`)}>{readonly?'查看':'编辑'}</button>{!readonly&&<button onClick={()=>void removeRule(rule)}>移除规则</button>}</div></td></tr>)}</tbody></table></div>:<EmptyState title="尚未关联风险规则" description="可以选择已有规则，或新建一条完整规则后自动关联当前场景。"/>}</div>}

        {tab==='scope'&&<div className="detail-grid"><Panel title="适用组织"><div className="check-grid vertical">{organizations.map((item)=><label key={item}><input type="checkbox" checked={draft.organizations.includes(item)} disabled={readonly} onChange={()=>toggleList(item)}/><span>{item}</span></label>)}</div></Panel><Panel title="例外范围"><div className="form-stack"><Field label="例外说明"><textarea value={draft.exceptions.description} disabled={readonly} onChange={(event)=>patchDraft({exceptions:{...draft.exceptions,description:event.target.value}})}/></Field><Field label="有效期"><input type="date" value={draft.exceptions.validUntil} disabled={readonly} onChange={(event)=>patchDraft({exceptions:{...draft.exceptions,validUntil:event.target.value}})}/></Field></div></Panel></div>}
        {tab==='versions'&&<div className="version-records">{scene.versions.map((item)=><article key={item.id} className={item.id===scene.versionId?'current':''}><i/><div><strong>{item.version} · {item.status}</strong><span>{item.sourceVersionId?`继承自 ${item.sourceVersionId}`:'初始版本'}</span><small>{item.updatedBy} · {dateText(item.updatedAt)}</small></div>{item.id===scene.versionId&&<StatusTag>当前版本</StatusTag>}</article>)}</div>}
      </div>
    </Panel>
    {!readonly&&<footer className="editor-action-bar"><div><span className={dirty?'dirty-dot':''}/><strong>{dirty?'修改尚未保存':'所有修改已保存'}</strong><small>{scene.validation.validatedAt?`最近校验：${dateText(scene.validation.validatedAt)}`:'尚未完成校验'}</small></div><div><Button onClick={back}>返回</Button><Button onClick={()=>void save()}>保存草稿</Button><Button onClick={()=>void validate()}>校验</Button>{scene.status==='待试跑'&&<Button variant="primary" onClick={()=>setTrialOpen(true)}>试跑</Button>}{scene.status==='待发布'&&<Button variant="primary" onClick={()=>setPublishOpen(true)}>发布</Button>}</div></footer>}
    <Drawer open={issuesOpen} title="场景校验结果" eyebrow="场景与检测能力检查" onClose={()=>setIssuesOpen(false)}><ValidationView blockers={scene.validation.blockers} warnings={scene.validation.warnings} onLocate={locateIssue}/></Drawer>
    <Modal open={ruleLibraryOpen} title="选择已有标准规则" description="建立规则版本引用，不复制规则内容；同一规则可以被多个风险场景复用。" confirmText={`引用到场景${selectedRules.length?`（${selectedRules.length}）`:''}`} onClose={()=>setRuleLibraryOpen(false)} onConfirm={()=>void confirmRules()}>{ruleLibraryLoading?<div className="loading-state"><i/><span>正在加载规则库…</span></div>:ruleLibrary.length===0?<EmptyState title="暂无可选择规则" description="请先在规则管理中新建规则，或当前规则均已被引用。"/>:<div className="rule-library-list">{ruleLibrary.map((rule)=><label key={rule.versionId} className={selectedRules.includes(rule.versionId)?'selected':''}><input type="checkbox" checked={selectedRules.includes(rule.versionId)} onChange={()=>setSelectedRules((items)=>items.includes(rule.versionId)?items.filter((item)=>item!==rule.versionId):[...items,rule.versionId])}/><div><strong>{rule.name}</strong><span>{rule.code} · {rule.domain||'通用'}</span><small>{rule.summary}；当前被 {rule.bindingCount||0} 个场景版本引用</small></div><RiskTag level={rule.level}/></label>)}</div>}</Modal>

    <Modal open={trialOpen} title="发起场景试跑" description={`${scene.name} ${scene.version}`} confirmText="开始试跑" onClose={()=>setTrialOpen(false)} onConfirm={()=>void runTrial()}><div className="form-stack"><div className="inherit-note"><Icon name="check"/><span>标准规则按检测口径和表达式执行，系统会固化命中证据。</span></div><div className="form-section two-column"><Field label="样本时间范围"><select value={trialParams.sampleDays} onChange={(event)=>setTrialParams({...trialParams,sampleDays:Number(event.target.value)})}><option value={30}>近30天</option><option value={90}>近90天</option><option value={180}>近180天</option></select></Field><Field label="最大样本数"><input type="number" value={trialParams.maxSamples} onChange={(event)=>setTrialParams({...trialParams,maxSamples:Number(event.target.value)})}/></Field><Field label="超时时间（秒）"><input type="number" value={trialParams.timeoutSeconds} onChange={(event)=>setTrialParams({...trialParams,timeoutSeconds:Number(event.target.value)})}/></Field><Field label="组织范围"><select value={trialParams.organizationScope} onChange={(event)=>setTrialParams({...trialParams,organizationScope:event.target.value})}><option>全部适用组织</option>{scene.organizations.map((item)=><option key={item}>{item}</option>)}</select></Field></div></div></Modal>
    <Drawer open={!!trial&&!trialOpen} title="场景试跑结果" eyebrow="样本验证" onClose={()=>setTrial(null)} footer={<Button onClick={()=>setTrial(null)}>关闭</Button>}>{trial&&<TrialResult task={trial}/>}</Drawer>
    <Modal open={publishOpen} title="发布不可变场景版本" description={`${scene.name} ${scene.version}`} confirmText="确认发布" onClose={()=>setPublishOpen(false)} onConfirm={()=>void publish()}><div className="form-stack"><div className="alert-box"><Icon name="lock"/><span>发布后固化场景、版本号、关联规则、制度依据和证据要求快照。</span></div><Field label="版本说明 *"><textarea value={publishInfo.versionNote} onChange={(event)=>setPublishInfo({...publishInfo,versionNote:event.target.value})}/></Field><Field label="发布原因 *"><textarea value={publishInfo.reason} onChange={(event)=>setPublishInfo({...publishInfo,reason:event.target.value})}/></Field><div className="publish-checklist compact">{['场景基本信息完整','启用规则完整','规则制度依据和证据要求完整','最近一次场景试跑通过'].map((item)=><div key={item}><Icon name="check"/><span>{item}</span><StatusTag>通过</StatusTag></div>)}</div></div></Modal>
  </>
}

function ValidationView({blockers,warnings,onLocate}:{blockers:ValidationIssue[];warnings:ValidationIssue[];onLocate:(issue:ValidationIssue)=>void}){
  return <div className="validation-view"><section className={blockers.length?'validation-summary danger':'validation-summary success'}><Icon name={blockers.length?'warning':'check'}/><div><strong>{blockers.length?`${blockers.length} 个阻断问题`:'校验通过'}</strong><span>{blockers.length?'修复全部阻断问题后才能试跑。':'当前版本可以进入试跑。'}</span></div></section>{blockers.map((item,index)=><button className="validation-item blocker" key={`${item.field}-${index}`} onClick={()=>onLocate(item)}><Icon name="warning"/><span>{item.message}</span><b>定位</b></button>)}{warnings.map((item,index)=><button className="validation-item" key={`${item.field}-${index}`} onClick={()=>onLocate(item)}><Icon name="warning"/><span>{item.message}</span><b>查看</b></button>)}</div>
}

function TrialResult({task}:{task:TrialTask}){
  const [filter,setFilter]=useState('全部');const samples=task.samples.filter((item)=>filter==='全部'||item.outcome===filter)
  return <div className="trial-result"><section className="trial-summary"><div><span>样本总数</span><strong>{task.summary.total}</strong></div><div><span>命中样本</span><strong>{task.summary.hit}</strong></div><div><span>未命中</span><strong>{task.summary.miss}</strong></div><div><span>执行错误</span><strong>{task.summary.error}</strong></div><div><span>证据完整率</span><strong>{task.summary.evidenceCompleteness}%</strong></div><div><span>执行耗时</span><strong>{task.summary.durationMs}ms</strong></div></section><div className={`alert-box ${task.summary.passed?'success-box':'danger'}`}><Icon name={task.summary.passed?'check':'warning'}/><span>{task.summary.passed?'试跑通过，结果已固化并允许进入发布。':'试跑未通过，请调整规则或样本范围后重试。'}</span></div><div className="trial-filter">{['全部','命中','未命中','错误'].map((item)=><button className={filter===item?'active':''} key={item} onClick={()=>setFilter(item)}>{item}</button>)}</div><div className="record-list trial-list">{samples.map((item)=><article key={item.id}><header><div><strong>{item.objectName}</strong><span>{item.code} · {item.detail.sourceType==='rule'?'标准规则':'智能判定'} · {item.detail.sourceName||item.detail.ruleName}</span></div><StatusTag>{item.outcome}</StatusTag></header><p>{item.detail.message}{item.detail.score!==undefined?`；风险评分：${item.detail.score}`:''}；证据状态：{item.evidenceStatus}{item.detail.relationHops?`；关系路径 ${item.detail.relationHops} 跳`:''}</p></article>)}</div></div>
}

function EvidenceRequirementPreview({name,meta}:{name:string;meta:{source:string;attachment:string;check:string;actual:string}}){
  return <div className="form-stack"><div className="requirement-preview-head"><Icon name="file" size={32}/><div><strong>{name}</strong><span>这是配置态的证据要求，不是运行后产生的实际附件。</span></div></div><div className="key-value"><div><span>来源系统</span><strong>{meta.source}</strong></div><div><span>附件要求</span><strong>{meta.attachment}</strong></div><div><span>完整性规则</span><strong>{meta.check}</strong></div><div><span>运行后对应</span><strong>{meta.actual}</strong></div></div><div className="file-preview"><Icon name="file" size={38}/><strong>{name}样例快照</strong><span>用于说明实际证据预览形态；第一阶段不在此处上传附件。</span><p>发布后规则命中时，系统会按该要求从来源系统固化实际证据，并在统一预警详情中提供预览、定位和来源追溯。</p></div></div>
}

export function RuleEditorPage(){
  const {id=''}=useParams();const navigate=useNavigate();const setToast=useAppStore((state)=>state.setToast)
  const [rule,setRule]=useState<RuleItem|null>(null);const [draft,setDraft]=useState<RuleItem|null>(null);const [elements,setElements]=useState<OntologyElement[]>(fallbackElements);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [dirty,setDirty]=useState(false);const [search,setSearch]=useState('');const [issues,setIssues]=useState<{blockers:ValidationIssue[];warnings:ValidationIssue[]}|null>(null);const [trial,setTrial]=useState<TrialTask|null>(null)
  const readonly=!!rule&&['已发布','已停用'].includes(rule.sceneStatus||rule.status)
  const load=async()=>{setLoading(true);setError('');try{const data=await sceneRuleApi.getRule(id);setRule(data);setDraft(structuredClone(data));const ontologies=await fetch('/api/ontologies').then((response)=>response.json()) as Array<{id:string;elements:OntologyElement[]}>;const found=ontologies.find((item)=>item.id===data.ontologyId);if(found?.elements.length)setElements(found.elements)}catch(err){setError(messageOf(err))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[id]);useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty])
  const patch=(next:Partial<RuleItem>)=>{if(!draft)return;setDraft({...draft,...next});setDirty(true)}
  const save=async()=>{if(!draft||!rule)return null;if(!dirty)return rule;try{const saved=await sceneRuleApi.updateRule(rule.versionId,{name:draft.name,type:draft.type,level:draft.level,enabled:draft.enabled,conditions:draft.conditions,pathConfig:draft.pathConfig,timeConfig:draft.timeConfig,aggregateConfig:draft.aggregateConfig,exceptions:draft.exceptions,outputs:draft.outputs,evidence:draft.evidence,policy:draft.policy,failureStrategy:draft.failureStrategy,lockVersion:rule.lockVersion});setRule(saved);setDraft(structuredClone(saved));setDirty(false);setToast('规则草稿已保存');return saved}catch(err){setToast(messageOf(err));return null}}
  const validate=async()=>{const saved=await save();if(!saved)return;try{const result=await sceneRuleApi.validateRule(saved.versionId);setIssues(result);setToast(result.blockers.length?'规则校验发现阻断问题':'规则校验通过')}catch(err){setToast(messageOf(err))}}
  const runTrial=async()=>{const saved=await save();if(!saved)return;if(!['待试跑','待发布'].includes(saved.sceneStatus||'')){setToast('请先返回场景完成整体校验');return}try{setTrial(await sceneRuleApi.createTrial(saved.sceneId,{ruleVersionId:saved.versionId,graphVersion:saved.graphVersion||'GRAPH-20260717.2',sampleDays:90,organizationScope:'全部适用组织',maxSamples:500,timeoutSeconds:60}))}catch(err){setToast(messageOf(err))}}
  const back=()=>{if(dirty&&!window.confirm('规则存在未保存修改，确认返回场景？'))return;navigate(`/scenes/${draft?.sceneId||''}?tab=rules`)}
  if(loading)return <div className="loading-state page-loading"><i/><span>正在加载规则版本…</span></div>
  if(error||!draft||!rule)return <div className="error-state page-error"><Icon name="warning"/><div><strong>规则加载失败</strong><span>{error||'规则不存在'}</span></div><Button onClick={()=>navigate('/rules')}>返回规则列表</Button></div>
  const groupedElements=elements.filter((item)=>`${item.name}${item.code}${item.type}`.toLowerCase().includes(search.toLowerCase()))
  const elementGroups=[
    {key:'class',label:'类',icon:'graph' as const,items:groupedElements.filter((item)=>item.type==='class')},
    {key:'property',label:'属性',icon:'file' as const,items:groupedElements.filter((item)=>item.type==='property')},
    {key:'relation',label:'关系',icon:'link' as const,items:groupedElements.filter((item)=>item.type==='relation')},
  ]
  const visibleElements=elements.filter((item)=>`${item.name}${item.code}${item.type}`.toLowerCase().includes(search.toLowerCase()))
  const addElement=(element:OntologyElement)=>{if(readonly||element.type==='class')return;const condition:RuleCondition={id:`cond-${Date.now()}`,fieldCode:element.code,fieldName:element.name,fieldType:element.dataType||element.type,operator:'等于',valueMode:'literal',value:''};patch({conditions:{...draft.conditions,items:[...draft.conditions.items,condition]}})}
  const toggle=(field:'outputs'|'evidence',value:string)=>{const list=draft[field];patch({[field]:list.includes(value)?list.filter((item)=>item!==value):[...list,value]} as Partial<RuleItem>)}
  return <>
    <div className="rule-editor-head"><div><button className="back-button" onClick={back}>‹ 返回所属场景</button><p className="eyebrow">规则编辑器 / {draft.code}</p><h1>{draft.name}</h1><div className="editor-meta"><StatusTag>{draft.status}</StatusTag><span>{draft.type}</span><span>所属场景：{draft.sceneName}</span><span>{dirty?'存在未保存修改':`最近保存：${dateText(draft.updatedAt)}`}</span></div></div><div className="page-actions"><Button onClick={back}>返回场景</Button>{!readonly&&<><Button onClick={()=>void save()}>保存</Button><Button onClick={()=>void validate()}>校验</Button><Button variant="primary" onClick={()=>void runTrial()}>试跑</Button></>}</div></div>
    <div className="rule-editor-shell">
      <aside className="ontology-palette rule-side-panel"><header><div><span>当前图谱结构版本</span><strong>{draft.ontologyId}</strong></div><StatusTag>已发布</StatusTag></header><label className="palette-search"><Icon name="search" size={15}/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="搜索类、属性或关系"/></label><div className="palette-groups">{elementGroups.map((group)=><section key={group.key}><h3>{group.label}</h3>{group.items.map((item)=><button key={item.id} disabled={readonly||item.type==='class'} onClick={()=>addElement(item)}><span><Icon name={group.icon} size={14}/><strong>{item.name}</strong></span><small>{item.code}</small></button>)}</section>)}</div></aside>
      <main className="rule-canvas"><Panel title="规则基础配置" subtitle="规则编码在当前场景版本内唯一"><div className="form-section two-column"><Field label="规则名称 *"><input value={draft.name} disabled={readonly} onChange={(event)=>patch({name:event.target.value})}/></Field><Field label="规则编码"><input value={draft.code} disabled/></Field><Field label="风险等级"><select value={draft.level} disabled={readonly} onChange={(event)=>patch({level:event.target.value as RiskLevel})}>{levels.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="是否启用"><select value={draft.enabled?'启用':'停用'} disabled={readonly} onChange={(event)=>patch({enabled:event.target.value==='启用'})}><option>启用</option><option>停用</option></select></Field><Field label="失败策略"><select value={draft.failureStrategy} disabled={readonly} onChange={(event)=>patch({failureStrategy:event.target.value})}><option>进入异常队列</option><option>不生成预警</option><option>生成待核查线索</option></select></Field></div></Panel>
      <Panel title="条件表达式" subtitle="支持AND、OR及最多三层条件组" actions={!readonly?<Button icon="plus" onClick={()=>patch({conditions:{...draft.conditions,items:[...draft.conditions.items,{id:`group-${Date.now()}`,logic:'AND',items:[]}]}})}>新增条件组</Button>:undefined}><ConditionGroupEditor group={draft.conditions} depth={1} readonly={readonly} elements={elements.filter((item)=>item.type==='property')} onChange={(conditions)=>patch({conditions})}/><button className="drop-zone" disabled={readonly} onClick={()=>visibleElements.find((item)=>item.type==='property')&&addElement(visibleElements.find((item)=>item.type==='property')!)}>＋ 从左侧选择结构元素或新增条件</button></Panel>
      {draft.type==='关系路径'&&<Panel title="关系路径" subtitle="首版最多支持两跳"><div className="path-hop-list">{draft.pathConfig.hops.map((hop,index)=><div className="path-hop-row" key={index}><input value={hop.from} disabled={readonly} onChange={(event)=>{const hops=[...draft.pathConfig.hops];hops[index]={...hop,from:event.target.value};patch({pathConfig:{hops}})}}/><input value={hop.relation} disabled={readonly} onChange={(event)=>{const hops=[...draft.pathConfig.hops];hops[index]={...hop,relation:event.target.value};patch({pathConfig:{hops}})}}/><input value={hop.to} disabled={readonly} onChange={(event)=>{const hops=[...draft.pathConfig.hops];hops[index]={...hop,to:event.target.value};patch({pathConfig:{hops}})}}/>{!readonly&&<button onClick={()=>patch({pathConfig:{hops:draft.pathConfig.hops.filter((_,i)=>i!==index)}})}><Icon name="close" size={14}/></button>}</div>)}{!readonly&&draft.pathConfig.hops.length<2&&<Button icon="plus" onClick={()=>patch({pathConfig:{hops:[...draft.pathConfig.hops,{from:'',relation:'',to:''}]}})}>新增一跳关系</Button>}</div></Panel>}
      {draft.type==='时序'&&<Panel title="时序窗口"><div className="form-section two-column"><Field label="目标类"><select value={draft.timeConfig.eventCode} disabled={readonly} onChange={(event)=>patch({timeConfig:{...draft.timeConfig,eventCode:event.target.value}})}>{elements.filter((item)=>item.type==='class').map((item)=><option value={item.code} key={item.code}>{item.name}</option>)}</select></Field><Field label="时间窗口"><div className="compound-input"><input type="number" value={draft.timeConfig.windowValue} disabled={readonly} onChange={(event)=>patch({timeConfig:{...draft.timeConfig,windowValue:Number(event.target.value)}})}/><select value={draft.timeConfig.windowUnit} disabled={readonly} onChange={(event)=>patch({timeConfig:{...draft.timeConfig,windowUnit:event.target.value}})}><option>小时</option><option>天</option><option>月</option></select></div></Field></div></Panel>}
      {draft.type==='聚合'&&<Panel title="聚合配置"><div className="form-section two-column"><Field label="聚合函数"><select value={draft.aggregateConfig.function} disabled={readonly} onChange={(event)=>patch({aggregateConfig:{...draft.aggregateConfig,function:event.target.value}})}><option>COUNT</option><option>SUM</option><option>AVG</option><option>MAX</option></select></Field><Field label="聚合字段"><select value={draft.aggregateConfig.fieldCode} disabled={readonly} onChange={(event)=>patch({aggregateConfig:{...draft.aggregateConfig,fieldCode:event.target.value}})}><option value="">请选择</option>{elements.filter((item)=>item.type==='property').map((item)=><option value={item.code} key={item.code}>{item.name}</option>)}</select></Field><Field label="比较运算符"><select value={draft.aggregateConfig.operator} disabled={readonly} onChange={(event)=>patch({aggregateConfig:{...draft.aggregateConfig,operator:event.target.value}})}><option>大于</option><option>大于等于</option><option>等于</option></select></Field><Field label="阈值"><input type="number" value={draft.aggregateConfig.threshold} disabled={readonly} onChange={(event)=>patch({aggregateConfig:{...draft.aggregateConfig,threshold:Number(event.target.value)}})}/></Field></div></Panel>}
      </main>
      <aside className="rule-inspector rule-side-panel"><Panel title="命中输出"><div className="check-grid vertical">{outputOptions.map((item)=><label key={item}><input type="checkbox" checked={draft.outputs.includes(item)} disabled={readonly} onChange={()=>toggle('outputs',item)}/><span>{item}</span></label>)}</div></Panel><Panel title="证据要求"><div className="check-grid vertical">{evidenceOptions.map((item)=><label key={item}><input type="checkbox" checked={draft.evidence.includes(item)} disabled={readonly} onChange={()=>toggle('evidence',item)}/><span>{item}</span></label>)}</div></Panel><Panel title="例外条件"><label className="switch-line"><span>启用例外</span><input type="checkbox" checked={draft.exceptions.enabled} disabled={readonly} onChange={(event)=>patch({exceptions:{...draft.exceptions,enabled:event.target.checked}})}/></label><textarea value={draft.exceptions.description} disabled={readonly} onChange={(event)=>patch({exceptions:{...draft.exceptions,description:event.target.value}})} placeholder="说明特殊授权、组织或白名单例外"/></Panel><Panel title="制度依据"><div className="form-stack compact-fields"><Field label="制度名称"><input value={draft.policy.name} disabled={readonly} onChange={(event)=>patch({policy:{...draft.policy,name:event.target.value}})}/></Field><Field label="制度版本"><input value={draft.policy.version} disabled={readonly} onChange={(event)=>patch({policy:{...draft.policy,version:event.target.value}})}/></Field><Field label="制度条款"><input value={draft.policy.clause} disabled={readonly} onChange={(event)=>patch({policy:{...draft.policy,clause:event.target.value}})}/></Field></div></Panel><Panel title="规则摘要" className="rule-summary-card"><p>{draft.summary}</p></Panel></aside>
    </div>
    {!readonly&&<footer className="editor-action-bar"><div><span className={dirty?'dirty-dot':''}/><strong>{dirty?'规则修改尚未保存':'规则草稿已保存'}</strong><small>保存后返回场景完成整体校验</small></div><div><Button onClick={back}>返回场景</Button><Button onClick={()=>void save()}>保存</Button><Button onClick={()=>void validate()}>校验</Button><Button variant="primary" onClick={()=>void runTrial()}>试跑</Button></div></footer>}
    <Drawer open={!!issues} title="规则校验结果" eyebrow="表达式与依赖检查" onClose={()=>setIssues(null)}>{issues&&<ValidationView blockers={issues.blockers} warnings={issues.warnings} onLocate={()=>setIssues(null)}/>}</Drawer>
    <Drawer open={!!trial} title="规则试跑结果" eyebrow="当前规则样本验证" onClose={()=>setTrial(null)}>{trial&&<TrialResult task={trial}/>}</Drawer>
  </>
}

function ConditionGroupEditor({group,depth,readonly,elements,onChange,onRemove}:{group:ConditionGroup;depth:number;readonly:boolean;elements:OntologyElement[];onChange:(group:ConditionGroup)=>void;onRemove?:()=>void}){
  const operators=['等于','不等于','大于','大于等于','小于','包含','不包含','为空','不为空','覆盖']
  const updateItem=(index:number,item:RuleCondition|ConditionGroup)=>onChange({...group,items:group.items.map((current,i)=>i===index?item:current)})
  const removeItem=(index:number)=>onChange({...group,items:group.items.filter((_,i)=>i!==index)})
  const addCondition=()=>{const element=elements[0];onChange({...group,items:[...group.items,{id:`cond-${Date.now()}`,fieldCode:element?.code||'',fieldName:element?.name||'',fieldType:element?.dataType||'文本',operator:'等于',valueMode:'literal',value:''}]})}
  const addGroup=()=>onChange({...group,items:[...group.items,{id:`group-${Date.now()}`,logic:'AND',items:[]}]})
  return <div className={`condition-group depth-${depth}`}><header><div><strong>{depth===1?'根条件组':`嵌套条件组 · 第${depth}层`}</strong><button className={`logic-toggle ${group.logic.toLowerCase()}`} disabled={readonly} onClick={()=>onChange({...group,logic:group.logic==='AND'?'OR':'AND'})}>{group.logic}</button></div>{!readonly&&<div className="condition-group-actions"><button onClick={addCondition}>＋ 条件</button>{depth<3&&<button onClick={addGroup}>＋ 条件组</button>}{onRemove&&<button onClick={onRemove}>删除组</button>}</div>}</header><div className="condition-items">{group.items.map((item,index)=>isConditionGroup(item)?<ConditionGroupEditor key={item.id} group={item} depth={depth+1} readonly={readonly} elements={elements} onChange={(next)=>updateItem(index,next)} onRemove={()=>removeItem(index)}/>:<div className="dynamic-condition-row" key={item.id}><select value={item.fieldCode} disabled={readonly} onChange={(event)=>{const element=elements.find((candidate)=>candidate.code===event.target.value);updateItem(index,{...item,fieldCode:event.target.value,fieldName:element?.name||'',fieldType:element?.dataType||''})}}><option value="">选择字段</option>{elements.map((element)=><option value={element.code} key={element.code}>{element.name}</option>)}</select><select value={item.operator} disabled={readonly} onChange={(event)=>updateItem(index,{...item,operator:event.target.value})}>{operators.map((operator)=><option key={operator}>{operator}</option>)}</select><select value={item.valueMode} disabled={readonly} onChange={(event)=>updateItem(index,{...item,valueMode:event.target.value as 'literal'|'field',value:'',valueFieldCode:''})}><option value="literal">固定值</option><option value="field">字段值</option></select>{item.valueMode==='field'?<select value={item.valueFieldCode||''} disabled={readonly} onChange={(event)=>{const element=elements.find((candidate)=>candidate.code===event.target.value);updateItem(index,{...item,valueFieldCode:event.target.value,valueFieldName:element?.name||''})}}><option value="">选择对比字段</option>{elements.map((element)=><option value={element.code} key={element.code}>{element.name}</option>)}</select>:<input value={item.value} disabled={readonly} onChange={(event)=>updateItem(index,{...item,value:event.target.value})} placeholder="请输入比较值"/>}{!readonly&&<button onClick={()=>removeItem(index)}><Icon name="close" size={14}/></button>}</div>)}</div>{!group.items.length&&<div className="condition-empty">当前条件组为空，请新增条件或从左侧选择图谱结构属性。</div>}</div>
}

