import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ruleClosureApi } from '../ruleClosureApi'
import { sceneRuleApi } from '../sceneRuleApi'
import type { ConditionGroup, OntologyElement, PathHop, RuleCondition, RuleItem, SceneItem, ValidationIssue } from '../sceneRuleTypes'
import { isConditionGroup } from '../sceneRuleTypes'
import type { RiskLevel } from '../types'
import { useAppStore } from '../store'
import { Button, EmptyState, Field, FilterGrid, Icon, Modal, PageHeader, Panel, RiskTag, StatusTag } from '../ui'

const ruleTypes:RuleItem['type'][]=['属性','字段比对','关系路径','时序','聚合']
const levels:RiskLevel[]=['重大','高','中','低']
const defaultOutputs=['主体名称与编码','命中条件及实际值','来源记录与版本','规则执行时间']
const optionalOutputs=['关系路径','事件时间','聚合结果']
const optionalEvidence=['审批记录','联系方式来源','附件材料','规则运行明细']
const fallbackElements:OntologyElement[]=[
  {id:'p1',type:'property',code:'PROC.Supplier.phone',name:'供应商联系电话',dataType:'文本',constraint:'',description:'供应商登记联系方式'},
  {id:'p2',type:'property',code:'PROC.Reviewer.phone',name:'评审人员联系电话',dataType:'文本',constraint:'',description:'评审人员登记联系方式'},
  {id:'p3',type:'property',code:'PROC.Contract.change_rate',name:'合同金额变更比例',dataType:'数字',constraint:'',description:'合同金额变化比例'},
  {id:'p4',type:'property',code:'PROC.Contract.change_amount',name:'合同变更金额',dataType:'金额',constraint:'',description:'合同累计变更金额'},
  {id:'r1',type:'relation',code:'PROC.shared_contact',name:'共同使用',dataType:'联系方式 → 评审人员',constraint:'',description:'共同使用联系方式'},
  {id:'e1',type:'class',code:'PROC.BidConfirmed',name:'中标确认',dataType:'类',constraint:'发生时间必填',description:'用于表达中标确认业务记录的普通类'},
]
const messageOf=(error:unknown)=>error instanceof Error?error.message:'操作失败，请稍后重试'
const dateText=(value:unknown)=>value?new Date(String(value)).toLocaleString('zh-CN',{hour12:false}):'—'
const unique=(items:string[])=>[...new Set(items.filter(Boolean))]

function ruleConfigured(rule:RuleItem){
  if(['已发布','已停用'].includes(rule.status))return true
  if(rule.type==='关系路径')return rule.pathConfig.hops.length>0
  if(rule.type==='时序')return Boolean(rule.timeConfig.eventCode&&rule.timeConfig.windowValue)
  if(rule.type==='聚合')return Boolean(rule.aggregateConfig.fieldCode&&rule.aggregateConfig.threshold)
  return rule.conditions.items.some((item)=>!isConditionGroup(item)&&item.fieldCode&&item.operator&&(['为空','不为空'].includes(item.operator)||item.value||item.valueFieldCode))
}

function displayStatus(rule:RuleItem){
  if(rule.status==='已发布'||rule.sceneStatus==='已发布')return '已发布'
  if(rule.status==='已停用'||rule.sceneStatus==='已停用')return '已停用'
  return ruleConfigured(rule)?'已配置':'未完成'
}

export function SimpleRuleManagementPage(){
  const navigate=useNavigate();const setToast=useAppStore((state)=>state.setToast)
  const [keyword,setKeyword]=useState('');const [rows,setRows]=useState<RuleItem[]>([]);const [scenes,setScenes]=useState<SceneItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  const [newOpen,setNewOpen]=useState(false);const [draft,setDraft]=useState({sceneId:'',name:'',type:'属性' as RuleItem['type'],levelMode:'inherit',level:'高' as RiskLevel})
  const editableScenes=useMemo(()=>scenes.filter((scene)=>!['已发布','已停用'].includes(scene.status)),[scenes])
  const selectedScene=editableScenes.find((scene)=>scene.id===draft.sceneId)
  const load=async(nextKeyword=keyword)=>{setLoading(true);setError('');try{const [ruleRows,sceneRows]=await Promise.all([ruleClosureApi.listRules(nextKeyword),ruleClosureApi.listScenes()]);setRows(ruleRows);setScenes(sceneRows)}catch(err){setError(messageOf(err))}finally{setLoading(false)}}
  useEffect(()=>{void load('')},[])
  const openNew=()=>{const scene=editableScenes[0];setDraft({sceneId:scene?.id||'',name:'',type:'属性',levelMode:'inherit',level:scene?.level||'高'});setNewOpen(true)}
  const chooseScene=(sceneId:string)=>{const scene=editableScenes.find((item)=>item.id===sceneId);setDraft({...draft,sceneId,level:draft.levelMode==='inherit'?(scene?.level||'高'):draft.level})}
  const create=async()=>{if(!draft.sceneId){setToast('当前没有可编辑的场景草稿，请先新建或复制场景版本');return}if(!draft.name.trim()){setToast('规则名称不能为空');return}try{const level=draft.levelMode==='inherit'?(selectedScene?.level||'高'):draft.level;const rule=await sceneRuleApi.createRuleForScene(draft.sceneId,{name:draft.name,type:draft.type,level});setNewOpen(false);setToast('规则草稿已创建，请配置判断逻辑');navigate(`/rules/${rule.versionId}`)}catch(err){setToast(messageOf(err))}}
  const remove=async(rule:RuleItem)=>{if(!window.confirm(`确认删除“${rule.name}”？已发布历史版本不会受到影响。`))return;try{await ruleClosureApi.deleteRule(rule.versionId);setToast('草稿规则已删除');await load()}catch(err){setToast(messageOf(err))}}

  return <>
    <PageHeader eyebrow="能力中心 / 规则管理" title="规则管理" description="新增规则只需确定所属场景和判断类型，制度依据、证据要求和命中输出默认继承场景。" actions={<><Button icon="refresh" onClick={()=>void load()}>刷新</Button><Button variant="primary" icon="plus" onClick={openNew}>新增规则</Button></>}/>
    <FilterGrid onReset={()=>{setKeyword('');void load('')}} onSearch={()=>void load()}><Field label="关键词"><input value={keyword} onChange={(event)=>setKeyword(event.target.value)} placeholder="规则名称、编码或所属场景"/></Field></FilterGrid>
    <Panel title="规则列表" subtitle="规则只负责判断逻辑，场景统一负责校验、试跑和发布">
      {loading?<div className="loading-state"><i/><span>正在加载规则…</span></div>:error?<div className="error-state"><Icon name="warning"/><div><strong>规则加载失败</strong><span>{error}</span></div><Button onClick={()=>void load()}>重试</Button></div>:rows.length===0?<EmptyState title="暂无规则" description="点击右上角“新增规则”开始配置。"/>:<div className="table-container"><table><thead><tr><th>规则名称 / 编码</th><th>所属场景</th><th>判断类型</th><th>风险等级</th><th>配置摘要</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{rows.map((rule)=>{const status=displayStatus(rule);const readonly=['已发布','已停用'].includes(status);return <tr key={rule.versionId}><td><strong>{rule.name}</strong><small className="cell-sub">{rule.code}</small></td><td><button className="table-link" onClick={()=>navigate(`/scenes/${rule.sceneId}?tab=rules`)}>{rule.sceneName}</button></td><td>{rule.type}</td><td><RiskTag level={rule.level}/></td><td className="summary-cell">{ruleConfigured(rule)?rule.summary:'尚未完成判断逻辑配置'}</td><td><StatusTag>{status}</StatusTag></td><td>{dateText(rule.updatedAt)}</td><td><div className="row-actions"><button onClick={()=>navigate(`/rules/${rule.versionId}`)}>{readonly?'查看':'继续配置'}</button>{!readonly&&<button className="danger-link" onClick={()=>void remove(rule)}>删除</button>}</div></td></tr>})}</tbody></table></div>}
    </Panel>
    <Modal open={newOpen} title="新增规则" description="第一步：选择所属场景并确定规则的判断类型。" confirmText="下一步：配置判断逻辑" onClose={()=>setNewOpen(false)} onConfirm={()=>void create()}><div className="form-stack">{editableScenes.length===0&&<div className="alert-box danger"><Icon name="warning"/><span>没有可编辑的场景版本，请先新建场景或复制已发布场景。</span></div>}<div className="form-section two-column"><Field label="所属场景 *"><select value={draft.sceneId} onChange={(event)=>chooseScene(event.target.value)}><option value="">请选择场景</option>{editableScenes.map((scene)=><option value={scene.id} key={scene.id}>{scene.name} · {scene.version} · {scene.status}</option>)}</select></Field><Field label="规则名称 *"><input value={draft.name} onChange={(event)=>setDraft({...draft,name:event.target.value})} placeholder="例如：供应商与评审人员联系电话相同"/></Field><Field label="规则类型 *"><select value={draft.type} onChange={(event)=>setDraft({...draft,type:event.target.value as RuleItem['type']})}>{ruleTypes.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="风险等级"><select value={draft.levelMode==='inherit'?'inherit':draft.level} onChange={(event)=>event.target.value==='inherit'?setDraft({...draft,levelMode:'inherit',level:selectedScene?.level||'高'}):setDraft({...draft,levelMode:'override',level:event.target.value as RiskLevel})}><option value="inherit">继承场景：{selectedScene?.level||'—'}</option>{levels.map((item)=><option value={item} key={item}>覆盖为：{item}</option>)}</select></Field></div>{selectedScene&&<div className="scene-context-preview"><div><span>主对象</span><strong>{selectedScene.objectName}</strong></div><div><span>目标类</span><strong>{selectedScene.eventName||'无'}</strong></div><div><span>图谱结构版本</span><strong>{selectedScene.ontologyId}</strong></div><div><span>场景版本</span><strong>{selectedScene.version}</strong></div></div>}</div></Modal>
  </>
}

export function SimpleRuleEditorPage(){
  const {id=''}=useParams();const navigate=useNavigate();const setToast=useAppStore((state)=>state.setToast)
  const [rule,setRule]=useState<RuleItem|null>(null);const [draft,setDraft]=useState<RuleItem|null>(null);const [scene,setScene]=useState<SceneItem|null>(null);const [elements,setElements]=useState<OntologyElement[]>(fallbackElements)
  const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [dirty,setDirty]=useState(false);const [issues,setIssues]=useState<ValidationIssue[]>([]);const [advanced,setAdvanced]=useState(false);const [overridePolicy,setOverridePolicy]=useState(false)
  const readonly=!!rule&&['已发布','已停用'].includes(rule.sceneStatus||rule.status)
  const load=async()=>{setLoading(true);setError('');try{const current=await sceneRuleApi.getRule(id);const parent=await sceneRuleApi.getScene(current.sceneId);setRule(current);setDraft(structuredClone(current));setScene(parent);const ontologies=await fetch('/api/ontologies').then((response)=>response.json()) as Array<{id:string;elements:OntologyElement[]}>;const ontology=ontologies.find((item)=>item.id===current.ontologyId);if(ontology?.elements.length)setElements(ontology.elements);const inherited=parent.policies[0];setOverridePolicy(Boolean(current.policy.name&&inherited&&current.policy.name!==inherited.name))}catch(err){setError(messageOf(err))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[id]);useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty])
  const patch=(next:Partial<RuleItem>)=>{if(!draft)return;setDraft({...draft,...next});setDirty(true);setIssues([])}
  const properties=elements.filter((item)=>item.type==='property');const relations=elements.filter((item)=>item.type==='relation');const events=elements.filter((item)=>item.type==='class')
  const scenePolicy=scene?.policies[0]||{name:'',version:'',clause:''}
  const extraOutputs=draft?draft.outputs.filter((item)=>!defaultOutputs.includes(item)):[]
  const extraEvidence=draft&&scene?draft.evidence.filter((item)=>!scene.evidence.includes(item)):[]
  const flatConditions=draft?draft.conditions.items.filter((item):item is RuleCondition=>!isConditionGroup(item)):[]
  const nestedCount=draft?draft.conditions.items.filter(isConditionGroup).length:0

  const addCondition=(element?:OntologyElement)=>{if(!draft)return;const field=element||properties[0];const condition:RuleCondition={id:`cond-${Date.now()}`,fieldCode:field?.code||'',fieldName:field?.name||'',fieldType:field?.dataType||'文本',operator:'等于',valueMode:draft.type==='字段比对'?'field':'literal',value:'',valueFieldCode:'',valueFieldName:''};patch({conditions:{...draft.conditions,items:[...draft.conditions.items,condition]}})}
  const updateCondition=(conditionId:string,next:Partial<RuleCondition>)=>{if(!draft)return;patch({conditions:{...draft.conditions,items:draft.conditions.items.map((item)=>!isConditionGroup(item)&&item.id===conditionId?{...item,...next}:item)}})}
  const removeCondition=(conditionId:string)=>{if(!draft)return;patch({conditions:{...draft.conditions,items:draft.conditions.items.filter((item)=>item.id!==conditionId)}})}
  const addRelation=(relation:OntologyElement)=>{if(!draft||draft.pathConfig.hops.length>=2)return;const [from='',to='']=String(relation.dataType||'').split('→').map((item)=>item.trim());patch({pathConfig:{hops:[...draft.pathConfig.hops,{from:from||scene?.objectName||'',relation:relation.name,to:to||'目标对象'}]}})}
  const updateHop=(index:number,relationCode:string)=>{if(!draft)return;const relation=relations.find((item)=>item.code===relationCode);if(!relation)return;const [from='',to='']=String(relation.dataType||'').split('→').map((item)=>item.trim());const hops=[...draft.pathConfig.hops];hops[index]={from:from||scene?.objectName||'',relation:relation.name,to:to||'目标对象'};patch({pathConfig:{hops}})}
  const selectEvent=(event:OntologyElement)=>{if(!draft)return;patch({timeConfig:{...draft.timeConfig,eventCode:event.code}})}
  const toggleExtra=(field:'outputs'|'evidence',value:string,inherited:string[])=>{if(!draft)return;const current=draft[field];const next=current.includes(value)?current.filter((item)=>item!==value):[...current,value];patch({[field]:unique([...inherited,...next])} as Partial<RuleItem>)}
  const relationCode=(hop:PathHop)=>relations.find((item)=>item.name===hop.relation)?.code||''

  const normalizedConditions=():ConditionGroup=>{
    if(!draft)return{id:'group-root',logic:'AND',items:[]}
    if(draft.type==='关系路径'){const hop=draft.pathConfig.hops[0];return{id:'group-root',logic:'AND',items:hop?[{id:'relation-condition',fieldCode:relationCode(hop)||hop.relation,fieldName:hop.relation,fieldType:'关系',operator:'存在',valueMode:'literal',value:'true'}]:[]}}
    if(draft.type==='时序'){return{id:'group-root',logic:'AND',items:draft.timeConfig.eventCode?[{id:'time-condition',fieldCode:draft.timeConfig.eventCode,fieldName:events.find((item)=>item.code===draft.timeConfig.eventCode)?.name||'事件',fieldType:'事件',operator:draft.timeConfig.direction||'之前',valueMode:'literal',value:`${draft.timeConfig.windowValue}${draft.timeConfig.windowUnit}`}]:[]}}
    if(draft.type==='聚合'){return{id:'group-root',logic:'AND',items:draft.aggregateConfig.fieldCode?[{id:'aggregate-condition',fieldCode:draft.aggregateConfig.fieldCode,fieldName:properties.find((item)=>item.code===draft.aggregateConfig.fieldCode)?.name||'聚合字段',fieldType:'聚合',operator:draft.aggregateConfig.operator,valueMode:'literal',value:String(draft.aggregateConfig.threshold)}]:[]}}
    return draft.conditions
  }
  const composePayload=()=>{
    if(!draft||!scene)return null
    const policy=overridePolicy?draft.policy:scenePolicy
    return{name:draft.name,type:draft.type,level:draft.level,enabled:true,conditions:normalizedConditions(),pathConfig:draft.pathConfig,timeConfig:draft.timeConfig,aggregateConfig:draft.aggregateConfig,exceptions:{enabled:Boolean(draft.exceptions.description||scene.exceptions.description),description:draft.exceptions.description||scene.exceptions.description,whitelist:draft.exceptions.whitelist||[]},outputs:unique([...defaultOutputs,...extraOutputs]),evidence:unique([...scene.evidence,...extraEvidence]),policy,failureStrategy:draft.failureStrategy,lockVersion:rule?.lockVersion||draft.lockVersion}
  }
  const save=async(silent=false)=>{if(!draft||!rule||!scene)return null;const payload=composePayload();if(!payload)return null;try{const saved=await sceneRuleApi.updateRule(rule.versionId,payload);setRule(saved);setDraft(structuredClone(saved));setDirty(false);if(!silent)setToast('规则草稿已保存');return saved}catch(err){setToast(messageOf(err));return null}}
  const complete=async()=>{const saved=await save(true);if(!saved)return;try{const result=await sceneRuleApi.validateRule(saved.versionId);if(result.blockers.length){setIssues(result.blockers);setToast(`还有${result.blockers.length}项需要完成`);return}setDirty(false);setToast('规则配置已完成，返回场景进行统一校验');navigate(`/scenes/${saved.sceneId}?tab=rules&completed=${encodeURIComponent(saved.code)}`)}catch(err){setToast(messageOf(err))}}
  const cancel=()=>{if(dirty&&!window.confirm('当前修改尚未保存，确认放弃并返回规则管理？'))return;navigate('/rules')}
  const logicDone=!!draft&&ruleConfigured({...draft,conditions:normalizedConditions()});const resultDone=Boolean(scene?.evidence.length&&scenePolicy.name);const configured=logicDone&&resultDone

  if(loading)return <div className="loading-state page-loading"><i/><span>正在加载规则配置…</span></div>
  if(error||!draft||!rule||!scene)return <div className="error-state page-error"><Icon name="warning"/><div><strong>规则加载失败</strong><span>{error||'规则或所属场景不存在'}</span></div><Button onClick={()=>navigate('/rules')}>返回规则管理</Button></div>
  const currentStatus=readonly?(rule.status==='已停用'?'已停用':'已发布'):(configured?'已配置':'未完成')
  return <>
    <div className="simple-rule-header"><div><button className="back-button" onClick={cancel}>‹ 返回规则管理</button><p className="eyebrow">新增规则 / {rule.code}</p><h1>{draft.name}</h1><div className="editor-meta"><StatusTag>{currentStatus}</StatusTag><span>{draft.type}</span><span>所属场景：{scene.name}</span><span>{dirty?'存在未保存修改':`最近保存：${dateText(rule.updatedAt)}`}</span></div></div>{readonly?<Button onClick={()=>navigate(`/scenes/${scene.id}?tab=rules`)}>查看所属场景</Button>:<div className="page-actions"><Button onClick={cancel}>取消</Button><Button onClick={()=>void save()}>保存草稿</Button><Button variant="primary" onClick={()=>void complete()}>完成配置并返回场景</Button></div>}</div>
    <div className="simple-rule-steps">{[{label:'基本信息',done:Boolean(draft.name&&draft.type)},{label:'判断逻辑',done:logicDone},{label:'结果摘要',done:resultDone},{label:'完成',done:configured}].map((step,index)=><div className={step.done?'done':''} key={step.label}><i>{step.done?'✓':index+1}</i><span>{step.label}</span></div>)}</div>
    <section className="rule-context-strip"><div><span>所属场景</span><strong>{scene.name} · {scene.version}</strong></div><div><span>主对象</span><strong>{scene.objectName}</strong></div><div><span>目标类</span><strong>{scene.eventName||'无'}</strong></div><div><span>图谱结构版本</span><strong>{scene.ontologyId}</strong></div><div><span>默认等级</span><strong>{scene.level}风险</strong></div></section>
    <div className="simple-rule-layout">
      <main className="simple-rule-main"><Panel title="1. 基本信息" subtitle="规则编码由系统生成，所属场景信息自动继承"><div className="form-section two-column"><Field label="规则名称 *"><input value={draft.name} disabled={readonly} onChange={(event)=>patch({name:event.target.value})}/></Field><Field label="规则类型 *"><select value={draft.type} disabled={readonly} onChange={(event)=>patch({type:event.target.value as RuleItem['type'],conditions:{id:'group-root',logic:'AND',items:[]},pathConfig:{hops:[]}})}>{ruleTypes.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="风险等级"><select value={draft.level===scene.level?'inherit':draft.level} disabled={readonly} onChange={(event)=>patch({level:event.target.value==='inherit'?scene.level:event.target.value as RiskLevel})}><option value="inherit">继承场景：{scene.level}</option>{levels.map((item)=><option key={item} value={item}>覆盖为：{item}</option>)}</select></Field><Field label="规则编码"><input value={rule.code} disabled/></Field></div></Panel>
      <Panel title="2. 配置判断逻辑" subtitle={logicHelp(draft.type)}>{draft.type==='属性'&&<FlatConditionEditor conditions={flatConditions} properties={properties} readonly={readonly} fieldCompare={false} onAdd={addCondition} onUpdate={updateCondition} onRemove={removeCondition}/>} {draft.type==='字段比对'&&<FlatConditionEditor conditions={flatConditions} properties={properties} readonly={readonly} fieldCompare onAdd={addCondition} onUpdate={updateCondition} onRemove={removeCondition}/>} {draft.type==='关系路径'&&<RelationLogic scene={scene} relations={relations} hops={draft.pathConfig.hops} readonly={readonly} onAdd={addRelation} onUpdate={updateHop} onRemove={(index)=>patch({pathConfig:{hops:draft.pathConfig.hops.filter((_,itemIndex)=>itemIndex!==index)}})}/>} {draft.type==='时序'&&<TimeLogic events={events} config={draft.timeConfig} readonly={readonly} onSelect={selectEvent} onChange={(timeConfig)=>patch({timeConfig})}/>} {draft.type==='聚合'&&<AggregateLogic properties={properties} scene={scene} config={draft.aggregateConfig} readonly={readonly} onChange={(aggregateConfig)=>patch({aggregateConfig})}/>} {nestedCount>0&&<div className="legacy-logic-note"><Icon name="warning"/><span>当前规则还保留{nestedCount}个历史高级条件组。简化编辑器不会自动删除，切换规则类型后将以当前简化配置为准。</span></div>}</Panel>
      {issues.length>0&&<Panel title={`还有 ${issues.length} 项需要完成`} className="simple-rule-issues">{issues.map((issue,index)=><div key={`${issue.field}-${index}`}><Icon name="warning"/><span>{issue.message}</span></div>)}</Panel>}
      </main>
      <aside className="simple-rule-result"><Panel title="3. 规则结果" subtitle="默认继承场景配置，无需重复填写"><div className="result-summary-list"><section><span>风险等级</span><strong>{draft.level}风险 {draft.level===scene.level&&<small>继承场景</small>}</strong></section><section><span>命中输出</span><strong>使用系统默认输出</strong><p>{defaultOutputs.join('、')}</p></section><section><span>证据要求</span><strong>继承场景 {scene.evidence.length} 项证据要求</strong><p>{scene.evidence.join('、')||'场景尚未配置证据要求'}</p></section><section><span>例外条件</span><strong>使用场景例外范围</strong><p>{scene.exceptions.description||'未配置例外'}</p></section><section><span>制度依据</span><strong>{scenePolicy.name||'场景尚未配置制度依据'}</strong><p>{scenePolicy.version} {scenePolicy.clause}</p></section></div>{!readonly&&<button className="advanced-toggle" onClick={()=>setAdvanced((value)=>!value)}>{advanced?'收起高级设置':'展开高级设置'} <Icon name="chevron" size={14}/></button>}{advanced&&!readonly&&<div className="advanced-settings"><Field label="补充命中输出"><div className="check-grid vertical">{optionalOutputs.map((item)=><label key={item}><input type="checkbox" checked={extraOutputs.includes(item)} onChange={()=>toggleExtra('outputs',item,defaultOutputs)}/><span>{item}</span></label>)}</div></Field><Field label="补充证据要求"><div className="check-grid vertical">{optionalEvidence.map((item)=><label key={item}><input type="checkbox" checked={draft.evidence.includes(item)} onChange={()=>toggleExtra('evidence',item,scene.evidence)}/><span>{item}</span></label>)}</div></Field><label className="switch-line"><span>覆盖场景制度依据</span><input type="checkbox" checked={overridePolicy} onChange={(event)=>{setOverridePolicy(event.target.checked);setDirty(true)}}/></label>{overridePolicy&&<div className="form-stack"><Field label="制度名称"><input value={draft.policy.name} onChange={(event)=>patch({policy:{...draft.policy,name:event.target.value}})}/></Field><Field label="制度版本"><input value={draft.policy.version} onChange={(event)=>patch({policy:{...draft.policy,version:event.target.value}})}/></Field><Field label="制度条款"><input value={draft.policy.clause} onChange={(event)=>patch({policy:{...draft.policy,clause:event.target.value}})}/></Field></div>}<Field label="规则专属例外"><textarea value={draft.exceptions.description} onChange={(event)=>patch({exceptions:{...draft.exceptions,description:event.target.value,enabled:Boolean(event.target.value)}})} placeholder="不填写时使用场景例外范围"/></Field></div>}</Panel><div className="next-action-card"><Icon name={configured?'check':'clock'}/><div><strong>{configured?'规则配置已完整':'请完成判断逻辑'}</strong><span>{configured?'点击“完成配置并返回场景”，在场景中统一校验和试跑。':'系统会自动检查当前规则类型所需的字段。'}</span></div></div></aside>
    </div>
    {!readonly&&<footer className="editor-action-bar"><div><span className={dirty?'dirty-dot':''}/><strong>{dirty?'修改尚未保存':currentStatus==='已配置'?'规则已配置':'规则草稿已保存'}</strong><small>规则完成后返回场景统一校验、试跑和发布</small></div><div><Button onClick={cancel}>取消</Button><Button onClick={()=>void save()}>保存草稿</Button><Button variant="primary" onClick={()=>void complete()}>完成配置并返回场景</Button></div></footer>}
  </>
}

function logicHelp(type:RuleItem['type']){return type==='属性'?'选择一个属性，与固定值进行比较。':type==='字段比对'?'选择两个属性进行比较。':type==='关系路径'?'从场景主对象出发，选择最多两跳关系。':type==='时序'?'选择判断类节点及其相对场景目标类的时间窗口。':'选择统计属性、聚合函数和判断阈值。'}

function operatorsFor(element?:OntologyElement){const type=element?.dataType||'';if(type.includes('数字')||type.includes('金额')||type.includes('日期'))return['等于','不等于','大于','大于等于','小于','小于等于','为空','不为空'];return['等于','不等于','包含','不包含','为空','不为空']}

function FlatConditionEditor({conditions,properties,readonly,fieldCompare,onAdd,onUpdate,onRemove}:{conditions:RuleCondition[];properties:OntologyElement[];readonly:boolean;fieldCompare:boolean;onAdd:(element?:OntologyElement)=>void;onUpdate:(id:string,next:Partial<RuleCondition>)=>void;onRemove:(id:string)=>void}){
  return <div className="simple-condition-list">{conditions.length>0&&<div className="simple-condition-head"><span>序号</span><span>判断属性</span><span>运算符</span><span>{fieldCompare?'对比属性':'比较值'}</span><span>操作</span></div>}{conditions.map((condition,index)=>{const element=properties.find((item)=>item.code===condition.fieldCode);const unary=['为空','不为空'].includes(condition.operator);return <div className="simple-condition" key={condition.id}><b>{index+1}</b><select value={condition.fieldCode} disabled={readonly} onChange={(event)=>{const next=properties.find((item)=>item.code===event.target.value);onUpdate(condition.id,{fieldCode:event.target.value,fieldName:next?.name||'',fieldType:next?.dataType||'',operator:'等于'})}}><option value="">选择判断属性</option>{properties.map((item)=><option value={item.code} key={item.code}>{item.name}</option>)}</select><select value={condition.operator} disabled={readonly} onChange={(event)=>{const operator=event.target.value;onUpdate(condition.id,{operator,value:['为空','不为空'].includes(operator)?'':condition.value})}}>{operatorsFor(element).map((item)=><option key={item}>{item}</option>)}</select>{unary?<div className="unary-value">无需比较值</div>:fieldCompare?<select value={condition.valueFieldCode||''} disabled={readonly} onChange={(event)=>{const next=properties.find((item)=>item.code===event.target.value);onUpdate(condition.id,{valueMode:'field',value:'',valueFieldCode:event.target.value,valueFieldName:next?.name||''})}}><option value="">选择对比属性</option>{properties.map((item)=><option value={item.code} key={item.code}>{item.name}</option>)}</select>:<input value={condition.value} disabled={readonly} onChange={(event)=>onUpdate(condition.id,{valueMode:'literal',value:event.target.value})} placeholder="输入比较值"/>}{!readonly&&<button onClick={()=>onRemove(condition.id)}><Icon name="close" size={14}/></button>}</div>})}{!conditions.length&&<EmptyState title="尚未配置判断条件" description={fieldCompare?'请选择两个属性进行比较。':'请选择一个属性并输入比较值。'}/>} {!readonly&&<Button icon="plus" onClick={()=>onAdd()}>添加判断条件</Button>}</div>
}

function RelationLogic({scene,relations,hops,readonly,onAdd,onUpdate,onRemove}:{scene:SceneItem;relations:OntologyElement[];hops:PathHop[];readonly:boolean;onAdd:(relation:OntologyElement)=>void;onUpdate:(index:number,code:string)=>void;onRemove:(index:number)=>void}){
  return <div className="guided-logic"><div className="logic-origin"><span>起点对象</span><strong>{scene.objectName}</strong><small>继承自所属场景</small></div>{hops.map((hop,index)=><div className="guided-hop" key={index}><i>{index+1}</i><select value={relations.find((item)=>item.name===hop.relation)?.code||''} disabled={readonly} onChange={(event)=>onUpdate(index,event.target.value)}><option value="">选择第{index+1}跳关系</option>{relations.map((item)=><option value={item.code} key={item.code}>{item.name} · {item.dataType}</option>)}</select><div><span>{hop.from}</span><Icon name="chevron"/><strong>{hop.relation}</strong><Icon name="chevron"/><span>{hop.to}</span></div>{!readonly&&<button onClick={()=>onRemove(index)}><Icon name="close" size={14}/></button>}</div>)}{!hops.length&&<EmptyState title="尚未选择关系" description="选择一条关系，系统会自动生成起点、方向和目标对象。"/>}{!readonly&&hops.length<2&&<div className="element-choice-grid">{relations.map((item)=><button key={item.code} onClick={()=>onAdd(item)}><Icon name="link"/><div><strong>添加到关系路径</strong><span>{item.name}</span><small>{item.dataType}</small></div></button>)}</div>}</div>
}

function TimeLogic({events,config,readonly,onSelect,onChange}:{events:OntologyElement[];config:RuleItem['timeConfig'];readonly:boolean;onSelect:(event:OntologyElement)=>void;onChange:(config:RuleItem['timeConfig'])=>void}){
  return <div className="guided-logic"><div className="element-choice-grid">{events.map((item)=><button className={config.eventCode===item.code?'selected':''} disabled={readonly} key={item.code} onClick={()=>onSelect(item)}><Icon name="clock"/><div><strong>设为判断类</strong><span>{item.name}</span><small>{item.code}</small></div></button>)}</div><div className="time-sentence"><span>该类节点发生在场景目标类节点</span><select value={config.direction||'之前'} disabled={readonly} onChange={(event)=>onChange({...config,direction:event.target.value})}><option>之前</option><option>之后</option></select><input type="number" value={config.windowValue} disabled={readonly} onChange={(event)=>onChange({...config,windowValue:Number(event.target.value)})}/><select value={config.windowUnit} disabled={readonly} onChange={(event)=>onChange({...config,windowUnit:event.target.value})}><option>小时</option><option>天</option><option>月</option></select><span>以内</span></div></div>
}

function AggregateLogic({properties,scene,config,readonly,onChange}:{properties:OntologyElement[];scene:SceneItem;config:RuleItem['aggregateConfig'];readonly:boolean;onChange:(config:RuleItem['aggregateConfig'])=>void}){
  return <div className="guided-logic"><div className="form-section two-column"><Field label="统计属性 *"><select value={config.fieldCode} disabled={readonly} onChange={(event)=>onChange({...config,fieldCode:event.target.value})}><option value="">选择数字或金额属性</option>{properties.filter((item)=>/数字|金额/.test(item.dataType)).map((item)=><option value={item.code} key={item.code}>{item.name}</option>)}</select></Field><Field label="聚合函数 *"><select value={config.function} disabled={readonly} onChange={(event)=>onChange({...config,function:event.target.value})}><option>COUNT</option><option>SUM</option><option>AVG</option><option>MAX</option></select></Field><Field label="判断条件"><select value={config.operator} disabled={readonly} onChange={(event)=>onChange({...config,operator:event.target.value})}><option>大于</option><option>大于等于</option><option>等于</option><option>小于</option></select></Field><Field label="阈值 *"><input type="number" value={config.threshold} disabled={readonly} onChange={(event)=>onChange({...config,threshold:Number(event.target.value)})}/></Field></div><div className="inherit-note"><Icon name="check"/><span>默认按“{scene.objectName}”分组，统计窗口继承场景：{scene.observationValue}{scene.observationUnit}</span></div></div>
}

